"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeleteCascadeModeEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.api.DeleteCascadeModeEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link DeleteCascadeModeEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DeleteCascadeModeEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.api.DeleteCascadeModeEnum') {
}
exports.DeleteCascadeModeEnum = DeleteCascadeModeEnum;
exports.default = DeleteCascadeModeEnum;
//# sourceMappingURL=DeleteCascadeModeEnum.js.map