"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QualifiedParamList = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.api.QualifiedParamList.
 *
 * This actually imports the java class for further use.
 * The class {@link QualifiedParamListClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class QualifiedParamList extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.api.QualifiedParamList') {
}
exports.QualifiedParamList = QualifiedParamList;
exports.default = QualifiedParamList;
//# sourceMappingURL=QualifiedParamList.js.map