import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IValueSetEnumBinder as ca_uhn_fhir_model_api_IValueSetEnumBinder, IValueSetEnumBinderInterface as ca_uhn_fhir_model_api_IValueSetEnumBinderInterface } from "./../../model/api/IValueSetEnumBinder";
import { Enum as java_lang_Enum } from "./../../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Optional as java_util_Optional } from "./../../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link RestSearchParameterTypeEnum} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RestSearchParameterTypeEnumClass extends JavaClass {
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly NUMBER: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly DATE: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly STRING: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly TOKEN: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly REFERENCE: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly COMPOSITE: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly QUANTITY: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly URI: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly HAS: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static readonly SPECIAL: RestSearchParameterTypeEnumClass | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VALUESET_IDENTIFIER: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly VALUESET_NAME: string | null;
    /**
     * Original type: 'ca.uhn.fhir.model.api.IValueSetEnumBinder'
     */
    static readonly VALUESET_BINDER: ca_uhn_fhir_model_api_IValueSetEnumBinder | JavaInterfaceProxy<ca_uhn_fhir_model_api_IValueSetEnumBinderInterface> | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum[]'
     */
    static values(): Promise<(RestSearchParameterTypeEnum | null)[] | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum[]'
     */
    static valuesSync(): (RestSearchParameterTypeEnum | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static valueOf(var0: string | null): Promise<RestSearchParameterTypeEnum | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static valueOfSync(var0: string | null): RestSearchParameterTypeEnum | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static forCode(var0: string | null): Promise<RestSearchParameterTypeEnum | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    static forCodeSync(var0: string | null): RestSearchParameterTypeEnum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystem(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystemSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getCode(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getCodeSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const RestSearchParameterTypeEnum_base: typeof RestSearchParameterTypeEnumClass;
/**
 * Class ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link RestSearchParameterTypeEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RestSearchParameterTypeEnum extends RestSearchParameterTypeEnum_base {
}
export default RestSearchParameterTypeEnum;
//# sourceMappingURL=RestSearchParameterTypeEnum.d.ts.map