"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchTotalModeEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.api.SearchTotalModeEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link SearchTotalModeEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SearchTotalModeEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.api.SearchTotalModeEnum') {
}
exports.SearchTotalModeEnum = SearchTotalModeEnum;
exports.default = SearchTotalModeEnum;
//# sourceMappingURL=SearchTotalModeEnum.js.map