"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SortOrderEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.api.SortOrderEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link SortOrderEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SortOrderEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.api.SortOrderEnum') {
}
exports.SortOrderEnum = SortOrderEnum;
exports.default = SortOrderEnum;
//# sourceMappingURL=SortOrderEnum.js.map