"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BindingKind = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.utils.validation.constants.BindingKind.
 *
 * This actually imports the java class for further use.
 * The class {@link BindingKindClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BindingKind extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.utils.validation.constants.BindingKind') {
}
exports.BindingKind = BindingKind;
exports.default = BindingKind;
//# sourceMappingURL=BindingKind.js.map