import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { EncodingEnum as ca_uhn_fhir_rest_api_EncodingEnum } from "./../rest/api/EncodingEnum";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../java/util/Set";
import { Boolean as java_lang_Boolean } from "./../../../../java/lang/Boolean";
import { Collection as java_util_Collection, CollectionInterface as java_util_CollectionInterface } from "./../../../../java/util/Collection";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../java/util/List";
import { IBaseResource as org_hl7_fhir_instance_model_api_IBaseResource, IBaseResourceInterface as org_hl7_fhir_instance_model_api_IBaseResourceInterface } from "./../../../../org/hl7/fhir/instance/model/api/IBaseResource";
import { Reader as java_io_Reader } from "./../../../../java/io/Reader";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { InputStream as java_io_InputStream } from "./../../../../java/io/InputStream";
import { Writer as java_io_Writer } from "./../../../../java/io/Writer";
import { IIdType as org_hl7_fhir_instance_model_api_IIdType, IIdTypeInterface as org_hl7_fhir_instance_model_api_IIdTypeInterface } from "./../../../../org/hl7/fhir/instance/model/api/IIdType";
import { IParserErrorHandler as ca_uhn_fhir_parser_IParserErrorHandler, IParserErrorHandlerInterface as ca_uhn_fhir_parser_IParserErrorHandlerInterface } from "./IParserErrorHandler";
/**
 * This class just defines types, you should import {@link IParser} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IParserClass extends JavaClass {
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     */
    getEncoding(): Promise<ca_uhn_fhir_rest_api_EncodingEnum | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     */
    getEncodingSync(): ca_uhn_fhir_rest_api_EncodingEnum | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getDontStripVersionsFromReferencesAtPaths(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getDontStripVersionsFromReferencesAtPathsSync(): java_util_Set | null;
    /**
     * @return original return type: 'boolean'
     */
    isEncodeElementsAppliesToChildResourcesOnly(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEncodeElementsAppliesToChildResourcesOnlySync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setEncodeElementsAppliesToChildResourcesOnly(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setEncodeElementsAppliesToChildResourcesOnlySync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOverrideResourceIdWithBundleEntryFullUrl(var0: java_lang_Boolean | boolean | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOverrideResourceIdWithBundleEntryFullUrlSync(var0: java_lang_Boolean | boolean | null): IParser | null;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPaths(var0: (string | null)[] | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPathsSync(var0: (string | null)[] | null): IParser | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPaths(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPathsSync(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IParser | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getPreferTypes(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getPreferTypesSync(): java_util_List | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    setPreferTypes(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    setPreferTypesSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @return original return type: 'boolean'
     */
    isOmitResourceId(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isOmitResourceIdSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOmitResourceId(var0: java_lang_Boolean | boolean): Promise<IParser | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOmitResourceIdSync(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_io_Reader | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: java_io_Reader | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: java_lang_Class | null, var1: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_io_InputStream | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: java_io_InputStream | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: java_io_InputStream | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: java_lang_Class | null, var1: java_io_InputStream | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: java_io_Reader | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResourceSync(var0: java_lang_Class | null, var1: java_io_Reader | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setServerBaseUrl(var0: string | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setServerBaseUrlSync(var0: string | null): IParser | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setPrettyPrint(var0: java_lang_Boolean | boolean): Promise<IParser | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setPrettyPrintSync(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @return original return type: 'boolean'
     */
    isSummaryMode(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isSummaryModeSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSummaryMode(var0: java_lang_Boolean | boolean): Promise<IParser | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSummaryModeSync(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeElements(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeElementsSync(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): IParser | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'java.lang.String'
     */
    encodeResourceToString(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'java.lang.String'
     */
    encodeResourceToStringSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'java.io.Writer'
     * @return original return type: 'void'
     */
    encodeResourceToWriter(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_io_Writer | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'java.io.Writer'
     * @return original return type: 'void'
     */
    encodeResourceToWriterSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_io_Writer | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IIdType'
     */
    getEncodeForceResourceId(): Promise<org_hl7_fhir_instance_model_api_IIdType | null>;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IIdType'
     */
    getEncodeForceResourceIdSync(): org_hl7_fhir_instance_model_api_IIdType | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeForceResourceId(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeForceResourceIdSync(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): IParser | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSuppressNarratives(var0: java_lang_Boolean | boolean): Promise<IParser | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSuppressNarrativesSync(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontEncodeElements(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontEncodeElementsSync(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IParser | null;
    /**
     * @return original return type: 'java.lang.Boolean'
     */
    getStripVersionsFromReferences(): Promise<boolean | null>;
    /**
     * @return original return type: 'java.lang.Boolean'
     */
    getStripVersionsFromReferencesSync(): boolean | null;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setStripVersionsFromReferences(var0: java_lang_Boolean | boolean | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setStripVersionsFromReferencesSync(var0: java_lang_Boolean | boolean | null): IParser | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setParserErrorHandler(var0: ca_uhn_fhir_parser_IParserErrorHandler | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandlerInterface> | null): Promise<IParser | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setParserErrorHandlerSync(var0: ca_uhn_fhir_parser_IParserErrorHandler | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandlerInterface> | null): IParser | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIParserProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IParserInterface {
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     */
    getEncoding(): ca_uhn_fhir_rest_api_EncodingEnum | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getDontStripVersionsFromReferencesAtPaths(): java_util_Set | null;
    /**
     * @return original return type: 'boolean'
     */
    isEncodeElementsAppliesToChildResourcesOnly(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setEncodeElementsAppliesToChildResourcesOnly(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOverrideResourceIdWithBundleEntryFullUrl(var0: java_lang_Boolean | boolean | null): IParser | null;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPaths(var0: (string | null)[] | null): IParser | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontStripVersionsFromReferencesAtPaths(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IParser | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getPreferTypes(): java_util_List | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    setPreferTypes(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @return original return type: 'boolean'
     */
    isOmitResourceId(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setOmitResourceId(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_io_Reader | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_io_InputStream | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.InputStream'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: java_io_InputStream | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.io.Reader'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    parseResource(var0: java_lang_Class | null, var1: java_io_Reader | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setServerBaseUrl(var0: string | null): IParser | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setPrettyPrint(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @return original return type: 'boolean'
     */
    isSummaryMode(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSummaryMode(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeElements(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): IParser | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'java.lang.String'
     */
    encodeResourceToString(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'java.io.Writer'
     * @return original return type: 'void'
     */
    encodeResourceToWriter(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_io_Writer | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IIdType'
     */
    getEncodeForceResourceId(): org_hl7_fhir_instance_model_api_IIdType | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setEncodeForceResourceId(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): IParser | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setSuppressNarratives(var0: java_lang_Boolean | boolean): IParser | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setDontEncodeElements(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IParser | null;
    /**
     * @return original return type: 'java.lang.Boolean'
     */
    getStripVersionsFromReferences(): boolean | null;
    /**
     * @param var0 original type: 'java.lang.Boolean'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setStripVersionsFromReferences(var0: java_lang_Boolean | boolean | null): IParser | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler'
     * @return original return type: 'ca.uhn.fhir.parser.IParser'
     */
    setParserErrorHandler(var0: ca_uhn_fhir_parser_IParserErrorHandler | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandlerInterface> | null): IParser | null;
}
/**
 * Create a proxy for the {@link IParser} interface.
 * All required methods in {@link IParserInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIParserProxy(methods: IParserInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IParserInterface>;
declare const IParser_base: typeof IParserClass;
/**
 * Class ca.uhn.fhir.parser.IParser.
 *
 * This actually imports the java class for further use.
 * The class {@link IParserClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IParser extends IParser_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IParser;
//# sourceMappingURL=IParser.d.ts.map