import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IParserErrorHandler$IParseLocation as ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation, IParserErrorHandler$IParseLocationInterface as ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface } from "./IParserErrorHandler$IParseLocation";
import { BaseJsonLikeValue$ValueType as ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType } from "./json/BaseJsonLikeValue$ValueType";
import { BaseJsonLikeValue$ScalarType as ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType } from "./json/BaseJsonLikeValue$ScalarType";
/**
 * This class just defines types, you should import {@link IParserErrorHandler} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IParserErrorHandlerClass extends JavaClass {
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    extensionContainsValueAndNestedExtensions(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    extensionContainsValueAndNestedExtensionsSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    invalidValue(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    invalidValueSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownElementSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var3 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @param var4 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var5 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @return original return type: 'void'
     */
    incorrectJsonType(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var3: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null, var4: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var5: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var3 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @param var4 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var5 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @return original return type: 'void'
     */
    incorrectJsonTypeSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var3: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null, var4: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var5: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownReference(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownReferenceSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownAttribute(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownAttributeSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    missingRequiredElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    missingRequiredElementSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    containedResourceWithNoId(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    containedResourceWithNoIdSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unexpectedRepeatingElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unexpectedRepeatingElementSync(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIParserErrorHandlerProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IParserErrorHandlerInterface {
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    extensionContainsValueAndNestedExtensions(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    invalidValue(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var3 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @param var4 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType'
     * @param var5 original type: 'ca.uhn.fhir.parser.json.BaseJsonLikeValue$ScalarType'
     * @return original return type: 'void'
     */
    incorrectJsonType(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null, var2: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var3: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null, var4: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ValueType | null, var5: ca_uhn_fhir_parser_json_BaseJsonLikeValue$ScalarType | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownReference(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unknownAttribute(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    missingRequiredElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @return original return type: 'void'
     */
    containedResourceWithNoId(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.parser.IParserErrorHandler$IParseLocation'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    unexpectedRepeatingElement(var0: ca_uhn_fhir_parser_IParserErrorHandler$IParseLocation | JavaInterfaceProxy<ca_uhn_fhir_parser_IParserErrorHandler$IParseLocationInterface> | null, var1: string | null): void;
}
/**
 * Create a proxy for the {@link IParserErrorHandler} interface.
 * All required methods in {@link IParserErrorHandlerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIParserErrorHandlerProxy(methods: IParserErrorHandlerInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IParserErrorHandlerInterface>;
declare const IParserErrorHandler_base: typeof IParserErrorHandlerClass;
/**
 * Class ca.uhn.fhir.parser.IParserErrorHandler.
 *
 * This actually imports the java class for further use.
 * The class {@link IParserErrorHandlerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IParserErrorHandler extends IParserErrorHandler_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IParserErrorHandler;
//# sourceMappingURL=IParserErrorHandler.d.ts.map