"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IInterceptorService = exports.createIInterceptorServiceProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IInterceptorService} interface.
 * All required methods in {@link IInterceptorServiceInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIInterceptorServiceProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.interceptor.api.IInterceptorService', methods, opts);
}
exports.createIInterceptorServiceProxy = createIInterceptorServiceProxy;
/**
 * Class ca.uhn.fhir.interceptor.api.IInterceptorService.
 *
 * This actually imports the java class for further use.
 * The class {@link IInterceptorServiceClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IInterceptorService extends (0, java_bridge_1.importClass)('ca.uhn.fhir.interceptor.api.IInterceptorService') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IInterceptorService = IInterceptorService;
exports.default = IInterceptorService;
//# sourceMappingURL=IInterceptorService.js.map