"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHttpResponse = exports.createIHttpResponseProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IHttpResponse} interface.
 * All required methods in {@link IHttpResponseInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIHttpResponseProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.client.api.IHttpResponse', methods, opts);
}
exports.createIHttpResponseProxy = createIHttpResponseProxy;
/**
 * Class ca.uhn.fhir.rest.client.api.IHttpResponse.
 *
 * This actually imports the java class for further use.
 * The class {@link IHttpResponseClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IHttpResponse extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.client.api.IHttpResponse') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IHttpResponse = IHttpResponse;
exports.default = IHttpResponse;
//# sourceMappingURL=IHttpResponse.js.map