"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHttpRequest = exports.createIHttpRequestProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IHttpRequest} interface.
 * All required methods in {@link IHttpRequestInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIHttpRequestProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.client.api.IHttpRequest', methods, opts);
}
exports.createIHttpRequestProxy = createIHttpRequestProxy;
/**
 * Class ca.uhn.fhir.rest.client.api.IHttpRequest.
 *
 * This actually imports the java class for further use.
 * The class {@link IHttpRequestClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IHttpRequest extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.client.api.IHttpRequest') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IHttpRequest = IHttpRequest;
exports.default = IHttpRequest;
//# sourceMappingURL=IHttpRequest.js.map