"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRestfulClientFactory = exports.createIRestfulClientFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IRestfulClientFactory} interface.
 * All required methods in {@link IRestfulClientFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIRestfulClientFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.client.api.IRestfulClientFactory', methods, opts);
}
exports.createIRestfulClientFactoryProxy = createIRestfulClientFactoryProxy;
/**
 * Class ca.uhn.fhir.rest.client.api.IRestfulClientFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link IRestfulClientFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IRestfulClientFactory extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.client.api.IRestfulClientFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IRestfulClientFactory = IRestfulClientFactory;
exports.default = IRestfulClientFactory;
//# sourceMappingURL=IRestfulClientFactory.js.map