"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRestfulClient = exports.createIRestfulClientProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IRestfulClient} interface.
 * All required methods in {@link IRestfulClientInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIRestfulClientProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.client.api.IRestfulClient', methods, opts);
}
exports.createIRestfulClientProxy = createIRestfulClientProxy;
/**
 * Class ca.uhn.fhir.rest.client.api.IRestfulClient.
 *
 * This actually imports the java class for further use.
 * The class {@link IRestfulClientClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IRestfulClient extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.client.api.IRestfulClient') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IRestfulClient = IRestfulClient;
exports.default = IRestfulClient;
//# sourceMappingURL=IRestfulClient.js.map