"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerValidationModeEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.client.api.ServerValidationModeEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link ServerValidationModeEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ServerValidationModeEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.client.api.ServerValidationModeEnum') {
}
exports.ServerValidationModeEnum = ServerValidationModeEnum;
exports.default = ServerValidationModeEnum;
//# sourceMappingURL=ServerValidationModeEnum.js.map