import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Element as org_hl7_fhir_r5_elementmodel_Element } from "./../../r5/elementmodel/Element";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
/**
 * This class just defines types, you should import {@link PercentageTracker} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PercentageTrackerClass extends JavaClass {
    /**
     * @return original return type: 'void'
     */
    done(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    doneSync(): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrl(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrlSync(): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @return original return type: 'void'
     */
    seeElement(var0: org_hl7_fhir_r5_elementmodel_Element | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @return original return type: 'void'
     */
    seeElementSync(var0: org_hl7_fhir_r5_elementmodel_Element | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.validation.instance.PercentageTracker'
     */
    static newInstanceAsync(var0: java_lang_Integer | number, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean): Promise<PercentageTracker>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     */
    constructor(var0: java_lang_Integer | number, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean);
}
declare const PercentageTracker_base: typeof PercentageTrackerClass;
/**
 * Class org.hl7.fhir.validation.instance.PercentageTracker.
 *
 * This actually imports the java class for further use.
 * The class {@link PercentageTrackerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PercentageTracker extends PercentageTracker_base {
}
export default PercentageTracker;
//# sourceMappingURL=PercentageTracker.d.ts.map