"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseIdentifierDt = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.model.base.composite.BaseIdentifierDt.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseIdentifierDtClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BaseIdentifierDt extends (0, java_bridge_1.importClass)('ca.uhn.fhir.model.base.composite.BaseIdentifierDt') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.BaseIdentifierDt = BaseIdentifierDt;
exports.default = BaseIdentifierDt;
//# sourceMappingURL=BaseIdentifierDt.js.map