"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IWorkerContextManager$ICanonicalResourceLocator = exports.createIWorkerContextManager$ICanonicalResourceLocatorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IWorkerContextManager$ICanonicalResourceLocator} interface.
 * All required methods in {@link IWorkerContextManager$ICanonicalResourceLocatorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIWorkerContextManager$ICanonicalResourceLocatorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.context.IWorkerContextManager$ICanonicalResourceLocator', methods, opts);
}
exports.createIWorkerContextManager$ICanonicalResourceLocatorProxy = createIWorkerContextManager$ICanonicalResourceLocatorProxy;
/**
 * Class org.hl7.fhir.r5.context.IWorkerContextManager$ICanonicalResourceLocator.
 *
 * This actually imports the java class for further use.
 * The class {@link IWorkerContextManager$ICanonicalResourceLocatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IWorkerContextManager$ICanonicalResourceLocator extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.context.IWorkerContextManager$ICanonicalResourceLocator') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IWorkerContextManager$ICanonicalResourceLocator = IWorkerContextManager$ICanonicalResourceLocator;
exports.default = IWorkerContextManager$ICanonicalResourceLocator;
//# sourceMappingURL=IWorkerContextManager$ICanonicalResourceLocator.js.map