"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IWorkerContext$ILoggingService$LogCategory = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.context.IWorkerContext$ILoggingService$LogCategory.
 *
 * This actually imports the java class for further use.
 * The class {@link IWorkerContext$ILoggingService$LogCategoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IWorkerContext$ILoggingService$LogCategory extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.context.IWorkerContext$ILoggingService$LogCategory') {
}
exports.IWorkerContext$ILoggingService$LogCategory = IWorkerContext$ILoggingService$LogCategory;
exports.default = IWorkerContext$ILoggingService$LogCategory;
//# sourceMappingURL=IWorkerContext$ILoggingService$LogCategory.js.map