"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleWorkerContext$IValidatorFactory = exports.createSimpleWorkerContext$IValidatorFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link SimpleWorkerContext$IValidatorFactory} interface.
 * All required methods in {@link SimpleWorkerContext$IValidatorFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSimpleWorkerContext$IValidatorFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.context.SimpleWorkerContext$IValidatorFactory', methods, opts);
}
exports.createSimpleWorkerContext$IValidatorFactoryProxy = createSimpleWorkerContext$IValidatorFactoryProxy;
/**
 * Class org.hl7.fhir.r5.context.SimpleWorkerContext$IValidatorFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link SimpleWorkerContext$IValidatorFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SimpleWorkerContext$IValidatorFactory extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.context.SimpleWorkerContext$IValidatorFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.SimpleWorkerContext$IValidatorFactory = SimpleWorkerContext$IValidatorFactory;
exports.default = SimpleWorkerContext$IValidatorFactory;
//# sourceMappingURL=SimpleWorkerContext$IValidatorFactory.js.map