"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminologyCache$CacheEntry = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.context.TerminologyCache$CacheEntry.
 *
 * This actually imports the java class for further use.
 * The class {@link TerminologyCache$CacheEntryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TerminologyCache$CacheEntry extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.context.TerminologyCache$CacheEntry') {
}
exports.TerminologyCache$CacheEntry = TerminologyCache$CacheEntry;
exports.default = TerminologyCache$CacheEntry;
//# sourceMappingURL=TerminologyCache$CacheEntry.js.map