"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Address = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Address.
 *
 * This actually imports the java class for further use.
 * The class {@link AddressClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Address extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Address') {
}
exports.Address = Address;
exports.default = Address;
//# sourceMappingURL=Address.js.map