"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Availability$AvailabilityAvailableTimeComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Availability$AvailabilityAvailableTimeComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link Availability$AvailabilityAvailableTimeComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Availability$AvailabilityAvailableTimeComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Availability$AvailabilityAvailableTimeComponent') {
}
exports.Availability$AvailabilityAvailableTimeComponent = Availability$AvailabilityAvailableTimeComponent;
exports.default = Availability$AvailabilityAvailableTimeComponent;
//# sourceMappingURL=Availability$AvailabilityAvailableTimeComponent.js.map