import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Base$ProfileSource as org_hl7_fhir_r5_model_Base$ProfileSource } from "./Base$ProfileSource";
import { Base$ValidationReason as org_hl7_fhir_r5_model_Base$ValidationReason } from "./Base$ValidationReason";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link Base$ValidationMode} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Base$ValidationModeClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     */
    getSource(): Promise<org_hl7_fhir_r5_model_Base$ProfileSource | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     */
    getSourceSync(): org_hl7_fhir_r5_model_Base$ProfileSource | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    withSource(var0: org_hl7_fhir_r5_model_Base$ProfileSource | null): Promise<Base$ValidationMode | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    withSourceSync(var0: org_hl7_fhir_r5_model_Base$ProfileSource | null): Base$ValidationMode | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     */
    getReason(): Promise<org_hl7_fhir_r5_model_Base$ValidationReason | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     */
    getReasonSync(): org_hl7_fhir_r5_model_Base$ValidationReason | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    withReason(var0: org_hl7_fhir_r5_model_Base$ValidationReason | null): Promise<Base$ValidationMode | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    withReasonSync(var0: org_hl7_fhir_r5_model_Base$ValidationReason | null): Base$ValidationMode | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     * @param var1 original type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_model_Base$ValidationReason | null, var1: org_hl7_fhir_r5_model_Base$ProfileSource | null): Promise<Base$ValidationMode>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     * @param var1 original type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     */
    constructor(var0: org_hl7_fhir_r5_model_Base$ValidationReason | null, var1: org_hl7_fhir_r5_model_Base$ProfileSource | null);
}
declare const Base$ValidationMode_base: typeof Base$ValidationModeClass;
/**
 * Class org.hl7.fhir.r5.model.Base$ValidationMode.
 *
 * This actually imports the java class for further use.
 * The class {@link Base$ValidationModeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Base$ValidationMode extends Base$ValidationMode_base {
}
export default Base$ValidationMode;
//# sourceMappingURL=Base$ValidationMode.d.ts.map