import { JavaClass, BasicOrJavaType } from "java-bridge";
import { ElementDefinition as org_hl7_fhir_r5_model_ElementDefinition } from "./ElementDefinition";
import { Base$ProfileSource as org_hl7_fhir_r5_model_Base$ProfileSource } from "./Base$ProfileSource";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./StructureDefinition";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
import { Base$ValidationReason as org_hl7_fhir_r5_model_Base$ValidationReason } from "./Base$ValidationReason";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Base as org_hl7_fhir_r5_model_Base } from "./Base";
import { Base$ValidationMode as org_hl7_fhir_r5_model_Base$ValidationMode } from "./Base$ValidationMode";
/**
 * This class just defines types, you should import {@link Base$ValidationInfo} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Base$ValidationInfoClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    getDefinition(): Promise<org_hl7_fhir_r5_model_ElementDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    getDefinitionSync(): org_hl7_fhir_r5_model_ElementDefinition | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     */
    getSource(): Promise<org_hl7_fhir_r5_model_Base$ProfileSource | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ProfileSource'
     */
    getSourceSync(): org_hl7_fhir_r5_model_Base$ProfileSource | null;
    /**
     * @return original return type: 'boolean'
     */
    isValid(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isValidSync(): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getStructure(): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getStructureSync(): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setValid(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setValidSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     */
    getReason(): Promise<org_hl7_fhir_r5_model_Base$ValidationReason | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationReason'
     */
    getReasonSync(): org_hl7_fhir_r5_model_Base$ValidationReason | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     * @return original return type: 'org.hl7.fhir.r5.model.Base$ValidationInfo'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_model_Base | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: org_hl7_fhir_r5_model_ElementDefinition | null, var3: org_hl7_fhir_r5_model_Base$ValidationMode | null): Promise<Base$ValidationInfo>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Base'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.model.Base$ValidationMode'
     */
    constructor(var0: org_hl7_fhir_r5_model_Base | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: org_hl7_fhir_r5_model_ElementDefinition | null, var3: org_hl7_fhir_r5_model_Base$ValidationMode | null);
}
declare const Base$ValidationInfo_base: typeof Base$ValidationInfoClass;
/**
 * Class org.hl7.fhir.r5.model.Base$ValidationInfo.
 *
 * This actually imports the java class for further use.
 * The class {@link Base$ValidationInfoClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Base$ValidationInfo extends Base$ValidationInfo_base {
}
export default Base$ValidationInfo;
//# sourceMappingURL=Base$ValidationInfo.d.ts.map