import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Enum as java_lang_Enum } from "./../../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Optional as java_util_Optional } from "./../../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link Bundle$LinkRelationTypes} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Bundle$LinkRelationTypesClass extends JavaClass {
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ABOUT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ACL: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ALTERNATE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly AMPHTML: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly APPENDIX: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly APPLETOUCHICON: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly APPLETOUCHSTARTUPIMAGE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ARCHIVES: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly AUTHOR: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly BLOCKEDBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly BOOKMARK: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CANONICAL: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CHAPTER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CITEAS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly COLLECTION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CONTENTS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CONVERTEDFROM: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly COPYRIGHT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CREATEFORM: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly CURRENT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly DESCRIBEDBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly DESCRIBES: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly DISCLOSURE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly DNSPREFETCH: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly DUPLICATE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly EDIT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly EDITFORM: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly EDITMEDIA: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ENCLOSURE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly EXTERNAL: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly FIRST: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly GLOSSARY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly HELP: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly HOSTS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly HUB: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ICON: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INDEX: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALAFTER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALBEFORE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALCONTAINS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALDISJOINT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALDURING: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALEQUALS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALFINISHEDBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALFINISHES: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALIN: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALMEETS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALMETBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALOVERLAPPEDBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALOVERLAPS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALSTARTEDBY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly INTERVALSTARTS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ITEM: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly LAST: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly LATESTVERSION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly LICENSE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly LINKSET: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly LRDD: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MANIFEST: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MASKICON: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MEDIAFEED: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MEMENTO: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MICROPUB: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MODULEPRELOAD: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MONITOR: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly MONITORGROUP: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NEXT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NEXTARCHIVE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NOFOLLOW: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NOOPENER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NOREFERRER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly OPENER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly OPENID2_LOCALID: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly OPENID2_PROVIDER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly ORIGINAL: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly P3PV1: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PAYMENT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PINGBACK: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PRECONNECT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREDECESSORVERSION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREFETCH: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PRELOAD: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PRERENDER: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREV: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREVIEW: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREVIOUS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PREVARCHIVE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PRIVACYPOLICY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PROFILE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly PUBLICATION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly RELATED: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly RESTCONF: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly REPLIES: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly RULEINPUT: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SEARCH: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SECTION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SELF: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SERVICE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SERVICEDESC: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SERVICEDOC: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SERVICEMETA: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SPONSORED: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly START: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly STATUS: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly STYLESHEET: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SUBSECTION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SUCCESSORVERSION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly SUNSET: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly TAG: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly TERMSOFSERVICE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly TIMEGATE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly TIMEMAP: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly TYPE: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly UGC: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly UP: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly VERSIONHISTORY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly VIA: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly WEBMENTION: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly WORKINGCOPY: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly WORKINGCOPYOF: Bundle$LinkRelationTypesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static readonly NULL: Bundle$LinkRelationTypesClass | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes[]'
     */
    static values(): Promise<(Bundle$LinkRelationTypes | null)[] | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes[]'
     */
    static valuesSync(): (Bundle$LinkRelationTypes | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static valueOf(var0: string | null): Promise<Bundle$LinkRelationTypes | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static valueOfSync(var0: string | null): Bundle$LinkRelationTypes | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinition(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinitionSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystem(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystemSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplay(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplaySync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static fromCode(var0: string | null): Promise<Bundle$LinkRelationTypes | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Bundle$LinkRelationTypes'
     */
    static fromCodeSync(var0: string | null): Bundle$LinkRelationTypes | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCode(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCodeSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const Bundle$LinkRelationTypes_base: typeof Bundle$LinkRelationTypesClass;
/**
 * Class org.hl7.fhir.r5.model.Bundle$LinkRelationTypes.
 *
 * This actually imports the java class for further use.
 * The class {@link Bundle$LinkRelationTypesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Bundle$LinkRelationTypes extends Bundle$LinkRelationTypes_base {
}
export default Bundle$LinkRelationTypes;
//# sourceMappingURL=Bundle$LinkRelationTypes.d.ts.map