"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CapabilityStatement$ReferenceHandlingPolicy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.CapabilityStatement$ReferenceHandlingPolicy.
 *
 * This actually imports the java class for further use.
 * The class {@link CapabilityStatement$ReferenceHandlingPolicyClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CapabilityStatement$ReferenceHandlingPolicy extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.CapabilityStatement$ReferenceHandlingPolicy') {
}
exports.CapabilityStatement$ReferenceHandlingPolicy = CapabilityStatement$ReferenceHandlingPolicy;
exports.default = CapabilityStatement$ReferenceHandlingPolicy;
//# sourceMappingURL=CapabilityStatement$ReferenceHandlingPolicy.js.map