"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CapabilityStatement$CapabilityStatementRestResourceOperationComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.CapabilityStatement$CapabilityStatementRestResourceOperationComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link CapabilityStatement$CapabilityStatementRestResourceOperationComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CapabilityStatement$CapabilityStatementRestResourceOperationComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.CapabilityStatement$CapabilityStatementRestResourceOperationComponent') {
}
exports.CapabilityStatement$CapabilityStatementRestResourceOperationComponent = CapabilityStatement$CapabilityStatementRestResourceOperationComponent;
exports.default = CapabilityStatement$CapabilityStatementRestResourceOperationComponent;
//# sourceMappingURL=CapabilityStatement$CapabilityStatementRestResourceOperationComponent.js.map