"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CapabilityStatement = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.CapabilityStatement.
 *
 * This actually imports the java class for further use.
 * The class {@link CapabilityStatementClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CapabilityStatement extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.CapabilityStatement') {
}
exports.CapabilityStatement = CapabilityStatement;
exports.default = CapabilityStatement;
//# sourceMappingURL=CapabilityStatement.js.map