"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CodeSystem$PropertyType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.CodeSystem$PropertyType.
 *
 * This actually imports the java class for further use.
 * The class {@link CodeSystem$PropertyTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CodeSystem$PropertyType extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.CodeSystem$PropertyType') {
}
exports.CodeSystem$PropertyType = CodeSystem$PropertyType;
exports.default = CodeSystem$PropertyType;
//# sourceMappingURL=CodeSystem$PropertyType.js.map