"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CodeSystem$CodeSystemFilterComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.CodeSystem$CodeSystemFilterComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link CodeSystem$CodeSystemFilterComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CodeSystem$CodeSystemFilterComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.CodeSystem$CodeSystemFilterComponent') {
}
exports.CodeSystem$CodeSystemFilterComponent = CodeSystem$CodeSystemFilterComponent;
exports.default = CodeSystem$CodeSystemFilterComponent;
//# sourceMappingURL=CodeSystem$CodeSystemFilterComponent.js.map