"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementDefinition$DiscriminatorType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.ElementDefinition$DiscriminatorType.
 *
 * This actually imports the java class for further use.
 * The class {@link ElementDefinition$DiscriminatorTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ElementDefinition$DiscriminatorType extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.ElementDefinition$DiscriminatorType') {
}
exports.ElementDefinition$DiscriminatorType = ElementDefinition$DiscriminatorType;
exports.default = ElementDefinition$DiscriminatorType;
//# sourceMappingURL=ElementDefinition$DiscriminatorType.js.map