"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementDefinition$AdditionalBindingPurposeVS = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.ElementDefinition$AdditionalBindingPurposeVS.
 *
 * This actually imports the java class for further use.
 * The class {@link ElementDefinition$AdditionalBindingPurposeVSClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ElementDefinition$AdditionalBindingPurposeVS extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.ElementDefinition$AdditionalBindingPurposeVS') {
}
exports.ElementDefinition$AdditionalBindingPurposeVS = ElementDefinition$AdditionalBindingPurposeVS;
exports.default = ElementDefinition$AdditionalBindingPurposeVS;
//# sourceMappingURL=ElementDefinition$AdditionalBindingPurposeVS.js.map