import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Enum as java_lang_Enum } from "./../../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Optional as java_util_Optional } from "./../../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link Enumerations$VersionIndependentResourceTypesAll} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Enumerations$VersionIndependentResourceTypesAllClass extends JavaClass {
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ACCOUNT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ACTIVITYDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ACTORDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ADMINISTRABLEPRODUCTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ADVERSEEVENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ALLERGYINTOLERANCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly APPOINTMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly APPOINTMENTRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ARTIFACTASSESSMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly AUDITEVENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BASIC: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BINARY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BIOLOGICALLYDERIVEDPRODUCT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BIOLOGICALLYDERIVEDPRODUCTDISPENSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BODYSTRUCTURE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BUNDLE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CANONICALRESOURCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CAPABILITYSTATEMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CAREPLAN: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CARETEAM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CHARGEITEM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CHARGEITEMDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CITATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CLAIM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CLAIMRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CLINICALIMPRESSION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CLINICALUSEDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CODESYSTEM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COMMUNICATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COMMUNICATIONREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COMPARTMENTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COMPOSITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONCEPTMAP: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONDITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONDITIONDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONSENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONTRACT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COVERAGE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COVERAGEELIGIBILITYREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly COVERAGEELIGIBILITYRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DETECTEDISSUE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEASSOCIATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEDISPENSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEMETRIC: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEUSAGE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DIAGNOSTICREPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DOCUMENTREFERENCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DOMAINRESOURCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ENCOUNTER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ENCOUNTERHISTORY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ENDPOINT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ENROLLMENTREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ENROLLMENTRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EPISODEOFCARE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EVENTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EVIDENCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EVIDENCEREPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EVIDENCEVARIABLE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EXAMPLESCENARIO: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EXPLANATIONOFBENEFIT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly FAMILYMEMBERHISTORY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly FLAG: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly FORMULARYITEM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly GENOMICSTUDY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly GOAL: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly GRAPHDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly GROUP: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly GUIDANCERESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly HEALTHCARESERVICE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMAGINGSELECTION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMAGINGSTUDY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMMUNIZATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMMUNIZATIONEVALUATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMMUNIZATIONRECOMMENDATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMPLEMENTATIONGUIDE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly INGREDIENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly INSURANCEPLAN: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly INVENTORYITEM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly INVENTORYREPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly INVOICE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly LIBRARY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly LINKAGE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly LIST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly LOCATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MANUFACTUREDITEMDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEASURE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEASUREREPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONADMINISTRATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONDISPENSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONKNOWLEDGE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONSTATEMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MESSAGEDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MESSAGEHEADER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly METADATARESOURCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MOLECULARSEQUENCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly NAMINGSYSTEM: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly NUTRITIONINTAKE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly NUTRITIONORDER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly NUTRITIONPRODUCT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly OBSERVATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly OBSERVATIONDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly OPERATIONDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly OPERATIONOUTCOME: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ORGANIZATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ORGANIZATIONAFFILIATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PACKAGEDPRODUCTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PARAMETERS: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PATIENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PAYMENTNOTICE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PAYMENTRECONCILIATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PERMISSION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PERSON: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PLANDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PRACTITIONER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PRACTITIONERROLE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PROCEDURE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PROVENANCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly QUESTIONNAIRE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly QUESTIONNAIRERESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly REGULATEDAUTHORIZATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RELATEDPERSON: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly REQUESTORCHESTRATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly REQUIREMENTS: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RESEARCHSTUDY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RESEARCHSUBJECT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RESOURCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RISKASSESSMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SCHEDULE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SEARCHPARAMETER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SERVICEREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SLOT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SPECIMEN: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SPECIMENDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly STRUCTUREDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly STRUCTUREMAP: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSCRIPTION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSCRIPTIONSTATUS: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSCRIPTIONTOPIC: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCEDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCENUCLEICACID: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCEPOLYMER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCEPROTEIN: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCEREFERENCEINFORMATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCESOURCEMATERIAL: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUPPLYDELIVERY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUPPLYREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TASK: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TERMINOLOGYCAPABILITIES: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TESTPLAN: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TESTREPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TESTSCRIPT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly TRANSPORT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly VALUESET: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly VERIFICATIONRESULT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly VISIONPRESCRIPTION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly BODYSITE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CATALOGENTRY: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly CONFORMANCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DATAELEMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICECOMPONENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEUSEREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DEVICEUSESTATEMENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DIAGNOSTICORDER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly DOCUMENTMANIFEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EFFECTEVIDENCESYNTHESIS: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ELIGIBILITYREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ELIGIBILITYRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly EXPANSIONPROFILE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMAGINGMANIFEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly IMAGINGOBJECTSELECTION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDIA: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONORDER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICATIONUSAGE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTAUTHORIZATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTCONTRAINDICATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTINDICATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTINGREDIENT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTINTERACTION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTMANUFACTURED: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTPACKAGED: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTPHARMACEUTICAL: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly MEDICINALPRODUCTUNDESIRABLEEFFECT: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ORDER: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly ORDERRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PROCEDUREREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PROCESSREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly PROCESSRESPONSE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly REFERRALREQUEST: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly REQUESTGROUP: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RESEARCHDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RESEARCHELEMENTDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly RISKEVIDENCESYNTHESIS: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SEQUENCE: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SERVICEDEFINITION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly SUBSTANCESPECIFICATION: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static readonly NULL: Enumerations$VersionIndependentResourceTypesAllClass | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll[]'
     */
    static values(): Promise<(Enumerations$VersionIndependentResourceTypesAll | null)[] | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll[]'
     */
    static valuesSync(): (Enumerations$VersionIndependentResourceTypesAll | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static valueOf(var0: string | null): Promise<Enumerations$VersionIndependentResourceTypesAll | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static valueOfSync(var0: string | null): Enumerations$VersionIndependentResourceTypesAll | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinition(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinitionSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystem(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystemSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplay(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplaySync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static fromCode(var0: string | null): Promise<Enumerations$VersionIndependentResourceTypesAll | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll'
     */
    static fromCodeSync(var0: string | null): Enumerations$VersionIndependentResourceTypesAll | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCode(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCodeSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    static isValidCode(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    static isValidCodeSync(var0: string | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const Enumerations$VersionIndependentResourceTypesAll_base: typeof Enumerations$VersionIndependentResourceTypesAllClass;
/**
 * Class org.hl7.fhir.r5.model.Enumerations$VersionIndependentResourceTypesAll.
 *
 * This actually imports the java class for further use.
 * The class {@link Enumerations$VersionIndependentResourceTypesAllClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Enumerations$VersionIndependentResourceTypesAll extends Enumerations$VersionIndependentResourceTypesAll_base {
}
export default Enumerations$VersionIndependentResourceTypesAll;
//# sourceMappingURL=Enumerations$VersionIndependentResourceTypesAll.d.ts.map