import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Enum as java_lang_Enum } from "./../../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Optional as java_util_Optional } from "./../../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link Enumerations$CommonLanguages} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Enumerations$CommonLanguagesClass extends JavaClass {
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly AR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly BG: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly BGBG: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly BN: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly CS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly CSCZ: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly BS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly BSBA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DADK: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DEAT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DECH: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly DEDE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly EL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ELGR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly EN: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENAU: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENCA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENGB: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENIN: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENNZ: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENSG: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ENUS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ES: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ESAR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ESES: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ESUY: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ET: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ETEE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FI: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FRBE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FRCH: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FRFR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FIFI: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FRCA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FY: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly FYNL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly HI: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly HR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly HRHR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly IS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ISIS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly IT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ITCH: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ITIT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly JA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly KO: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly LT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly LTLT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly LV: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly LVLV: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NLBE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NLNL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NO: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NONO: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PA: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PLPL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PTPT: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly PTBR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly RO: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly RORO: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly RU: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly RURU: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SK: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SKSK: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SL: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SLSI: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SR: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SRRS: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SV: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly SVSE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly TE: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ZH: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ZHCN: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ZHHK: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ZHSG: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly ZHTW: Enumerations$CommonLanguagesClass | null;
    /**
     * Original type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static readonly NULL: Enumerations$CommonLanguagesClass | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages[]'
     */
    static values(): Promise<(Enumerations$CommonLanguages | null)[] | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages[]'
     */
    static valuesSync(): (Enumerations$CommonLanguages | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static valueOf(var0: string | null): Promise<Enumerations$CommonLanguages | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static valueOfSync(var0: string | null): Enumerations$CommonLanguages | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinition(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefinitionSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystem(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getSystemSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplay(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDisplaySync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static fromCode(var0: string | null): Promise<Enumerations$CommonLanguages | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.Enumerations$CommonLanguages'
     */
    static fromCodeSync(var0: string | null): Enumerations$CommonLanguages | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCode(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toCodeSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    static isValidCode(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    static isValidCodeSync(var0: string | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const Enumerations$CommonLanguages_base: typeof Enumerations$CommonLanguagesClass;
/**
 * Class org.hl7.fhir.r5.model.Enumerations$CommonLanguages.
 *
 * This actually imports the java class for further use.
 * The class {@link Enumerations$CommonLanguagesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Enumerations$CommonLanguages extends Enumerations$CommonLanguages_base {
}
export default Enumerations$CommonLanguages;
//# sourceMappingURL=Enumerations$CommonLanguages.d.ts.map