"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Enumerations$FHIRVersion = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Enumerations$FHIRVersion.
 *
 * This actually imports the java class for further use.
 * The class {@link Enumerations$FHIRVersionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Enumerations$FHIRVersion extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Enumerations$FHIRVersion') {
}
exports.Enumerations$FHIRVersion = Enumerations$FHIRVersion;
exports.default = Enumerations$FHIRVersion;
//# sourceMappingURL=Enumerations$FHIRVersion.js.map