"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnumFactory = exports.createEnumFactoryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link EnumFactory} interface.
 * All required methods in {@link EnumFactoryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createEnumFactoryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.model.EnumFactory', methods, opts);
}
exports.createEnumFactoryProxy = createEnumFactoryProxy;
/**
 * Class org.hl7.fhir.r5.model.EnumFactory.
 *
 * This actually imports the java class for further use.
 * The class {@link EnumFactoryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class EnumFactory extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.EnumFactory') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.EnumFactory = EnumFactory;
exports.default = EnumFactory;
//# sourceMappingURL=EnumFactory.js.map