"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ExpressionNode = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.ExpressionNode.
 *
 * This actually imports the java class for further use.
 * The class {@link ExpressionNodeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ExpressionNode extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.ExpressionNode') {
}
exports.ExpressionNode = ExpressionNode;
exports.default = ExpressionNode;
//# sourceMappingURL=ExpressionNode.js.map