"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Integer64Type = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Integer64Type.
 *
 * This actually imports the java class for further use.
 * The class {@link Integer64TypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Integer64Type extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Integer64Type') {
}
exports.Integer64Type = Integer64Type;
exports.default = Integer64Type;
//# sourceMappingURL=Integer64Type.js.map