"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PrimitiveType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.PrimitiveType.
 *
 * This actually imports the java class for further use.
 * The class {@link PrimitiveTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class PrimitiveType extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.PrimitiveType') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.PrimitiveType = PrimitiveType;
exports.default = PrimitiveType;
//# sourceMappingURL=PrimitiveType.js.map