"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Questionnaire$QuestionnaireItemOperator = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Questionnaire$QuestionnaireItemOperator.
 *
 * This actually imports the java class for further use.
 * The class {@link Questionnaire$QuestionnaireItemOperatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Questionnaire$QuestionnaireItemOperator extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Questionnaire$QuestionnaireItemOperator') {
}
exports.Questionnaire$QuestionnaireItemOperator = Questionnaire$QuestionnaireItemOperator;
exports.default = Questionnaire$QuestionnaireItemOperator;
//# sourceMappingURL=Questionnaire$QuestionnaireItemOperator.js.map