"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RelatedArtifact = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.RelatedArtifact.
 *
 * This actually imports the java class for further use.
 * The class {@link RelatedArtifactClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class RelatedArtifact extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.RelatedArtifact') {
}
exports.RelatedArtifact = RelatedArtifact;
exports.default = RelatedArtifact;
//# sourceMappingURL=RelatedArtifact.js.map