"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Signature = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.Signature.
 *
 * This actually imports the java class for further use.
 * The class {@link SignatureClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Signature extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.Signature') {
}
exports.Signature = Signature;
exports.default = Signature;
//# sourceMappingURL=Signature.js.map