"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StructureDefinition$StructureDefinitionMappingComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.StructureDefinition$StructureDefinitionMappingComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link StructureDefinition$StructureDefinitionMappingComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StructureDefinition$StructureDefinitionMappingComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.StructureDefinition$StructureDefinitionMappingComponent') {
}
exports.StructureDefinition$StructureDefinitionMappingComponent = StructureDefinition$StructureDefinitionMappingComponent;
exports.default = StructureDefinition$StructureDefinitionMappingComponent;
//# sourceMappingURL=StructureDefinition$StructureDefinitionMappingComponent.js.map