"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent') {
}
exports.TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent = TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent;
exports.default = TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent;
//# sourceMappingURL=TerminologyCapabilities$TerminologyCapabilitiesCodeSystemVersionFilterComponent.js.map