"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UuidType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.model.UuidType.
 *
 * This actually imports the java class for further use.
 * The class {@link UuidTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class UuidType extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.model.UuidType') {
}
exports.UuidType = UuidType;
exports.default = UuidType;
//# sourceMappingURL=UuidType.js.map