"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AddProfileTagEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.context.api.AddProfileTagEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link AddProfileTagEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class AddProfileTagEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.context.api.AddProfileTagEnum') {
}
exports.AddProfileTagEnum = AddProfileTagEnum;
exports.default = AddProfileTagEnum;
//# sourceMappingURL=AddProfileTagEnum.js.map