import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Enum as java_lang_Enum } from "./../../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { ResourceReferenceInfo as ca_uhn_fhir_util_ResourceReferenceInfo } from "./../../util/ResourceReferenceInfo";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../../java/util/Set";
import { Optional as java_util_Optional } from "./../../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link BundleInclusionRule} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BundleInclusionRuleClass extends JavaClass {
    /**
     * Original type: 'ca.uhn.fhir.context.api.BundleInclusionRule'
     */
    static readonly BASED_ON_INCLUDES: BundleInclusionRuleClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.api.BundleInclusionRule'
     */
    static readonly BASED_ON_RESOURCE_PRESENCE: BundleInclusionRuleClass | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.api.BundleInclusionRule[]'
     */
    static values(): Promise<(BundleInclusionRule | null)[] | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.api.BundleInclusionRule[]'
     */
    static valuesSync(): (BundleInclusionRule | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.api.BundleInclusionRule'
     */
    static valueOf(var0: string | null): Promise<BundleInclusionRule | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.api.BundleInclusionRule'
     */
    static valueOfSync(var0: string | null): BundleInclusionRule | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.util.ResourceReferenceInfo'
     * @param var1 original type: 'java.util.Set'
     * @return original return type: 'boolean'
     */
    shouldIncludeReferencedResource(var0: ca_uhn_fhir_util_ResourceReferenceInfo | null, var1: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.util.ResourceReferenceInfo'
     * @param var1 original type: 'java.util.Set'
     * @return original return type: 'boolean'
     */
    shouldIncludeReferencedResourceSync(var0: ca_uhn_fhir_util_ResourceReferenceInfo | null, var1: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const BundleInclusionRule_base: typeof BundleInclusionRuleClass;
/**
 * Class ca.uhn.fhir.context.api.BundleInclusionRule.
 *
 * This actually imports the java class for further use.
 * The class {@link BundleInclusionRuleClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BundleInclusionRule extends BundleInclusionRule_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default BundleInclusionRule;
//# sourceMappingURL=BundleInclusionRule.d.ts.map