"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Validator = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.mitre.inferno.Validator.
 *
 * This actually imports the java class for further use.
 * The class {@link ValidatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Validator extends (0, java_bridge_1.importClass)('org.mitre.inferno.Validator') {
}
exports.Validator = Validator;
exports.default = Validator;
//# sourceMappingURL=Validator.js.map