import { JavaClass, BasicOrJavaType } from "java-bridge";
import { SourceLocation as org_hl7_fhir_utilities_SourceLocation } from "./../../utilities/SourceLocation";
import { PrintStream as java_io_PrintStream } from "./../../../../../java/io/PrintStream";
import { PrintWriter as java_io_PrintWriter } from "./../../../../../java/io/PrintWriter";
import { Throwable as java_lang_Throwable } from "./../../../../../java/lang/Throwable";
import { StackTraceElement as java_lang_StackTraceElement } from "./../../../../../java/lang/StackTraceElement";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { FHIRLexer as org_hl7_fhir_r5_utils_FHIRLexer } from "./FHIRLexer";
/**
 * This class just defines types, you should import {@link FHIRLexer$FHIRLexerException} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FHIRLexer$FHIRLexerExceptionClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.utilities.SourceLocation'
     */
    getLocation(): Promise<org_hl7_fhir_utilities_SourceLocation | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.SourceLocation'
     */
    getLocationSync(): org_hl7_fhir_utilities_SourceLocation | null;
    /**
     * @return original return type: 'void'
     */
    printStackTrace(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    printStackTraceSync(): void;
    /**
     * @param var0 original type: 'java.io.PrintStream'
     * @return original return type: 'void'
     */
    printStackTrace(var0: java_io_PrintStream | null): Promise<void>;
    /**
     * @param var0 original type: 'java.io.PrintStream'
     * @return original return type: 'void'
     */
    printStackTraceSync(var0: java_io_PrintStream | null): void;
    /**
     * @param var0 original type: 'java.io.PrintWriter'
     * @return original return type: 'void'
     */
    printStackTrace(var0: java_io_PrintWriter | null): Promise<void>;
    /**
     * @param var0 original type: 'java.io.PrintWriter'
     * @return original return type: 'void'
     */
    printStackTraceSync(var0: java_io_PrintWriter | null): void;
    /**
     * @return original return type: 'java.lang.Throwable'
     */
    fillInStackTrace(): Promise<java_lang_Throwable | null>;
    /**
     * @return original return type: 'java.lang.Throwable'
     */
    fillInStackTraceSync(): java_lang_Throwable | null;
    /**
     * @return original return type: 'java.lang.Throwable'
     */
    getCause(): Promise<java_lang_Throwable | null>;
    /**
     * @return original return type: 'java.lang.Throwable'
     */
    getCauseSync(): java_lang_Throwable | null;
    /**
     * @param var0 original type: 'java.lang.Throwable'
     * @return original return type: 'java.lang.Throwable'
     */
    initCause(var0: java_lang_Throwable | null): Promise<java_lang_Throwable | null>;
    /**
     * @param var0 original type: 'java.lang.Throwable'
     * @return original return type: 'java.lang.Throwable'
     */
    initCauseSync(var0: java_lang_Throwable | null): java_lang_Throwable | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'java.lang.String'
     */
    getMessage(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getMessageSync(): string | null;
    /**
     * @return original return type: 'java.lang.Throwable[]'
     */
    getSuppressed(): Promise<(java_lang_Throwable | null)[] | null>;
    /**
     * @return original return type: 'java.lang.Throwable[]'
     */
    getSuppressedSync(): (java_lang_Throwable | null)[] | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getLocalizedMessage(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getLocalizedMessageSync(): string | null;
    /**
     * @return original return type: 'java.lang.StackTraceElement[]'
     */
    getStackTrace(): Promise<(java_lang_StackTraceElement | null)[] | null>;
    /**
     * @return original return type: 'java.lang.StackTraceElement[]'
     */
    getStackTraceSync(): (java_lang_StackTraceElement | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.StackTraceElement[]'
     * @return original return type: 'void'
     */
    setStackTrace(var0: (java_lang_StackTraceElement | null)[] | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.StackTraceElement[]'
     * @return original return type: 'void'
     */
    setStackTraceSync(var0: (java_lang_StackTraceElement | null)[] | null): void;
    /**
     * @param var0 original type: 'java.lang.Throwable'
     * @return original return type: 'void'
     */
    addSuppressed(var0: java_lang_Throwable | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Throwable'
     * @return original return type: 'void'
     */
    addSuppressedSync(var0: java_lang_Throwable | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.FHIRLexer'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.utilities.SourceLocation'
     * @return original return type: 'org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_utils_FHIRLexer | null, var1: string | null, var2: org_hl7_fhir_utilities_SourceLocation | null): Promise<FHIRLexer$FHIRLexerException>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.FHIRLexer'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.utilities.SourceLocation'
     */
    constructor(var0: org_hl7_fhir_r5_utils_FHIRLexer | null, var1: string | null, var2: org_hl7_fhir_utilities_SourceLocation | null);
}
declare const FHIRLexer$FHIRLexerException_base: typeof FHIRLexer$FHIRLexerExceptionClass;
/**
 * Class org.hl7.fhir.r5.utils.FHIRLexer$FHIRLexerException.
 *
 * This actually imports the java class for further use.
 * The class {@link FHIRLexer$FHIRLexerExceptionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FHIRLexer$FHIRLexerException extends FHIRLexer$FHIRLexerException_base {
}
export default FHIRLexer$FHIRLexerException;
//# sourceMappingURL=FHIRLexer$FHIRLexerException.d.ts.map