"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FHIRPathEngine$ElementDefinitionMatch = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.utils.FHIRPathEngine$ElementDefinitionMatch.
 *
 * This actually imports the java class for further use.
 * The class {@link FHIRPathEngine$ElementDefinitionMatchClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FHIRPathEngine$ElementDefinitionMatch extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.utils.FHIRPathEngine$ElementDefinitionMatch') {
}
exports.FHIRPathEngine$ElementDefinitionMatch = FHIRPathEngine$ElementDefinitionMatch;
exports.default = FHIRPathEngine$ElementDefinitionMatch;
//# sourceMappingURL=FHIRPathEngine$ElementDefinitionMatch.js.map