import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link FHIRPathEngine$IEvaluationContext$FunctionDetails} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FHIRPathEngine$IEvaluationContext$FunctionDetailsClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    getDescription(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDescriptionSync(): string | null;
    /**
     * @return original return type: 'int'
     */
    getMinParameters(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getMinParametersSync(): number;
    /**
     * @return original return type: 'int'
     */
    getMaxParameters(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    getMaxParametersSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     * @return original return type: 'org.hl7.fhir.r5.utils.FHIRPathEngine$IEvaluationContext$FunctionDetails'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number): Promise<FHIRPathEngine$IEvaluationContext$FunctionDetails>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'int'
     * @param var2 original type: 'int'
     */
    constructor(var0: string | null, var1: java_lang_Integer | number, var2: java_lang_Integer | number);
}
declare const FHIRPathEngine$IEvaluationContext$FunctionDetails_base: typeof FHIRPathEngine$IEvaluationContext$FunctionDetailsClass;
/**
 * Class org.hl7.fhir.r5.utils.FHIRPathEngine$IEvaluationContext$FunctionDetails.
 *
 * This actually imports the java class for further use.
 * The class {@link FHIRPathEngine$IEvaluationContext$FunctionDetailsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FHIRPathEngine$IEvaluationContext$FunctionDetails extends FHIRPathEngine$IEvaluationContext$FunctionDetails_base {
}
export default FHIRPathEngine$IEvaluationContext$FunctionDetails;
//# sourceMappingURL=FHIRPathEngine$IEvaluationContext$FunctionDetails.d.ts.map