"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FHIRPathEngine$IEvaluationContext$FunctionDetails = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.utils.FHIRPathEngine$IEvaluationContext$FunctionDetails.
 *
 * This actually imports the java class for further use.
 * The class {@link FHIRPathEngine$IEvaluationContext$FunctionDetailsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FHIRPathEngine$IEvaluationContext$FunctionDetails extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.utils.FHIRPathEngine$IEvaluationContext$FunctionDetails') {
}
exports.FHIRPathEngine$IEvaluationContext$FunctionDetails = FHIRPathEngine$IEvaluationContext$FunctionDetails;
exports.default = FHIRPathEngine$IEvaluationContext$FunctionDetails;
//# sourceMappingURL=FHIRPathEngine$IEvaluationContext$FunctionDetails.js.map