"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CDATASection = exports.createCDATASectionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link CDATASection} interface.
 * All required methods in {@link CDATASectionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createCDATASectionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.w3c.dom.CDATASection', methods, opts);
}
exports.createCDATASectionProxy = createCDATASectionProxy;
/**
 * Class org.w3c.dom.CDATASection.
 *
 * This actually imports the java class for further use.
 * The class {@link CDATASectionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CDATASection extends (0, java_bridge_1.importClass)('org.w3c.dom.CDATASection') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.CDATASection = CDATASection;
exports.default = CDATASection;
//# sourceMappingURL=CDATASection.js.map