"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Document = exports.createDocumentProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Document} interface.
 * All required methods in {@link DocumentInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDocumentProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.w3c.dom.Document', methods, opts);
}
exports.createDocumentProxy = createDocumentProxy;
/**
 * Class org.w3c.dom.Document.
 *
 * This actually imports the java class for further use.
 * The class {@link DocumentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Document extends (0, java_bridge_1.importClass)('org.w3c.dom.Document') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Document = Document;
exports.default = Document;
//# sourceMappingURL=Document.js.map