"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocumentFragment = exports.createDocumentFragmentProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link DocumentFragment} interface.
 * All required methods in {@link DocumentFragmentInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createDocumentFragmentProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.w3c.dom.DocumentFragment', methods, opts);
}
exports.createDocumentFragmentProxy = createDocumentFragmentProxy;
/**
 * Class org.w3c.dom.DocumentFragment.
 *
 * This actually imports the java class for further use.
 * The class {@link DocumentFragmentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DocumentFragment extends (0, java_bridge_1.importClass)('org.w3c.dom.DocumentFragment') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.DocumentFragment = DocumentFragment;
exports.default = DocumentFragment;
//# sourceMappingURL=DocumentFragment.js.map