"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NodeList = exports.createNodeListProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link NodeList} interface.
 * All required methods in {@link NodeListInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createNodeListProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.w3c.dom.NodeList', methods, opts);
}
exports.createNodeListProxy = createNodeListProxy;
/**
 * Class org.w3c.dom.NodeList.
 *
 * This actually imports the java class for further use.
 * The class {@link NodeListClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class NodeList extends (0, java_bridge_1.importClass)('org.w3c.dom.NodeList') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.NodeList = NodeList;
exports.default = NodeList;
//# sourceMappingURL=NodeList.js.map