"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TypeInfo = exports.createTypeInfoProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link TypeInfo} interface.
 * All required methods in {@link TypeInfoInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createTypeInfoProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.w3c.dom.TypeInfo', methods, opts);
}
exports.createTypeInfoProxy = createTypeInfoProxy;
/**
 * Class org.w3c.dom.TypeInfo.
 *
 * This actually imports the java class for further use.
 * The class {@link TypeInfoClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TypeInfo extends (0, java_bridge_1.importClass)('org.w3c.dom.TypeInfo') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TypeInfo = TypeInfo;
exports.default = TypeInfo;
//# sourceMappingURL=TypeInfo.js.map