import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IBase as org_hl7_fhir_instance_model_api_IBase, IBaseInterface as org_hl7_fhir_instance_model_api_IBaseInterface } from "./../../../../org/hl7/fhir/instance/model/api/IBase";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link BaseRuntimeChildDefinition$IMutator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BaseRuntimeChildDefinition$IMutatorClass extends JavaClass {
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    remove(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    removeSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    setValueSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    addValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    addValueSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createBaseRuntimeChildDefinition$IMutatorProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface BaseRuntimeChildDefinition$IMutatorInterface {
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    remove?(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @return original return type: 'void'
     */
    addValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null): void;
}
/**
 * Create a proxy for the {@link BaseRuntimeChildDefinition$IMutator} interface.
 * All required methods in {@link BaseRuntimeChildDefinition$IMutatorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createBaseRuntimeChildDefinition$IMutatorProxy(methods: BaseRuntimeChildDefinition$IMutatorInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<BaseRuntimeChildDefinition$IMutatorInterface>;
declare const BaseRuntimeChildDefinition$IMutator_base: typeof BaseRuntimeChildDefinition$IMutatorClass;
/**
 * Class ca.uhn.fhir.context.BaseRuntimeChildDefinition$IMutator.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseRuntimeChildDefinition$IMutatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BaseRuntimeChildDefinition$IMutator extends BaseRuntimeChildDefinition$IMutator_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default BaseRuntimeChildDefinition$IMutator;
//# sourceMappingURL=BaseRuntimeChildDefinition$IMutator.d.ts.map