"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FhirContext = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.context.FhirContext.
 *
 * This actually imports the java class for further use.
 * The class {@link FhirContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FhirContext extends (0, java_bridge_1.importClass)('ca.uhn.fhir.context.FhirContext') {
}
exports.FhirContext = FhirContext;
exports.default = FhirContext;
//# sourceMappingURL=FhirContext.js.map