import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Enum as java_lang_Enum } from "./../../../../java/lang/Enum";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { FhirContext as ca_uhn_fhir_context_FhirContext } from "./FhirContext";
import { IFhirVersion as ca_uhn_fhir_model_api_IFhirVersion } from "./../model/api/IFhirVersion";
import { Optional as java_util_Optional } from "./../../../../java/util/Optional";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link FhirVersionEnum} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FhirVersionEnumClass extends JavaClass {
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly DSTU2: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly DSTU2_HL7ORG: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly DSTU2_1: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly DSTU3: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly R4: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly R4B: FhirVersionEnumClass | null;
    /**
     * Original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static readonly R5: FhirVersionEnumClass | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum[]'
     */
    static values(): Promise<(FhirVersionEnum | null)[] | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum[]'
     */
    static valuesSync(): (FhirVersionEnum | null)[] | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static valueOf(var0: string | null): Promise<FhirVersionEnum | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static valueOfSync(var0: string | null): FhirVersionEnum | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOf(var0: java_lang_Class | null, var1: string | null): Promise<java_lang_Enum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Enum'
     */
    static valueOfSync(var0: java_lang_Class | null, var1: string | null): java_lang_Enum | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirContext'
     */
    newContext(): Promise<ca_uhn_fhir_context_FhirContext | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirContext'
     */
    newContextSync(): ca_uhn_fhir_context_FhirContext | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getFhirVersionString(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getFhirVersionStringSync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isPresentOnClasspath(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isPresentOnClasspathSync(): boolean;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.IFhirVersion'
     */
    getVersionImplementation(): Promise<ca_uhn_fhir_model_api_IFhirVersion | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.IFhirVersion'
     */
    getVersionImplementationSync(): ca_uhn_fhir_model_api_IFhirVersion | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static determineVersionForType(var0: java_lang_Class | null): Promise<FhirVersionEnum | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static determineVersionForTypeSync(var0: java_lang_Class | null): FhirVersionEnum | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isEquivalentTo(var0: FhirVersionEnumClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isEquivalentToSync(var0: FhirVersionEnumClass | null): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isOlderThan(var0: FhirVersionEnumClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isOlderThanSync(var0: FhirVersionEnumClass | null): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isNewerThan(var0: FhirVersionEnumClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isNewerThanSync(var0: FhirVersionEnumClass | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isRi(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isRiSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static forVersionString(var0: string | null): Promise<FhirVersionEnum | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.FhirVersionEnum'
     */
    static forVersionStringSync(var0: string | null): FhirVersionEnum | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isEqualOrNewerThan(var0: FhirVersionEnumClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirVersionEnum'
     * @return original return type: 'boolean'
     */
    isEqualOrNewerThanSync(var0: FhirVersionEnumClass | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    name(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareTo(var0: BasicOrJavaType | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'int'
     */
    compareToSync(var0: BasicOrJavaType | null): number;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareTo(var0: java_lang_Enum | null): Promise<number>;
    /**
     * @param var0 original type: 'java.lang.Enum'
     * @return original return type: 'int'
     */
    compareToSync(var0: java_lang_Enum | null): number;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstable(): Promise<java_util_Optional | null>;
    /**
     * @return original return type: 'java.util.Optional'
     */
    describeConstableSync(): java_util_Optional | null;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClass(): Promise<java_lang_Class | null>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getDeclaringClassSync(): java_lang_Class | null;
    /**
     * @return original return type: 'int'
     */
    ordinal(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    ordinalSync(): number;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const FhirVersionEnum_base: typeof FhirVersionEnumClass;
/**
 * Class ca.uhn.fhir.context.FhirVersionEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link FhirVersionEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FhirVersionEnum extends FhirVersionEnum_base {
}
export default FhirVersionEnum;
//# sourceMappingURL=FhirVersionEnum.d.ts.map