import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IIdType as org_hl7_fhir_instance_model_api_IIdType, IIdTypeInterface as org_hl7_fhir_instance_model_api_IIdTypeInterface } from "./../../../../org/hl7/fhir/instance/model/api/IIdType";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../java/util/List";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../java/util/Set";
import { ComboSearchParamType as ca_uhn_fhir_context_ComboSearchParamType } from "./ComboSearchParamType";
import { IPhoneticEncoder as ca_uhn_fhir_context_phonetic_IPhoneticEncoder, IPhoneticEncoderInterface as ca_uhn_fhir_context_phonetic_IPhoneticEncoderInterface } from "./phonetic/IPhoneticEncoder";
import { IBaseExtension as org_hl7_fhir_instance_model_api_IBaseExtension, IBaseExtensionInterface as org_hl7_fhir_instance_model_api_IBaseExtensionInterface } from "./../../../../org/hl7/fhir/instance/model/api/IBaseExtension";
import { RuntimeSearchParam$RuntimeSearchParamStatusEnum as ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum } from "./RuntimeSearchParam$RuntimeSearchParamStatusEnum";
import { RestSearchParameterTypeEnum as ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum } from "./../rest/api/RestSearchParameterTypeEnum";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { Collection as java_util_Collection, CollectionInterface as java_util_CollectionInterface } from "./../../../../java/util/Collection";
/**
 * This class just defines types, you should import {@link RuntimeSearchParam} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RuntimeSearchParamClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    getName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    encode(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    encodeSync(var0: string | null): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IIdType'
     */
    getId(): Promise<org_hl7_fhir_instance_model_api_IIdType | null>;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IIdType'
     */
    getIdSync(): org_hl7_fhir_instance_model_api_IIdType | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPath(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPathSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getExtensions(var0: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getExtensionsSync(var0: string | null): java_util_List | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getBase(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getBaseSync(): java_util_Set | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.ComboSearchParamType'
     */
    getComboSearchParamType(): Promise<ca_uhn_fhir_context_ComboSearchParamType | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.ComboSearchParamType'
     */
    getComboSearchParamTypeSync(): ca_uhn_fhir_context_ComboSearchParamType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getPathsSplitForResourceType(var0: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getPathsSplitForResourceTypeSync(var0: string | null): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getPathsSplit(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getPathsSplitSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getProvidesMembershipInCompartments(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getProvidesMembershipInCompartmentsSync(): java_util_Set | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getComponents(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getComponentsSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getTargets(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getTargetsSync(): java_util_Set | null;
    /**
     * @return original return type: 'boolean'
     */
    hasTargets(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasTargetsSync(): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.phonetic.IPhoneticEncoder'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    setPhoneticEncoder(var0: ca_uhn_fhir_context_phonetic_IPhoneticEncoder | JavaInterfaceProxy<ca_uhn_fhir_context_phonetic_IPhoneticEncoderInterface> | null): Promise<RuntimeSearchParam | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.phonetic.IPhoneticEncoder'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    setPhoneticEncoderSync(var0: ca_uhn_fhir_context_phonetic_IPhoneticEncoder | JavaInterfaceProxy<ca_uhn_fhir_context_phonetic_IPhoneticEncoderInterface> | null): RuntimeSearchParam | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseExtension'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    addExtension(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseExtension | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseExtensionInterface> | null): Promise<RuntimeSearchParam | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseExtension'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    addExtensionSync(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseExtension | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseExtensionInterface> | null): RuntimeSearchParam | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     */
    getStatus(): Promise<ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     */
    getStatusSync(): ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDescription(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDescriptionSync(): string | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    getParamType(): Promise<ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     */
    getParamTypeSync(): ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUri(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUriSync(): string | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     * @param var6 original type: 'java.util.Set'
     * @param var7 original type: 'java.util.Set'
     * @param var8 original type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     * @param var9 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    static newInstanceAsync(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var1: string | null, var2: string | null, var3: string | null, var4: string | null, var5: ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null, var6: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var7: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var8: ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null, var9: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<RuntimeSearchParam>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     * @param var6 original type: 'java.util.Set'
     * @param var7 original type: 'java.util.Set'
     * @param var8 original type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     * @param var9 original type: 'ca.uhn.fhir.context.ComboSearchParamType'
     * @param var10 original type: 'java.util.List'
     * @param var11 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    static newInstanceAsync(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var1: string | null, var2: string | null, var3: string | null, var4: string | null, var5: ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null, var6: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var7: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var8: ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null, var9: ca_uhn_fhir_context_ComboSearchParamType | null, var10: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var11: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<RuntimeSearchParam>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     * @return original return type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    static newInstanceAsync(var0: RuntimeSearchParamClass | null): Promise<RuntimeSearchParam>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     * @param var6 original type: 'java.util.Set'
     * @param var7 original type: 'java.util.Set'
     * @param var8 original type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     * @param var9 original type: 'java.util.Collection'
     */
    constructor(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var1: string | null, var2: string | null, var3: string | null, var4: string | null, var5: ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null, var6: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var7: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var8: ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null, var9: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null);
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'ca.uhn.fhir.rest.api.RestSearchParameterTypeEnum'
     * @param var6 original type: 'java.util.Set'
     * @param var7 original type: 'java.util.Set'
     * @param var8 original type: 'ca.uhn.fhir.context.RuntimeSearchParam$RuntimeSearchParamStatusEnum'
     * @param var9 original type: 'ca.uhn.fhir.context.ComboSearchParamType'
     * @param var10 original type: 'java.util.List'
     * @param var11 original type: 'java.util.Collection'
     */
    constructor(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var1: string | null, var2: string | null, var3: string | null, var4: string | null, var5: ca_uhn_fhir_rest_api_RestSearchParameterTypeEnum | null, var6: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var7: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var8: ca_uhn_fhir_context_RuntimeSearchParam$RuntimeSearchParamStatusEnum | null, var9: ca_uhn_fhir_context_ComboSearchParamType | null, var10: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var11: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null);
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.RuntimeSearchParam'
     */
    constructor(var0: RuntimeSearchParamClass | null);
}
declare const RuntimeSearchParam_base: typeof RuntimeSearchParamClass;
/**
 * Class ca.uhn.fhir.context.RuntimeSearchParam.
 *
 * This actually imports the java class for further use.
 * The class {@link RuntimeSearchParamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class RuntimeSearchParam extends RuntimeSearchParam_base {
}
export default RuntimeSearchParam;
//# sourceMappingURL=RuntimeSearchParam.d.ts.map