"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DefaultConstructorMarker = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class kotlin.jvm.internal.DefaultConstructorMarker.
 *
 * This actually imports the java class for further use.
 * The class {@link DefaultConstructorMarkerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DefaultConstructorMarker extends (0, java_bridge_1.importClass)('kotlin.jvm.internal.DefaultConstructorMarker') {
}
exports.DefaultConstructorMarker = DefaultConstructorMarker;
exports.default = DefaultConstructorMarker;
//# sourceMappingURL=DefaultConstructorMarker.js.map