import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IBaseResource as org_hl7_fhir_instance_model_api_IBaseResource, IBaseResourceInterface as org_hl7_fhir_instance_model_api_IBaseResourceInterface } from "./../../../../org/hl7/fhir/instance/model/api/IBaseResource";
import { Map as java_util_Map } from "./../../../../java/util/Map";
import { BaseRuntimeChildDefinition as ca_uhn_fhir_context_BaseRuntimeChildDefinition } from "./../context/BaseRuntimeChildDefinition";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { IModelVisitor as ca_uhn_fhir_util_IModelVisitor, IModelVisitorInterface as ca_uhn_fhir_util_IModelVisitorInterface } from "./IModelVisitor";
import { IBase as org_hl7_fhir_instance_model_api_IBase, IBaseInterface as org_hl7_fhir_instance_model_api_IBaseInterface } from "./../../../../org/hl7/fhir/instance/model/api/IBase";
import { IModelVisitor2 as ca_uhn_fhir_util_IModelVisitor2, IModelVisitor2Interface as ca_uhn_fhir_util_IModelVisitor2Interface } from "./IModelVisitor2";
import { List as java_util_List } from "./../../../../java/util/List";
import { IIdType as org_hl7_fhir_instance_model_api_IIdType, IIdTypeInterface as org_hl7_fhir_instance_model_api_IIdTypeInterface } from "./../../../../org/hl7/fhir/instance/model/api/IIdType";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../java/util/Set";
import { Optional as java_util_Optional } from "./../../../../java/util/Optional";
import { Collection as java_util_Collection, CollectionInterface as java_util_CollectionInterface } from "./../../../../java/util/Collection";
import { Boolean as java_lang_Boolean } from "./../../../../java/lang/Boolean";
import { FhirTerser$ContainedResources as ca_uhn_fhir_util_FhirTerser$ContainedResources } from "./FhirTerser$ContainedResources";
import { FhirTerser$OptionsEnum as ca_uhn_fhir_util_FhirTerser$OptionsEnum } from "./FhirTerser$OptionsEnum";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { FhirContext as ca_uhn_fhir_context_FhirContext } from "./../context/FhirContext";
/**
 * This class just defines types, you should import {@link FhirTerser} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FhirTerserClass extends JavaClass {
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    clone(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    cloneSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'void'
     */
    clear(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'void'
     */
    clearSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): void;
    /**
     * @return original return type: 'java.util.Map'
     */
    newMap(): Promise<java_util_Map | null>;
    /**
     * @return original return type: 'java.util.Map'
     */
    newMapSync(): java_util_Map | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.BaseRuntimeChildDefinition'
     */
    getDefinition(var0: java_lang_Class | null, var1: string | null): Promise<ca_uhn_fhir_context_BaseRuntimeChildDefinition | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.BaseRuntimeChildDefinition'
     */
    getDefinitionSync(var0: java_lang_Class | null, var1: string | null): ca_uhn_fhir_context_BaseRuntimeChildDefinition | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'ca.uhn.fhir.util.IModelVisitor'
     * @return original return type: 'void'
     */
    visit(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: ca_uhn_fhir_util_IModelVisitor | JavaInterfaceProxy<ca_uhn_fhir_util_IModelVisitorInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'ca.uhn.fhir.util.IModelVisitor'
     * @return original return type: 'void'
     */
    visitSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: ca_uhn_fhir_util_IModelVisitor | JavaInterfaceProxy<ca_uhn_fhir_util_IModelVisitorInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'ca.uhn.fhir.util.IModelVisitor2'
     * @return original return type: 'void'
     */
    visit(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: ca_uhn_fhir_util_IModelVisitor2 | JavaInterfaceProxy<ca_uhn_fhir_util_IModelVisitor2Interface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'ca.uhn.fhir.util.IModelVisitor2'
     * @return original return type: 'void'
     */
    visitSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: ca_uhn_fhir_util_IModelVisitor2 | JavaInterfaceProxy<ca_uhn_fhir_util_IModelVisitor2Interface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    setElement(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: string | null): Promise<org_hl7_fhir_instance_model_api_IBase | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    setElementSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: string | null): org_hl7_fhir_instance_model_api_IBase | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getAllPopulatedChildElementsOfType(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_lang_Class | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getAllPopulatedChildElementsOfTypeSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_lang_Class | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    getSinglePrimitiveValueOrNull(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    getSinglePrimitiveValueOrNullSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    getSingleValueOrNull(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): Promise<org_hl7_fhir_instance_model_api_IBase | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    getSingleValueOrNullSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): org_hl7_fhir_instance_model_api_IBase | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getSingleValueOrNull(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getSingleValueOrNullSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var3 original type: 'java.util.Set'
     * @return original return type: 'boolean'
     */
    isSourceInCompartmentForTarget(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var3: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @param var3 original type: 'java.util.Set'
     * @return original return type: 'boolean'
     */
    isSourceInCompartmentForTargetSync(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null, var3: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'boolean'
     */
    isSourceInCompartmentForTarget(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'boolean'
     */
    isSourceInCompartmentForTargetSync(var0: string | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'java.util.List'
     */
    getAllResourceReferences(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'java.util.List'
     */
    getAllResourceReferencesSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.Optional'
     */
    getSinglePrimitiveValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): Promise<java_util_Optional | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.Optional'
     */
    getSinglePrimitiveValueSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): java_util_Optional | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.Collection'
     */
    getAllEmbeddedResources(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_lang_Boolean | boolean): Promise<java_util_Collection | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.Collection'
     */
    getAllEmbeddedResourcesSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: java_lang_Boolean | boolean): java_util_Collection | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'ca.uhn.fhir.util.FhirTerser$OptionsEnum[]'
     * @return original return type: 'ca.uhn.fhir.util.FhirTerser$ContainedResources'
     */
    containResources(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: (ca_uhn_fhir_util_FhirTerser$OptionsEnum | null)[] | null): Promise<ca_uhn_fhir_util_FhirTerser$ContainedResources | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var1 original type: 'ca.uhn.fhir.util.FhirTerser$OptionsEnum[]'
     * @return original return type: 'ca.uhn.fhir.util.FhirTerser$ContainedResources'
     */
    containResourcesSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var1: (ca_uhn_fhir_util_FhirTerser$OptionsEnum | null)[] | null): ca_uhn_fhir_util_FhirTerser$ContainedResources | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.util.Collection'
     * @return original return type: 'void'
     */
    addElements(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.util.Collection'
     * @return original return type: 'void'
     */
    addElementsSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var2 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    cloneInto(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var2: java_lang_Boolean | boolean): Promise<org_hl7_fhir_instance_model_api_IBase | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var2 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    cloneIntoSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var2: java_lang_Boolean | boolean): org_hl7_fhir_instance_model_api_IBase | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'java.util.Optional'
     */
    getSingleValue(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): Promise<java_util_Optional | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'java.util.Optional'
     */
    getSingleValueSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): java_util_Optional | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    addElement(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): Promise<org_hl7_fhir_instance_model_api_IBase | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    addElementSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): org_hl7_fhir_instance_model_api_IBase | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    addElement(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: string | null): Promise<org_hl7_fhir_instance_model_api_IBase | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBase'
     */
    addElementSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: string | null): org_hl7_fhir_instance_model_api_IBase | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Boolean | boolean, var3: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Boolean | boolean, var3: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @param var3 original type: 'boolean'
     * @param var4 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null, var3: java_lang_Boolean | boolean, var4: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @param var3 original type: 'boolean'
     * @param var4 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null, var3: java_lang_Boolean | boolean, var4: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null, var3: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null, var3: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getValues(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBase'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getValuesSync(var0: org_hl7_fhir_instance_model_api_IBase | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseInterface> | null, var1: string | null, var2: java_lang_Class | null): java_util_List | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirContext'
     * @return original return type: 'ca.uhn.fhir.util.FhirTerser'
     */
    static newInstanceAsync(var0: ca_uhn_fhir_context_FhirContext | null): Promise<FhirTerser>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.FhirContext'
     */
    constructor(var0: ca_uhn_fhir_context_FhirContext | null);
}
declare const FhirTerser_base: typeof FhirTerserClass;
/**
 * Class ca.uhn.fhir.util.FhirTerser.
 *
 * This actually imports the java class for further use.
 * The class {@link FhirTerserClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class FhirTerser extends FhirTerser_base {
}
export default FhirTerser;
//# sourceMappingURL=FhirTerser.d.ts.map