"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IModelVisitor = exports.createIModelVisitorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IModelVisitor} interface.
 * All required methods in {@link IModelVisitorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIModelVisitorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.util.IModelVisitor', methods, opts);
}
exports.createIModelVisitorProxy = createIModelVisitorProxy;
/**
 * Class ca.uhn.fhir.util.IModelVisitor.
 *
 * This actually imports the java class for further use.
 * The class {@link IModelVisitorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IModelVisitor extends (0, java_bridge_1.importClass)('ca.uhn.fhir.util.IModelVisitor') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IModelVisitor = IModelVisitor;
exports.default = IModelVisitor;
//# sourceMappingURL=IModelVisitor.js.map