"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StopWatch = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.util.StopWatch.
 *
 * This actually imports the java class for further use.
 * The class {@link StopWatchClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StopWatch extends (0, java_bridge_1.importClass)('ca.uhn.fhir.util.StopWatch') {
}
exports.StopWatch = StopWatch;
exports.default = StopWatch;
//# sourceMappingURL=StopWatch.js.map