import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { ValidationLevel as org_hl7_fhir_validation_cli_utils_ValidationLevel } from "./cli/utils/ValidationLevel";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../java/util/List";
import { ValidationMessage$Source as org_hl7_fhir_utilities_validation_ValidationMessage$Source } from "./../utilities/validation/ValidationMessage$Source";
import { ValidationMessage$IssueType as org_hl7_fhir_utilities_validation_ValidationMessage$IssueType } from "./../utilities/validation/ValidationMessage$IssueType";
import { Boolean as java_lang_Boolean } from "./../../../../java/lang/Boolean";
import { ValidationMessage as org_hl7_fhir_utilities_validation_ValidationMessage } from "./../utilities/validation/ValidationMessage";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./../r5/model/StructureDefinition";
import { XVerExtensionManager$XVerExtensionStatus as org_hl7_fhir_r5_utils_XVerExtensionManager$XVerExtensionStatus } from "./../r5/utils/XVerExtensionManager$XVerExtensionStatus";
import { Element as org_hl7_fhir_r5_elementmodel_Element } from "./../r5/elementmodel/Element";
import { Map as java_util_Map } from "./../../../../java/util/Map";
import { Resource as org_hl7_fhir_r5_model_Resource } from "./../r5/model/Resource";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { IWorkerContext as org_hl7_fhir_r5_context_IWorkerContext, IWorkerContextInterface as org_hl7_fhir_r5_context_IWorkerContextInterface } from "./../r5/context/IWorkerContext";
import { XVerExtensionManager as org_hl7_fhir_r5_utils_XVerExtensionManager } from "./../r5/utils/XVerExtensionManager";
/**
 * This class just defines types, you should import {@link BaseValidator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BaseValidatorClass extends JavaClass {
    /**
     * Original type: 'java.lang.String'
     */
    static readonly NO_RULE_DATE: string | null;
    /**
     * @return original return type: 'boolean'
     */
    isDebug(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isDebugSync(): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.validation.cli.utils.ValidationLevel'
     */
    getLevel(): Promise<org_hl7_fhir_validation_cli_utils_ValidationLevel | null>;
    /**
     * @return original return type: 'org.hl7.fhir.validation.cli.utils.ValidationLevel'
     */
    getLevelSync(): org_hl7_fhir_validation_cli_utils_ValidationLevel | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.validation.cli.utils.ValidationLevel'
     * @return original return type: 'void'
     */
    setLevel(var0: org_hl7_fhir_validation_cli_utils_ValidationLevel | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.validation.cli.utils.ValidationLevel'
     * @return original return type: 'void'
     */
    setLevelSync(var0: org_hl7_fhir_validation_cli_utils_ValidationLevel | null): void;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage$Source'
     * @param var3 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage$IssueType'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'boolean'
     * @param var6 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    rule(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_utilities_validation_ValidationMessage$Source | null, var3: org_hl7_fhir_utilities_validation_ValidationMessage$IssueType | null, var4: string | null, var5: java_lang_Boolean | boolean, var6: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage$Source'
     * @param var3 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage$IssueType'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'boolean'
     * @param var6 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    ruleSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_utilities_validation_ValidationMessage$Source | null, var3: org_hl7_fhir_utilities_validation_ValidationMessage$IssueType | null, var4: string | null, var5: java_lang_Boolean | boolean, var6: string | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage'
     * @return original return type: 'boolean'
     */
    checkMsgId(var0: string | null, var1: org_hl7_fhir_utilities_validation_ValidationMessage | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.utilities.validation.ValidationMessage'
     * @return original return type: 'boolean'
     */
    checkMsgIdSync(var0: string | null, var1: org_hl7_fhir_utilities_validation_ValidationMessage | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    xverDefn(var0: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    xverDefnSync(var0: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.XVerExtensionManager$XVerExtensionStatus'
     */
    xverStatus(var0: string | null): Promise<org_hl7_fhir_r5_utils_XVerExtensionManager$XVerExtensionStatus | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.XVerExtensionManager$XVerExtensionStatus'
     */
    xverStatusSync(var0: string | null): org_hl7_fhir_r5_utils_XVerExtensionManager$XVerExtensionStatus | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getXverExt(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getXverExtSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getXverExt(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_r5_elementmodel_Element | null, var3: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getXverExtSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_r5_elementmodel_Element | null, var3: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    xverVersion(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    xverVersionSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    xverElementId(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    xverElementIdSync(var0: string | null): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isXverUrl(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isXverUrlSync(var0: string | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isAllowExamples(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAllowExamplesSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.validation.BaseValidator'
     */
    setForPublication(var0: java_lang_Boolean | boolean): Promise<BaseValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.validation.BaseValidator'
     */
    setForPublicationSync(var0: java_lang_Boolean | boolean): BaseValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isForPublication(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isForPublicationSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setDebug(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setDebugSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAllowExamples(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAllowExamplesSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'java.util.Map'
     */
    getValidationControl(): Promise<java_util_Map | null>;
    /**
     * @return original return type: 'java.util.Map'
     */
    getValidationControlSync(): java_util_Map | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.Class'
     * @return original return type: 'org.hl7.fhir.r5.model.Resource'
     */
    loadContainedResource(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_r5_elementmodel_Element | null, var3: string | null, var4: java_lang_Class | null): Promise<org_hl7_fhir_r5_model_Resource | null>;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.Class'
     * @return original return type: 'org.hl7.fhir.r5.model.Resource'
     */
    loadContainedResourceSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: string | null, var2: org_hl7_fhir_r5_elementmodel_Element | null, var3: string | null, var4: java_lang_Class | null): org_hl7_fhir_r5_model_Resource | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     * @param var2 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.validation.BaseValidator'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_utils_XVerExtensionManager | null, var2: java_lang_Boolean | boolean): Promise<BaseValidator>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     * @param var2 original type: 'boolean'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_utils_XVerExtensionManager | null, var2: java_lang_Boolean | boolean);
}
declare const BaseValidator_base: typeof BaseValidatorClass;
/**
 * Class org.hl7.fhir.validation.BaseValidator.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseValidatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BaseValidator extends BaseValidator_base {
}
export default BaseValidator;
//# sourceMappingURL=BaseValidator.d.ts.map