/// <reference types="node" />
import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Manager$FhirFormat as org_hl7_fhir_r5_elementmodel_Manager$FhirFormat } from "./../r5/elementmodel/Manager$FhirFormat";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link Content} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ContentClass extends JavaClass {
    /**
     * @return original return type: 'byte[]'
     */
    getFocus(): Promise<Buffer | null>;
    /**
     * @return original return type: 'byte[]'
     */
    getFocusSync(): Buffer | null;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    setFocus(var0: Buffer | null): Promise<void>;
    /**
     * @param var0 original type: 'byte[]'
     * @return original return type: 'void'
     */
    setFocusSync(var0: Buffer | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     */
    getCntType(): Promise<org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     */
    getCntTypeSync(): org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @return original return type: 'void'
     */
    setCntType(var0: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @return original return type: 'void'
     */
    setCntTypeSync(var0: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getExampleFileName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getExampleFileNameSync(): string | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'org.hl7.fhir.validation.Content'
     */
    static newInstanceAsync(): Promise<Content>;
    constructor();
}
declare const Content_base: typeof ContentClass;
/**
 * Class org.hl7.fhir.validation.Content.
 *
 * This actually imports the java class for further use.
 * The class {@link ContentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Content extends Content_base {
}
export default Content;
//# sourceMappingURL=Content.d.ts.map