"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidationEngine = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.validation.ValidationEngine.
 *
 * This actually imports the java class for further use.
 * The class {@link ValidationEngineClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValidationEngine extends (0, java_bridge_1.importClass)('org.hl7.fhir.validation.ValidationEngine') {
}
exports.ValidationEngine = ValidationEngine;
exports.default = ValidationEngine;
//# sourceMappingURL=ValidationEngine.js.map