"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidationEngine$IValidationEngineLoader = exports.createValidationEngine$IValidationEngineLoaderProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ValidationEngine$IValidationEngineLoader} interface.
 * All required methods in {@link ValidationEngine$IValidationEngineLoaderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createValidationEngine$IValidationEngineLoaderProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.validation.ValidationEngine$IValidationEngineLoader', methods, opts);
}
exports.createValidationEngine$IValidationEngineLoaderProxy = createValidationEngine$IValidationEngineLoaderProxy;
/**
 * Class org.hl7.fhir.validation.ValidationEngine$IValidationEngineLoader.
 *
 * This actually imports the java class for further use.
 * The class {@link ValidationEngine$IValidationEngineLoaderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValidationEngine$IValidationEngineLoader extends (0, java_bridge_1.importClass)('org.hl7.fhir.validation.ValidationEngine$IValidationEngineLoader') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ValidationEngine$IValidationEngineLoader = ValidationEngine$IValidationEngineLoader;
exports.default = ValidationEngine$IValidationEngineLoader;
//# sourceMappingURL=ValidationEngine$IValidationEngineLoader.js.map