"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CompositeClientParam = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.rest.gclient.CompositeClientParam.
 *
 * This actually imports the java class for further use.
 * The class {@link CompositeClientParamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class CompositeClientParam extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.CompositeClientParam') {
}
exports.CompositeClientParam = CompositeClientParam;
exports.default = CompositeClientParam;
//# sourceMappingURL=CompositeClientParam.js.map