"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICreate = exports.createICreateProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ICreate} interface.
 * All required methods in {@link ICreateInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createICreateProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ICreate', methods, opts);
}
exports.createICreateProxy = createICreateProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ICreate.
 *
 * This actually imports the java class for further use.
 * The class {@link ICreateClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ICreate extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ICreate') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ICreate = ICreate;
exports.default = ICreate;
//# sourceMappingURL=ICreate.js.map