"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICreateTyped = exports.createICreateTypedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ICreateTyped} interface.
 * All required methods in {@link ICreateTypedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createICreateTypedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ICreateTyped', methods, opts);
}
exports.createICreateTypedProxy = createICreateTypedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ICreateTyped.
 *
 * This actually imports the java class for further use.
 * The class {@link ICreateTypedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ICreateTyped extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ICreateTyped') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ICreateTyped = ICreateTyped;
exports.default = ICreateTyped;
//# sourceMappingURL=ICreateTyped.js.map