"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICreateWithQuery = exports.createICreateWithQueryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ICreateWithQuery} interface.
 * All required methods in {@link ICreateWithQueryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createICreateWithQueryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ICreateWithQuery', methods, opts);
}
exports.createICreateWithQueryProxy = createICreateWithQueryProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ICreateWithQuery.
 *
 * This actually imports the java class for further use.
 * The class {@link ICreateWithQueryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ICreateWithQuery extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ICreateWithQuery') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ICreateWithQuery = ICreateWithQuery;
exports.default = ICreateWithQuery;
//# sourceMappingURL=ICreateWithQuery.js.map