"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICriterion = exports.createICriterionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ICriterion} interface.
 * All required methods in {@link ICriterionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createICriterionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ICriterion', methods, opts);
}
exports.createICriterionProxy = createICriterionProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ICriterion.
 *
 * This actually imports the java class for further use.
 * The class {@link ICriterionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ICriterion extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ICriterion') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ICriterion = ICriterion;
exports.default = ICriterion;
//# sourceMappingURL=ICriterion.js.map