"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDeleteTyped = exports.createIDeleteTypedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IDeleteTyped} interface.
 * All required methods in {@link IDeleteTypedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIDeleteTypedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IDeleteTyped', methods, opts);
}
exports.createIDeleteTypedProxy = createIDeleteTypedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IDeleteTyped.
 *
 * This actually imports the java class for further use.
 * The class {@link IDeleteTypedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IDeleteTyped extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IDeleteTyped') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IDeleteTyped = IDeleteTyped;
exports.default = IDeleteTyped;
//# sourceMappingURL=IDeleteTyped.js.map