import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IDeleteTyped as ca_uhn_fhir_rest_gclient_IDeleteTyped } from "./IDeleteTyped";
import { IBaseResource as org_hl7_fhir_instance_model_api_IBaseResource, IBaseResourceInterface as org_hl7_fhir_instance_model_api_IBaseResourceInterface } from "./../../../../../org/hl7/fhir/instance/model/api/IBaseResource";
import { IDeleteWithQuery as ca_uhn_fhir_rest_gclient_IDeleteWithQuery } from "./IDeleteWithQuery";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { IIdType as org_hl7_fhir_instance_model_api_IIdType, IIdTypeInterface as org_hl7_fhir_instance_model_api_IIdTypeInterface } from "./../../../../../org/hl7/fhir/instance/model/api/IIdType";
/**
 * This class just defines types, you should import {@link IDelete} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IDeleteClass extends JavaClass {
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resource(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteTyped | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceSync(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceConditionalByUrl(var0: string | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteTyped | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceConditionalByUrlSync(var0: string | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByType(var0: java_lang_Class | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByTypeSync(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByType(var0: string | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByTypeSync(var0: string | null): ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceById(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteTyped | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceByIdSync(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceById(var0: string | null, var1: string | null): Promise<ca_uhn_fhir_rest_gclient_IDeleteTyped | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceByIdSync(var0: string | null, var1: string | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIDeleteProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IDeleteInterface {
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resource(var0: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceConditionalByUrl(var0: string | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByType(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteWithQuery'
     */
    resourceConditionalByType(var0: string | null): ca_uhn_fhir_rest_gclient_IDeleteWithQuery | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IIdType'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceById(var0: org_hl7_fhir_instance_model_api_IIdType | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IIdTypeInterface> | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IDeleteTyped'
     */
    resourceById(var0: string | null, var1: string | null): ca_uhn_fhir_rest_gclient_IDeleteTyped | null;
}
/**
 * Create a proxy for the {@link IDelete} interface.
 * All required methods in {@link IDeleteInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIDeleteProxy(methods: IDeleteInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IDeleteInterface>;
declare const IDelete_base: typeof IDeleteClass;
/**
 * Class ca.uhn.fhir.rest.gclient.IDelete.
 *
 * This actually imports the java class for further use.
 * The class {@link IDeleteClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IDelete extends IDelete_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IDelete;
//# sourceMappingURL=IDelete.d.ts.map