"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IGetPage = exports.createIGetPageProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IGetPage} interface.
 * All required methods in {@link IGetPageInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIGetPageProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IGetPage', methods, opts);
}
exports.createIGetPageProxy = createIGetPageProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IGetPage.
 *
 * This actually imports the java class for further use.
 * The class {@link IGetPageClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IGetPage extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IGetPage') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IGetPage = IGetPage;
exports.default = IGetPage;
//# sourceMappingURL=IGetPage.js.map