import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IMetaAddOrDeleteUnsourced as ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced } from "./IMetaAddOrDeleteUnsourced";
import { IMetaGetUnsourced as ca_uhn_fhir_rest_gclient_IMetaGetUnsourced } from "./IMetaGetUnsourced";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link IMeta} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IMetaClass extends JavaClass {
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    add(): Promise<ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    addSync(): ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaGetUnsourced'
     */
    get(var0: java_lang_Class | null): Promise<ca_uhn_fhir_rest_gclient_IMetaGetUnsourced | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaGetUnsourced'
     */
    getSync(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IMetaGetUnsourced | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    delete(): Promise<ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    deleteSync(): ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIMetaProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IMetaInterface {
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    add(): ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaGetUnsourced'
     */
    get(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IMetaGetUnsourced | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IMetaAddOrDeleteUnsourced'
     */
    delete(): ca_uhn_fhir_rest_gclient_IMetaAddOrDeleteUnsourced | null;
}
/**
 * Create a proxy for the {@link IMeta} interface.
 * All required methods in {@link IMetaInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIMetaProxy(methods: IMetaInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IMetaInterface>;
declare const IMeta_base: typeof IMetaClass;
/**
 * Class ca.uhn.fhir.rest.gclient.IMeta.
 *
 * This actually imports the java class for further use.
 * The class {@link IMetaClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IMeta extends IMeta_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IMeta;
//# sourceMappingURL=IMeta.d.ts.map