"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperationUntypedWithInputAndPartialOutput = exports.createIOperationUntypedWithInputAndPartialOutputProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOperationUntypedWithInputAndPartialOutput} interface.
 * All required methods in {@link IOperationUntypedWithInputAndPartialOutputInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOperationUntypedWithInputAndPartialOutputProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IOperationUntypedWithInputAndPartialOutput', methods, opts);
}
exports.createIOperationUntypedWithInputAndPartialOutputProxy = createIOperationUntypedWithInputAndPartialOutputProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IOperationUntypedWithInputAndPartialOutput.
 *
 * This actually imports the java class for further use.
 * The class {@link IOperationUntypedWithInputAndPartialOutputClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOperationUntypedWithInputAndPartialOutput extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IOperationUntypedWithInputAndPartialOutput') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOperationUntypedWithInputAndPartialOutput = IOperationUntypedWithInputAndPartialOutput;
exports.default = IOperationUntypedWithInputAndPartialOutput;
//# sourceMappingURL=IOperationUntypedWithInputAndPartialOutput.js.map