"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperationUnnamed = exports.createIOperationUnnamedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOperationUnnamed} interface.
 * All required methods in {@link IOperationUnnamedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOperationUnnamedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IOperationUnnamed', methods, opts);
}
exports.createIOperationUnnamedProxy = createIOperationUnnamedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IOperationUnnamed.
 *
 * This actually imports the java class for further use.
 * The class {@link IOperationUnnamedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOperationUnnamed extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IOperationUnnamed') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOperationUnnamed = IOperationUnnamed;
exports.default = IOperationUnnamed;
//# sourceMappingURL=IOperationUnnamed.js.map