"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperationUntypedWithInput = exports.createIOperationUntypedWithInputProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOperationUntypedWithInput} interface.
 * All required methods in {@link IOperationUntypedWithInputInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOperationUntypedWithInputProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IOperationUntypedWithInput', methods, opts);
}
exports.createIOperationUntypedWithInputProxy = createIOperationUntypedWithInputProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IOperationUntypedWithInput.
 *
 * This actually imports the java class for further use.
 * The class {@link IOperationUntypedWithInputClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOperationUntypedWithInput extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IOperationUntypedWithInput') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOperationUntypedWithInput = IOperationUntypedWithInput;
exports.default = IOperationUntypedWithInput;
//# sourceMappingURL=IOperationUntypedWithInput.js.map