"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperationUntyped = exports.createIOperationUntypedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOperationUntyped} interface.
 * All required methods in {@link IOperationUntypedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOperationUntypedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IOperationUntyped', methods, opts);
}
exports.createIOperationUntypedProxy = createIOperationUntypedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IOperationUntyped.
 *
 * This actually imports the java class for further use.
 * The class {@link IOperationUntypedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOperationUntyped extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IOperationUntyped') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOperationUntyped = IOperationUntyped;
exports.default = IOperationUntyped;
//# sourceMappingURL=IOperationUntyped.js.map