"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOperation = exports.createIOperationProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOperation} interface.
 * All required methods in {@link IOperationInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOperationProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IOperation', methods, opts);
}
exports.createIOperationProxy = createIOperationProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IOperation.
 *
 * This actually imports the java class for further use.
 * The class {@link IOperationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOperation extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IOperation') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOperation = IOperation;
exports.default = IOperation;
//# sourceMappingURL=IOperation.js.map