"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPatchExecutable = exports.createIPatchExecutableProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IPatchExecutable} interface.
 * All required methods in {@link IPatchExecutableInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIPatchExecutableProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IPatchExecutable', methods, opts);
}
exports.createIPatchExecutableProxy = createIPatchExecutableProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IPatchExecutable.
 *
 * This actually imports the java class for further use.
 * The class {@link IPatchExecutableClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IPatchExecutable extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IPatchExecutable') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IPatchExecutable = IPatchExecutable;
exports.default = IPatchExecutable;
//# sourceMappingURL=IPatchExecutable.js.map