import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { ISort as ca_uhn_fhir_rest_gclient_ISort } from "./ISort";
import { SortSpec as ca_uhn_fhir_rest_api_SortSpec } from "./../api/SortSpec";
import { ICriterion as ca_uhn_fhir_rest_gclient_ICriterion, ICriterionInterface as ca_uhn_fhir_rest_gclient_ICriterionInterface } from "./ICriterion";
import { IBaseQuery as ca_uhn_fhir_rest_gclient_IBaseQuery } from "./IBaseQuery";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { SearchStyleEnum as ca_uhn_fhir_rest_api_SearchStyleEnum } from "./../api/SearchStyleEnum";
import { SearchTotalModeEnum as ca_uhn_fhir_rest_api_SearchTotalModeEnum } from "./../api/SearchTotalModeEnum";
import { Include as ca_uhn_fhir_model_api_Include } from "./../../model/api/Include";
import { Collection as java_util_Collection, CollectionInterface as java_util_CollectionInterface } from "./../../../../../java/util/Collection";
import { Map as java_util_Map, MapInterface as java_util_MapInterface } from "./../../../../../java/util/Map";
import { DateRangeParam as ca_uhn_fhir_rest_param_DateRangeParam } from "./../param/DateRangeParam";
import { IClientExecutable as ca_uhn_fhir_rest_gclient_IClientExecutable } from "./IClientExecutable";
import { EncodingEnum as ca_uhn_fhir_rest_api_EncodingEnum } from "./../api/EncodingEnum";
import { CacheControlDirective as ca_uhn_fhir_rest_api_CacheControlDirective } from "./../api/CacheControlDirective";
import { SummaryEnum as ca_uhn_fhir_rest_api_SummaryEnum } from "./../api/SummaryEnum";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../../java/util/List";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
/**
 * This class just defines types, you should import {@link IQuery} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IQueryClass extends JavaClass {
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    offset(var0: java_lang_Integer | number): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    offsetSync(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    count(var0: java_lang_Integer | number): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    countSync(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.ISort'
     */
    sort(): Promise<ca_uhn_fhir_rest_gclient_ISort | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.ISort'
     */
    sortSync(): ca_uhn_fhir_rest_gclient_ISort | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SortSpec'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    sort(var0: ca_uhn_fhir_rest_api_SortSpec | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SortSpec'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    sortSync(var0: ca_uhn_fhir_rest_api_SortSpec | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    and(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    andSync(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    and(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IBaseQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    andSync(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    limitTo(var0: java_lang_Integer | number): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    limitToSync(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    returnBundle(var0: java_lang_Class | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    returnBundleSync(var0: java_lang_Class | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withSecurity(var0: string | null, var1: string | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withSecuritySync(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchStyleEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    usingStyle(var0: ca_uhn_fhir_rest_api_SearchStyleEnum | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchStyleEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    usingStyleSync(var0: ca_uhn_fhir_rest_api_SearchStyleEnum | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchTotalModeEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    totalMode(var0: ca_uhn_fhir_rest_api_SearchTotalModeEnum | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchTotalModeEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    totalModeSync(var0: ca_uhn_fhir_rest_api_SearchTotalModeEnum | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    revInclude(var0: ca_uhn_fhir_model_api_Include | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    revIncludeSync(var0: ca_uhn_fhir_model_api_Include | null): IQuery | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withAnyProfile(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withAnyProfileSync(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withProfile(var0: string | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withProfileSync(var0: string | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withTag(var0: string | null, var1: string | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withTagSync(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    where(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IBaseQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    whereSync(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    where(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    whereSync(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): IQuery | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    where(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IBaseQuery | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    whereSync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withIdAndCompartment(var0: string | null, var1: string | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withIdAndCompartmentSync(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    include(var0: ca_uhn_fhir_model_api_Include | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    includeSync(var0: ca_uhn_fhir_model_api_Include | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.param.DateRangeParam'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    lastUpdated(var0: ca_uhn_fhir_rest_param_DateRangeParam | null): Promise<IQuery | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.param.DateRangeParam'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    lastUpdatedSync(var0: ca_uhn_fhir_rest_param_DateRangeParam | null): IQuery | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    whereMap(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IBaseQuery | null>;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    whereMapSync(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @return original return type: 'java.lang.Object'
     */
    execute(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    executeSync(): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    accept(var0: string | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    acceptSync(var0: string | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encoded(var0: ca_uhn_fhir_rest_api_EncodingEnum | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedSync(var0: ca_uhn_fhir_rest_api_EncodingEnum | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.CacheControlDirective'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    cacheControl(var0: ca_uhn_fhir_rest_api_CacheControlDirective | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.CacheControlDirective'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    cacheControlSync(var0: ca_uhn_fhir_rest_api_CacheControlDirective | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    elementsSubset(var0: (string | null)[] | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    elementsSubsetSync(var0: (string | null)[] | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SummaryEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    summaryMode(var0: ca_uhn_fhir_rest_api_SummaryEnum | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SummaryEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    summaryModeSync(var0: ca_uhn_fhir_rest_api_SummaryEnum | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedXml(): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedXmlSync(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseType(var0: java_lang_Class | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseTypeSync(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedJson(): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedJsonSync(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    prettyPrint(): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    prettyPrintSync(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseTypes(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseTypesSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    withAdditionalHeader(var0: string | null, var1: string | null): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    withAdditionalHeaderSync(var0: string | null, var1: string | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    andLogRequestAndResponse(var0: java_lang_Boolean | boolean): Promise<ca_uhn_fhir_rest_gclient_IClientExecutable | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    andLogRequestAndResponseSync(var0: java_lang_Boolean | boolean): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIQueryProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IQueryInterface {
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    offset(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    count(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.ISort'
     */
    sort(): ca_uhn_fhir_rest_gclient_ISort | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SortSpec'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    sort(var0: ca_uhn_fhir_rest_api_SortSpec | null): IQuery | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    and?(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    and?(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    limitTo(var0: java_lang_Integer | number): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    returnBundle(var0: java_lang_Class | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withSecurity(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchStyleEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    usingStyle(var0: ca_uhn_fhir_rest_api_SearchStyleEnum | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SearchTotalModeEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    totalMode(var0: ca_uhn_fhir_rest_api_SearchTotalModeEnum | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    revInclude(var0: ca_uhn_fhir_model_api_Include | null): IQuery | null;
    /**
     * @param var0 original type: 'java.util.Collection'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withAnyProfile(var0: java_util_Collection | JavaInterfaceProxy<java_util_CollectionInterface> | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withProfile(var0: string | null): IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withTag(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    where?(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    where?(var0: ca_uhn_fhir_rest_gclient_ICriterion | JavaInterfaceProxy<ca_uhn_fhir_rest_gclient_ICriterionInterface> | null): IQuery | null;
    /**
     * **Note: Although this method is marked as optional, it actually must be implemented.**
     *
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    where?(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    withIdAndCompartment(var0: string | null, var1: string | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.Include'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    include(var0: ca_uhn_fhir_model_api_Include | null): IQuery | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.param.DateRangeParam'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    lastUpdated(var0: ca_uhn_fhir_rest_param_DateRangeParam | null): IQuery | null;
    /**
     * @param var0 original type: 'java.util.Map'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IBaseQuery'
     */
    whereMap(var0: java_util_Map | JavaInterfaceProxy<java_util_MapInterface> | null): ca_uhn_fhir_rest_gclient_IBaseQuery | null;
    /**
     * @return original return type: 'java.lang.Object'
     */
    execute(): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    accept(var0: string | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.EncodingEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encoded(var0: ca_uhn_fhir_rest_api_EncodingEnum | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.CacheControlDirective'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    cacheControl(var0: ca_uhn_fhir_rest_api_CacheControlDirective | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.String[]'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    elementsSubset(var0: (string | null)[] | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.api.SummaryEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    summaryMode(var0: ca_uhn_fhir_rest_api_SummaryEnum | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedXml(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseType(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    encodedJson(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    prettyPrint(): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    preferResponseTypes(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    withAdditionalHeader(var0: string | null, var1: string | null): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IClientExecutable'
     */
    andLogRequestAndResponse(var0: java_lang_Boolean | boolean): ca_uhn_fhir_rest_gclient_IClientExecutable | null;
}
/**
 * Create a proxy for the {@link IQuery} interface.
 * All required methods in {@link IQueryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIQueryProxy(methods: IQueryInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IQueryInterface>;
declare const IQuery_base: typeof IQueryClass;
/**
 * Class ca.uhn.fhir.rest.gclient.IQuery.
 *
 * This actually imports the java class for further use.
 * The class {@link IQueryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IQuery extends IQuery_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IQuery;
//# sourceMappingURL=IQuery.d.ts.map