"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISort = exports.createISortProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ISort} interface.
 * All required methods in {@link ISortInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createISortProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ISort', methods, opts);
}
exports.createISortProxy = createISortProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ISort.
 *
 * This actually imports the java class for further use.
 * The class {@link ISortClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ISort extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ISort') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ISort = ISort;
exports.default = ISort;
//# sourceMappingURL=ISort.js.map