"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITransactionTyped = exports.createITransactionTypedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ITransactionTyped} interface.
 * All required methods in {@link ITransactionTypedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createITransactionTypedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ITransactionTyped', methods, opts);
}
exports.createITransactionTypedProxy = createITransactionTypedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ITransactionTyped.
 *
 * This actually imports the java class for further use.
 * The class {@link ITransactionTypedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ITransactionTyped extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ITransactionTyped') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ITransactionTyped = ITransactionTyped;
exports.default = ITransactionTyped;
//# sourceMappingURL=ITransactionTyped.js.map