"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITransaction = exports.createITransactionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ITransaction} interface.
 * All required methods in {@link ITransactionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createITransactionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.ITransaction', methods, opts);
}
exports.createITransactionProxy = createITransactionProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.ITransaction.
 *
 * This actually imports the java class for further use.
 * The class {@link ITransactionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ITransaction extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.ITransaction') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ITransaction = ITransaction;
exports.default = ITransaction;
//# sourceMappingURL=ITransaction.js.map