import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IQuery as ca_uhn_fhir_rest_gclient_IQuery } from "./IQuery";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link IUntypedQuery} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IUntypedQueryClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResource(var0: java_lang_Class | null): Promise<ca_uhn_fhir_rest_gclient_IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResourceSync(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResource(var0: string | null): Promise<ca_uhn_fhir_rest_gclient_IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResourceSync(var0: string | null): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forAllResources(): Promise<ca_uhn_fhir_rest_gclient_IQuery | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forAllResourcesSync(): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    byUrl(var0: string | null): Promise<ca_uhn_fhir_rest_gclient_IQuery | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    byUrlSync(var0: string | null): ca_uhn_fhir_rest_gclient_IQuery | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIUntypedQueryProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IUntypedQueryInterface {
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResource(var0: java_lang_Class | null): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forResource(var0: string | null): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    forAllResources(): ca_uhn_fhir_rest_gclient_IQuery | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.IQuery'
     */
    byUrl(var0: string | null): ca_uhn_fhir_rest_gclient_IQuery | null;
}
/**
 * Create a proxy for the {@link IUntypedQuery} interface.
 * All required methods in {@link IUntypedQueryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIUntypedQueryProxy(methods: IUntypedQueryInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IUntypedQueryInterface>;
declare const IUntypedQuery_base: typeof IUntypedQueryClass;
/**
 * Class ca.uhn.fhir.rest.gclient.IUntypedQuery.
 *
 * This actually imports the java class for further use.
 * The class {@link IUntypedQueryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IUntypedQuery extends IUntypedQuery_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IUntypedQuery;
//# sourceMappingURL=IUntypedQuery.d.ts.map