"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUpdateWithQuery = exports.createIUpdateWithQueryProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IUpdateWithQuery} interface.
 * All required methods in {@link IUpdateWithQueryInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIUpdateWithQueryProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IUpdateWithQuery', methods, opts);
}
exports.createIUpdateWithQueryProxy = createIUpdateWithQueryProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IUpdateWithQuery.
 *
 * This actually imports the java class for further use.
 * The class {@link IUpdateWithQueryClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IUpdateWithQuery extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IUpdateWithQuery') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IUpdateWithQuery = IUpdateWithQuery;
exports.default = IUpdateWithQuery;
//# sourceMappingURL=IUpdateWithQuery.js.map