"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUpdateTyped = exports.createIUpdateTypedProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IUpdateTyped} interface.
 * All required methods in {@link IUpdateTypedInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIUpdateTypedProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IUpdateTyped', methods, opts);
}
exports.createIUpdateTypedProxy = createIUpdateTypedProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IUpdateTyped.
 *
 * This actually imports the java class for further use.
 * The class {@link IUpdateTypedClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IUpdateTyped extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IUpdateTyped') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IUpdateTyped = IUpdateTyped;
exports.default = IUpdateTyped;
//# sourceMappingURL=IUpdateTyped.js.map