"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IValidate = exports.createIValidateProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IValidate} interface.
 * All required methods in {@link IValidateInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIValidateProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.rest.gclient.IValidate', methods, opts);
}
exports.createIValidateProxy = createIValidateProxy;
/**
 * Class ca.uhn.fhir.rest.gclient.IValidate.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidateClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IValidate extends (0, java_bridge_1.importClass)('ca.uhn.fhir.rest.gclient.IValidate') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IValidate = IValidate;
exports.default = IValidate;
//# sourceMappingURL=IValidate.js.map