import { JavaClass, BasicOrJavaType } from "java-bridge";
import { NumberClientParam$IMatches as ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches } from "./NumberClientParam$IMatches";
import { ParamPrefixEnum as ca_uhn_fhir_rest_param_ParamPrefixEnum } from "./../param/ParamPrefixEnum";
import { ICriterion as ca_uhn_fhir_rest_gclient_ICriterion } from "./ICriterion";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link QuantityClientParam} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class QuantityClientParamClass extends JavaClass {
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.param.ParamPrefixEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    withPrefix(var0: ca_uhn_fhir_rest_param_ParamPrefixEnum | null): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.rest.param.ParamPrefixEnum'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    withPrefixSync(var0: ca_uhn_fhir_rest_param_ParamPrefixEnum | null): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamNameSync(): string | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     */
    isMissing(var0: java_lang_Boolean | boolean): Promise<ca_uhn_fhir_rest_gclient_ICriterion | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.ICriterion'
     */
    isMissingSync(var0: java_lang_Boolean | boolean): ca_uhn_fhir_rest_gclient_ICriterion | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    exactly(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    exactlySync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    greaterThanOrEquals(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    greaterThanOrEqualsSync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    lessThan(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    lessThanSync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    approximately(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    approximatelySync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    greaterThan(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    greaterThanSync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    lessThanOrEquals(): Promise<ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.rest.gclient.NumberClientParam$IMatches'
     */
    lessThanOrEqualsSync(): ca_uhn_fhir_rest_gclient_NumberClientParam$IMatches | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.rest.gclient.QuantityClientParam'
     */
    static newInstanceAsync(var0: string | null): Promise<QuantityClientParam>;
    /**
     * @param var0 original type: 'java.lang.String'
     */
    constructor(var0: string | null);
}
declare const QuantityClientParam_base: typeof QuantityClientParamClass;
/**
 * Class ca.uhn.fhir.rest.gclient.QuantityClientParam.
 *
 * This actually imports the java class for further use.
 * The class {@link QuantityClientParamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class QuantityClientParam extends QuantityClientParam_base {
}
export default QuantityClientParam;
//# sourceMappingURL=QuantityClientParam.d.ts.map