/// <reference types="node" />
import { JavaClass, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { List as java_util_List } from "./../../../../../java/util/List";
import { IValidationSupport$CodeValidationResult as ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult } from "./IValidationSupport$CodeValidationResult";
import { ValidationSupportContext as ca_uhn_fhir_context_support_ValidationSupportContext } from "./ValidationSupportContext";
import { ConceptValidationOptions as ca_uhn_fhir_context_support_ConceptValidationOptions } from "./ConceptValidationOptions";
import { IBaseResource as org_hl7_fhir_instance_model_api_IBaseResource, IBaseResourceInterface as org_hl7_fhir_instance_model_api_IBaseResourceInterface } from "./../../../../../org/hl7/fhir/instance/model/api/IBaseResource";
import { IValidationSupport$ValueSetExpansionOutcome as ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome } from "./IValidationSupport$ValueSetExpansionOutcome";
import { ValueSetExpansionOptions as ca_uhn_fhir_context_support_ValueSetExpansionOptions } from "./ValueSetExpansionOptions";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { IValidationSupport$LookupCodeResult as ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult } from "./IValidationSupport$LookupCodeResult";
import { FhirContext as ca_uhn_fhir_context_FhirContext } from "./../FhirContext";
import { TranslateConceptResults as ca_uhn_fhir_context_support_TranslateConceptResults } from "./TranslateConceptResults";
import { IValidationSupport$TranslateCodeRequest as ca_uhn_fhir_context_support_IValidationSupport$TranslateCodeRequest } from "./IValidationSupport$TranslateCodeRequest";
/**
 * This class just defines types, you should import {@link IValidationSupport} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IValidationSupportClass extends JavaClass {
    /**
     * Original type: 'java.lang.String'
     */
    static readonly URL_PREFIX_VALUE_SET: string | null;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllStructureDefinitions(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllStructureDefinitionsSync(): java_util_List | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCodeInValueSet(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCodeInValueSetSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchStructureDefinition(var0: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchStructureDefinitionSync(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllConformanceResources(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllConformanceResourcesSync(): java_util_List | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isCodeSystemSupported(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isCodeSystemSupportedSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isValueSetSupported(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isValueSetSupportedSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isEnabledValidationForCodingsLogicalAnd(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEnabledValidationForCodingsLogicalAndSync(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllNonBaseStructureDefinitions(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllNonBaseStructureDefinitionsSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isRemoteTerminologyServiceConfigured(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isRemoteTerminologyServiceConfiguredSync(): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSet(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSetSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSet(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: string | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSetSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: string | null): ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchValueSet(var0: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchValueSetSync(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchResource(var0: java_lang_Class | null, var1: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchResourceSync(var0: java_lang_Class | null, var1: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCode(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: string | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCodeSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: string | null): ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchCodeSystem(var0: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchCodeSystemSync(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'byte[]'
     */
    fetchBinary(var0: string | null): Promise<Buffer | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'byte[]'
     */
    fetchBinarySync(var0: string | null): Buffer | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCode(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCodeSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null): ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCode(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null, var3: string | null): Promise<ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCodeSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null, var3: string | null): ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirContext'
     */
    getFhirContext(): Promise<ca_uhn_fhir_context_FhirContext | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirContext'
     */
    getFhirContextSync(): ca_uhn_fhir_context_FhirContext | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    generateSnapshot(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: string | null, var3: string | null, var4: string | null): Promise<org_hl7_fhir_instance_model_api_IBaseResource | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    generateSnapshotSync(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: string | null, var3: string | null, var4: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.IValidationSupport$TranslateCodeRequest'
     * @return original return type: 'ca.uhn.fhir.context.support.TranslateConceptResults'
     */
    translateConcept(var0: ca_uhn_fhir_context_support_IValidationSupport$TranslateCodeRequest | null): Promise<ca_uhn_fhir_context_support_TranslateConceptResults | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.IValidationSupport$TranslateCodeRequest'
     * @return original return type: 'ca.uhn.fhir.context.support.TranslateConceptResults'
     */
    translateConceptSync(var0: ca_uhn_fhir_context_support_IValidationSupport$TranslateCodeRequest | null): ca_uhn_fhir_context_support_TranslateConceptResults | null;
    /**
     * @return original return type: 'void'
     */
    invalidateCaches(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    invalidateCachesSync(): void;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIValidationSupportProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IValidationSupportInterface {
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllStructureDefinitions?(): java_util_List | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCodeInValueSet?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchStructureDefinition?(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllConformanceResources?(): java_util_List | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isCodeSystemSupported?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isValueSetSupported?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isEnabledValidationForCodingsLogicalAnd?(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    fetchAllNonBaseStructureDefinitions?(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isRemoteTerminologyServiceConfigured?(): boolean;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSet?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null): ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ValueSetExpansionOptions'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome'
     */
    expandValueSet?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ValueSetExpansionOptions | null, var2: string | null): ca_uhn_fhir_context_support_IValidationSupport$ValueSetExpansionOutcome | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchValueSet?(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchResource?(var0: java_lang_Class | null, var1: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'ca.uhn.fhir.context.support.ConceptValidationOptions'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @param var5 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$CodeValidationResult'
     */
    validateCode?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: ca_uhn_fhir_context_support_ConceptValidationOptions | null, var2: string | null, var3: string | null, var4: string | null, var5: string | null): ca_uhn_fhir_context_support_IValidationSupport$CodeValidationResult | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    fetchCodeSystem?(var0: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'byte[]'
     */
    fetchBinary?(var0: string | null): Buffer | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCode?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null): ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult'
     */
    lookupCode?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: string | null, var2: string | null, var3: string | null): ca_uhn_fhir_context_support_IValidationSupport$LookupCodeResult | null;
    /**
     * @return original return type: 'ca.uhn.fhir.context.FhirContext'
     */
    getFhirContext(): ca_uhn_fhir_context_FhirContext | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     * @param var1 original type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseResource'
     */
    generateSnapshot?(var0: ca_uhn_fhir_context_support_ValidationSupportContext | null, var1: org_hl7_fhir_instance_model_api_IBaseResource | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseResourceInterface> | null, var2: string | null, var3: string | null, var4: string | null): org_hl7_fhir_instance_model_api_IBaseResource | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.IValidationSupport$TranslateCodeRequest'
     * @return original return type: 'ca.uhn.fhir.context.support.TranslateConceptResults'
     */
    translateConcept?(var0: ca_uhn_fhir_context_support_IValidationSupport$TranslateCodeRequest | null): ca_uhn_fhir_context_support_TranslateConceptResults | null;
    /**
     * @return original return type: 'void'
     */
    invalidateCaches?(): void;
}
/**
 * Create a proxy for the {@link IValidationSupport} interface.
 * All required methods in {@link IValidationSupportInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIValidationSupportProxy(methods: IValidationSupportInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IValidationSupportInterface>;
declare const IValidationSupport_base: typeof IValidationSupportClass;
/**
 * Class ca.uhn.fhir.context.support.IValidationSupport.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationSupportClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IValidationSupport extends IValidationSupport_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IValidationSupport;
//# sourceMappingURL=IValidationSupport.d.ts.map