"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IValidationSupport$LookupCodeResult = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationSupport$LookupCodeResultClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IValidationSupport$LookupCodeResult extends (0, java_bridge_1.importClass)('ca.uhn.fhir.context.support.IValidationSupport$LookupCodeResult') {
}
exports.IValidationSupport$LookupCodeResult = IValidationSupport$LookupCodeResult;
exports.default = IValidationSupport$LookupCodeResult;
//# sourceMappingURL=IValidationSupport$LookupCodeResult.js.map