"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IValidationSupport$ValueSetExpansionOutcome = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationSupport$ValueSetExpansionOutcomeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IValidationSupport$ValueSetExpansionOutcome extends (0, java_bridge_1.importClass)('ca.uhn.fhir.context.support.IValidationSupport$ValueSetExpansionOutcome') {
}
exports.IValidationSupport$ValueSetExpansionOutcome = IValidationSupport$ValueSetExpansionOutcome;
exports.default = IValidationSupport$ValueSetExpansionOutcome;
//# sourceMappingURL=IValidationSupport$ValueSetExpansionOutcome.js.map