import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IValidationSupport as ca_uhn_fhir_context_support_IValidationSupport, IValidationSupportInterface as ca_uhn_fhir_context_support_IValidationSupportInterface } from "./IValidationSupport";
import { Set as java_util_Set } from "./../../../../../java/util/Set";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link ValidationSupportContext} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ValidationSupportContextClass extends JavaClass {
    /**
     * @return original return type: 'boolean'
     */
    isEnabledValidationForCodingsLogicalAnd(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEnabledValidationForCodingsLogicalAndSync(): boolean;
    /**
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport'
     */
    getRootValidationSupport(): Promise<ca_uhn_fhir_context_support_IValidationSupport | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.context.support.IValidationSupport'
     */
    getRootValidationSupportSync(): ca_uhn_fhir_context_support_IValidationSupport | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getCurrentlyGeneratingSnapshots(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getCurrentlyGeneratingSnapshotsSync(): java_util_Set | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.IValidationSupport'
     * @return original return type: 'ca.uhn.fhir.context.support.ValidationSupportContext'
     */
    static newInstanceAsync(var0: ca_uhn_fhir_context_support_IValidationSupport | JavaInterfaceProxy<ca_uhn_fhir_context_support_IValidationSupportInterface> | null): Promise<ValidationSupportContext>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.context.support.IValidationSupport'
     */
    constructor(var0: ca_uhn_fhir_context_support_IValidationSupport | JavaInterfaceProxy<ca_uhn_fhir_context_support_IValidationSupportInterface> | null);
}
declare const ValidationSupportContext_base: typeof ValidationSupportContextClass;
/**
 * Class ca.uhn.fhir.context.support.ValidationSupportContext.
 *
 * This actually imports the java class for further use.
 * The class {@link ValidationSupportContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ValidationSupportContext extends ValidationSupportContext_base {
}
export default ValidationSupportContext;
//# sourceMappingURL=ValidationSupportContext.d.ts.map