import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
import { XhtmlNode as org_hl7_fhir_utilities_xhtml_XhtmlNode } from "./XhtmlNode";
import { HierarchicalTableGenerator$TableModel as org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel } from "./HierarchicalTableGenerator$TableModel";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../../java/util/Set";
import { HierarchicalTableGenerator$TableGenerationMode as org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableGenerationMode } from "./HierarchicalTableGenerator$TableGenerationMode";
import { Date as java_util_Date } from "./../../../../../java/util/Date";
import { TranslationServices as org_hl7_fhir_utilities_TranslationServices, TranslationServicesInterface as org_hl7_fhir_utilities_TranslationServicesInterface } from "./../TranslationServices";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link HierarchicalTableGenerator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class HierarchicalTableGeneratorClass extends JavaClass {
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_REFERENCE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_PRIMITIVE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_KEY: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_DATATYPE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_RESOURCE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_ELEMENT: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_OBJECT_BOX: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_REUSE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_EXTENSION: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_CHOICE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_SLICE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_SLICE_ITEM: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_FIXED: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_EXTENSION_SIMPLE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_PROFILE: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly TEXT_ICON_EXTENSION_COMPLEX: string | null;
    /**
     * Original type: 'int'
     */
    static readonly NEW_REGULAR: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly CONTINUE_REGULAR: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly NEW_SLICER: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly CONTINUE_SLICER: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly NEW_SLICE: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly CONTINUE_SLICE: java_lang_Integer | number;
    /**
     * Original type: 'boolean'
     */
    static ACTIVE_TABLES: java_lang_Boolean | boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'int'
     * @param var3 original type: 'java.util.Set'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.XhtmlNode'
     */
    generate(var0: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null, var1: string | null, var2: java_lang_Integer | number, var3: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<org_hl7_fhir_utilities_xhtml_XhtmlNode | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'int'
     * @param var3 original type: 'java.util.Set'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.XhtmlNode'
     */
    generateSync(var0: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null, var1: string | null, var2: java_lang_Integer | number, var3: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): org_hl7_fhir_utilities_xhtml_XhtmlNode | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initGridTable(var0: string | null, var1: string | null): Promise<org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initGridTableSync(var0: string | null, var1: string | null): org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'boolean'
     * @param var5 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableGenerationMode'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initNormalTable(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean, var3: string | null, var4: java_lang_Boolean | boolean, var5: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableGenerationMode | null): Promise<org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'boolean'
     * @param var5 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableGenerationMode'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initNormalTableSync(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean, var3: string | null, var4: java_lang_Boolean | boolean, var5: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableGenerationMode | null): org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    static help16AsData(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    static help16AsDataSync(): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    emptyRow(var0: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    emptyRowSync(var0: org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null, var1: java_lang_Integer | number): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initComparisonTable(var0: string | null, var1: string | null): Promise<org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel'
     */
    initComparisonTableSync(var0: string | null, var1: string | null): org_hl7_fhir_utilities_xhtml_HierarchicalTableGenerator$TableModel | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.String'
     */
    translate(var0: string | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.String'
     */
    translateSync(var0: string | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): string | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    toStr(var0: java_lang_Integer | number): Promise<string | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    toStrSync(var0: java_lang_Integer | number): string | null;
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'java.lang.String'
     */
    toStr(var0: java_util_Date | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'java.lang.String'
     */
    toStrSync(var0: java_util_Date | null): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.TranslationServices'
     */
    getTranslator(): Promise<org_hl7_fhir_utilities_TranslationServices | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.TranslationServices'
     */
    getTranslatorSync(): org_hl7_fhir_utilities_TranslationServices | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TranslationServices'
     * @return original return type: 'void'
     */
    setTranslator(var0: org_hl7_fhir_utilities_TranslationServices | JavaInterfaceProxy<org_hl7_fhir_utilities_TranslationServicesInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TranslationServices'
     * @return original return type: 'void'
     */
    setTranslatorSync(var0: org_hl7_fhir_utilities_TranslationServices | JavaInterfaceProxy<org_hl7_fhir_utilities_TranslationServicesInterface> | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean): Promise<HierarchicalTableGenerator>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Boolean | boolean): Promise<HierarchicalTableGenerator>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator'
     */
    static newInstanceAsync(): Promise<HierarchicalTableGenerator>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     */
    constructor(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean);
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     */
    constructor(var0: string | null, var1: java_lang_Boolean | boolean);
    constructor();
}
declare const HierarchicalTableGenerator_base: typeof HierarchicalTableGeneratorClass;
/**
 * Class org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator.
 *
 * This actually imports the java class for further use.
 * The class {@link HierarchicalTableGeneratorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class HierarchicalTableGenerator extends HierarchicalTableGenerator_base {
}
export default HierarchicalTableGenerator;
//# sourceMappingURL=HierarchicalTableGenerator.d.ts.map