"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HierarchicalTableGenerator$TableModel = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel.
 *
 * This actually imports the java class for further use.
 * The class {@link HierarchicalTableGenerator$TableModelClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class HierarchicalTableGenerator$TableModel extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.xhtml.HierarchicalTableGenerator$TableModel') {
}
exports.HierarchicalTableGenerator$TableModel = HierarchicalTableGenerator$TableModel;
exports.default = HierarchicalTableGenerator$TableModel;
//# sourceMappingURL=HierarchicalTableGenerator$TableModel.js.map