"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.XhtmlNode$Location = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.xhtml.XhtmlNode$Location.
 *
 * This actually imports the java class for further use.
 * The class {@link XhtmlNode$LocationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class XhtmlNode$Location extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.xhtml.XhtmlNode$Location') {
}
exports.XhtmlNode$Location = XhtmlNode$Location;
exports.default = XhtmlNode$Location;
//# sourceMappingURL=XhtmlNode$Location.js.map