import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { Consumer as java_util_function_Consumer, ConsumerInterface as java_util_function_ConsumerInterface } from "./../../../../java/util/function/Consumer";
import { Reader as java_io_Reader } from "./../../../../java/io/Reader";
/**
 * This class just defines types, you should import {@link LineIterator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LineIteratorClass extends JavaClass {
    /**
     * @return original return type: 'void'
     */
    remove(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    removeSync(): void;
    /**
     * @return original return type: 'boolean'
     */
    hasNext(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasNextSync(): boolean;
    /**
     * @return original return type: 'java.lang.Object'
     */
    next(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    nextSync(): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    next(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nextSync(): string | null;
    /**
     * @return original return type: 'void'
     */
    close(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    closeSync(): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    nextLine(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    nextLineSync(): string | null;
    /**
     * @param var0 original type: 'org.apache.commons.io.LineIterator'
     * @return original return type: 'void'
     */
    static closeQuietly(var0: LineIteratorClass | null): Promise<void>;
    /**
     * @param var0 original type: 'org.apache.commons.io.LineIterator'
     * @return original return type: 'void'
     */
    static closeQuietlySync(var0: LineIteratorClass | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    forEachRemaining(var0: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    forEachRemainingSync(var0: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): void;
    /**
     * @param var0 original type: 'java.io.Reader'
     * @return original return type: 'org.apache.commons.io.LineIterator'
     */
    static newInstanceAsync(var0: java_io_Reader | null): Promise<LineIterator>;
    /**
     * @param var0 original type: 'java.io.Reader'
     */
    constructor(var0: java_io_Reader | null);
}
declare const LineIterator_base: typeof LineIteratorClass;
/**
 * Class org.apache.commons.io.LineIterator.
 *
 * This actually imports the java class for further use.
 * The class {@link LineIteratorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class LineIterator extends LineIterator_base {
}
export default LineIterator;
//# sourceMappingURL=LineIterator.d.ts.map