import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IBaseDatatype as org_hl7_fhir_instance_model_api_IBaseDatatype, IBaseDatatypeInterface as org_hl7_fhir_instance_model_api_IBaseDatatypeInterface } from "./../../../../../org/hl7/fhir/instance/model/api/IBaseDatatype";
import { List as java_util_List } from "./../../../../../java/util/List";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
import { IPrimitiveDatatype as ca_uhn_fhir_model_api_IPrimitiveDatatype } from "./IPrimitiveDatatype";
import { StringDt as ca_uhn_fhir_model_primitive_StringDt } from "./../primitive/StringDt";
import { IdDt as ca_uhn_fhir_model_primitive_IdDt } from "./../primitive/IdDt";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
/**
 * This class just defines types, you should import {@link ExtensionDt} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ExtensionDtClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    getValue(): Promise<org_hl7_fhir_instance_model_api_IBaseDatatype | null>;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    getValueSync(): org_hl7_fhir_instance_model_api_IBaseDatatype | null;
    /**
     * @return original return type: 'boolean'
     */
    isEmpty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEmptySync(): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): Promise<ExtensionDt | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setValueSync(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): ExtensionDt | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'java.lang.Object'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'java.lang.Object'
     */
    setValueSync(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getExtension(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getExtensionSync(): java_util_List | null;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getAllPopulatedChildElementsOfType(var0: java_lang_Class | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.Class'
     * @return original return type: 'java.util.List'
     */
    getAllPopulatedChildElementsOfTypeSync(var0: java_lang_Class | null): java_util_List | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrlAsString(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrlAsStringSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrl(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrlSync(): string | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setModifier(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setModifierSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isModifier(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isModifierSync(): boolean;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.IPrimitiveDatatype'
     */
    getValueAsPrimitive(): Promise<ca_uhn_fhir_model_api_IPrimitiveDatatype | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.IPrimitiveDatatype'
     */
    getValueAsPrimitiveSync(): ca_uhn_fhir_model_api_IPrimitiveDatatype | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    setUrl(var0: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    setUrlSync(var0: string | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setUrl(var0: string | null): Promise<ExtensionDt | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setUrlSync(var0: string | null): ExtensionDt | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.primitive.StringDt'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setUrl(var0: ca_uhn_fhir_model_primitive_StringDt | null): Promise<ExtensionDt | null>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.primitive.StringDt'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    setUrlSync(var0: ca_uhn_fhir_model_primitive_StringDt | null): ExtensionDt | null;
    /**
     * @return original return type: 'ca.uhn.fhir.model.primitive.IdDt'
     */
    getId(): Promise<ca_uhn_fhir_model_primitive_IdDt | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.primitive.IdDt'
     */
    getIdSync(): ca_uhn_fhir_model_primitive_IdDt | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getElementSpecificId(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getElementSpecificIdSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setElementSpecificId(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setElementSpecificIdSync(var0: string | null): void;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.primitive.IdDt'
     * @return original return type: 'void'
     */
    setId(var0: ca_uhn_fhir_model_primitive_IdDt | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.primitive.IdDt'
     * @return original return type: 'void'
     */
    setIdSync(var0: ca_uhn_fhir_model_primitive_IdDt | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setId(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setIdSync(var0: string | null): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getUndeclaredExtensions(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getUndeclaredExtensionsSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getUndeclaredModifierExtensions(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getUndeclaredModifierExtensionsSync(): java_util_List | null;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    addUndeclaredExtension(var0: java_lang_Boolean | boolean, var1: string | null): Promise<ExtensionDt | null>;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    addUndeclaredExtensionSync(var0: java_lang_Boolean | boolean, var1: string | null): ExtensionDt | null;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    addUndeclaredExtension(var0: java_lang_Boolean | boolean, var1: string | null, var2: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): Promise<ExtensionDt | null>;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    addUndeclaredExtensionSync(var0: java_lang_Boolean | boolean, var1: string | null, var2: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): ExtensionDt | null;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.ExtensionDt'
     * @return original return type: 'void'
     */
    addUndeclaredExtension(var0: ExtensionDtClass | null): Promise<void>;
    /**
     * @param var0 original type: 'ca.uhn.fhir.model.api.ExtensionDt'
     * @return original return type: 'void'
     */
    addUndeclaredExtensionSync(var0: ExtensionDtClass | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getUndeclaredExtensionsByUrl(var0: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getUndeclaredExtensionsByUrlSync(var0: string | null): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getAllUndeclaredExtensions(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getAllUndeclaredExtensionsSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPre(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPreSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    hasFormatComment(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasFormatCommentSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getUserData(var0: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getUserDataSync(var0: string | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    setUserData(var0: string | null, var1: BasicOrJavaType | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    setUserDataSync(var0: string | null, var1: BasicOrJavaType | null): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPost(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPostSync(): java_util_List | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    fhirType(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    fhirTypeSync(): string | null;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    static newInstanceAsync(var0: java_lang_Boolean | boolean, var1: string | null, var2: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): Promise<ExtensionDt>;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    static newInstanceAsync(var0: java_lang_Boolean | boolean, var1: string | null): Promise<ExtensionDt>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    static newInstanceAsync(var0: java_lang_Boolean | boolean): Promise<ExtensionDt>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.ExtensionDt'
     */
    static newInstanceAsync(): Promise<ExtensionDt>;
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    constructor(var0: java_lang_Boolean | boolean, var1: string | null, var2: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null);
    /**
     * @param var0 original type: 'boolean'
     * @param var1 original type: 'java.lang.String'
     */
    constructor(var0: java_lang_Boolean | boolean, var1: string | null);
    /**
     * @param var0 original type: 'boolean'
     */
    constructor(var0: java_lang_Boolean | boolean);
    constructor();
}
declare const ExtensionDt_base: typeof ExtensionDtClass;
/**
 * Class ca.uhn.fhir.model.api.ExtensionDt.
 *
 * This actually imports the java class for further use.
 * The class {@link ExtensionDtClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ExtensionDt extends ExtensionDt_base {
}
export default ExtensionDt;
//# sourceMappingURL=ExtensionDt.d.ts.map