import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Boolean as java_lang_Boolean } from "./../../../../../java/lang/Boolean";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link Include} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IncludeClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.String'
     */
    getValue(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getValueSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setValue(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setValueSync(var0: string | null): void;
    /**
     * @return original return type: 'boolean'
     */
    isLocked(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isLockedSync(): boolean;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    toLocked(): Promise<Include | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    toLockedSync(): Include | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamNameSync(): string | null;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    asNonRecursive(): Promise<Include | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    asNonRecursiveSync(): Include | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamType(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamTypeSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    withType(var0: string | null): Promise<Include | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    withTypeSync(var0: string | null): Include | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamTargetType(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getParamTargetTypeSync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isRecurse(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isRecurseSync(): boolean;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    asRecursive(): Promise<Include | null>;
    /**
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    asRecursiveSync(): Include | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    setRecurse(var0: java_lang_Boolean | boolean): Promise<Include | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    setRecurseSync(var0: java_lang_Boolean | boolean): Include | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean): Promise<Include>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    static newInstanceAsync(var0: string | null, var1: java_lang_Boolean | boolean): Promise<Include>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'ca.uhn.fhir.model.api.Include'
     */
    static newInstanceAsync(var0: string | null): Promise<Include>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     */
    constructor(var0: string | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean);
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     */
    constructor(var0: string | null, var1: java_lang_Boolean | boolean);
    /**
     * @param var0 original type: 'java.lang.String'
     */
    constructor(var0: string | null);
}
declare const Include_base: typeof IncludeClass;
/**
 * Class ca.uhn.fhir.model.api.Include.
 *
 * This actually imports the java class for further use.
 * The class {@link IncludeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Include extends Include_base {
}
export default Include;
//# sourceMappingURL=Include.d.ts.map