"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IQueryParameterType = exports.createIQueryParameterTypeProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IQueryParameterType} interface.
 * All required methods in {@link IQueryParameterTypeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIQueryParameterTypeProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.model.api.IQueryParameterType', methods, opts);
}
exports.createIQueryParameterTypeProxy = createIQueryParameterTypeProxy;
/**
 * Class ca.uhn.fhir.model.api.IQueryParameterType.
 *
 * This actually imports the java class for further use.
 * The class {@link IQueryParameterTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IQueryParameterType extends (0, java_bridge_1.importClass)('ca.uhn.fhir.model.api.IQueryParameterType') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IQueryParameterType = IQueryParameterType;
exports.default = IQueryParameterType;
//# sourceMappingURL=IQueryParameterType.js.map