"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemporalPrecisionEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.model.api.TemporalPrecisionEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link TemporalPrecisionEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TemporalPrecisionEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.model.api.TemporalPrecisionEnum') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TemporalPrecisionEnum = TemporalPrecisionEnum;
exports.default = TemporalPrecisionEnum;
//# sourceMappingURL=TemporalPrecisionEnum.js.map