import { JavaClass, BasicOrJavaType } from "java-bridge";
import { InputStream as java_io_InputStream } from "./../../../../../java/io/InputStream";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link BasePackageCacheManager$InputStreamWithSrc} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BasePackageCacheManager$InputStreamWithSrcClass extends JavaClass {
    /**
     * Original type: 'java.io.InputStream'
     */
    stream: java_io_InputStream | null;
    /**
     * Original type: 'java.lang.String'
     */
    url: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    version: string | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.npm.BasePackageCacheManager$InputStreamWithSrc'
     */
    static newInstanceAsync(var0: java_io_InputStream | null, var1: string | null, var2: string | null): Promise<BasePackageCacheManager$InputStreamWithSrc>;
    /**
     * @param var0 original type: 'java.io.InputStream'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     */
    constructor(var0: java_io_InputStream | null, var1: string | null, var2: string | null);
}
declare const BasePackageCacheManager$InputStreamWithSrc_base: typeof BasePackageCacheManager$InputStreamWithSrcClass;
/**
 * Class org.hl7.fhir.utilities.npm.BasePackageCacheManager$InputStreamWithSrc.
 *
 * This actually imports the java class for further use.
 * The class {@link BasePackageCacheManager$InputStreamWithSrcClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class BasePackageCacheManager$InputStreamWithSrc extends BasePackageCacheManager$InputStreamWithSrc_base {
}
export default BasePackageCacheManager$InputStreamWithSrc;
//# sourceMappingURL=BasePackageCacheManager$InputStreamWithSrc.d.ts.map