"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NpmPackage$PackageResourceInformation = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.npm.NpmPackage$PackageResourceInformation.
 *
 * This actually imports the java class for further use.
 * The class {@link NpmPackage$PackageResourceInformationClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class NpmPackage$PackageResourceInformation extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.npm.NpmPackage$PackageResourceInformation') {
}
exports.NpmPackage$PackageResourceInformation = NpmPackage$PackageResourceInformation;
exports.default = NpmPackage$PackageResourceInformation;
//# sourceMappingURL=NpmPackage$PackageResourceInformation.js.map