"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimeTracker$Session = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.TimeTracker$Session.
 *
 * This actually imports the java class for further use.
 * The class {@link TimeTracker$SessionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TimeTracker$Session extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.TimeTracker$Session') {
}
exports.TimeTracker$Session = TimeTracker$Session;
exports.default = TimeTracker$Session;
//# sourceMappingURL=TimeTracker$Session.js.map