import { JavaClass, BasicOrJavaType } from "java-bridge";
import { Long as java_lang_Long } from "./../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../java/lang/Class";
import { TimeTracker as org_hl7_fhir_utilities_TimeTracker } from "./TimeTracker";
/**
 * This class just defines types, you should import {@link TimeTracker$Session} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class TimeTracker$SessionClass extends JavaClass {
    /**
     * @return original return type: 'void'
     */
    end(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    endSync(): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TimeTracker'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.TimeTracker$Session'
     */
    static newInstanceAsync(var0: org_hl7_fhir_utilities_TimeTracker | null, var1: string | null): Promise<TimeTracker$Session>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TimeTracker'
     * @param var1 original type: 'java.lang.String'
     */
    constructor(var0: org_hl7_fhir_utilities_TimeTracker | null, var1: string | null);
}
declare const TimeTracker$Session_base: typeof TimeTracker$SessionClass;
/**
 * Class org.hl7.fhir.utilities.TimeTracker$Session.
 *
 * This actually imports the java class for further use.
 * The class {@link TimeTracker$SessionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class TimeTracker$Session extends TimeTracker$Session_base {
}
export default TimeTracker$Session;
//# sourceMappingURL=TimeTracker$Session.d.ts.map