"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ToolingClientLogger = exports.createToolingClientLoggerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ToolingClientLogger} interface.
 * All required methods in {@link ToolingClientLoggerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createToolingClientLoggerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.utilities.ToolingClientLogger', methods, opts);
}
exports.createToolingClientLoggerProxy = createToolingClientLoggerProxy;
/**
 * Class org.hl7.fhir.utilities.ToolingClientLogger.
 *
 * This actually imports the java class for further use.
 * The class {@link ToolingClientLoggerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ToolingClientLogger extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.ToolingClientLogger') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ToolingClientLogger = ToolingClientLogger;
exports.default = ToolingClientLogger;
//# sourceMappingURL=ToolingClientLogger.js.map