"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TranslationServices = exports.createTranslationServicesProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link TranslationServices} interface.
 * All required methods in {@link TranslationServicesInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createTranslationServicesProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.utilities.TranslationServices', methods, opts);
}
exports.createTranslationServicesProxy = createTranslationServicesProxy;
/**
 * Class org.hl7.fhir.utilities.TranslationServices.
 *
 * This actually imports the java class for further use.
 * The class {@link TranslationServicesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TranslationServices extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.TranslationServices') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.TranslationServices = TranslationServices;
exports.default = TranslationServices;
//# sourceMappingURL=TranslationServices.js.map