"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VersionUtilities$VersionURLInfo = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.VersionUtilities$VersionURLInfo.
 *
 * This actually imports the java class for further use.
 * The class {@link VersionUtilities$VersionURLInfoClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class VersionUtilities$VersionURLInfo extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.VersionUtilities$VersionURLInfo') {
}
exports.VersionUtilities$VersionURLInfo = VersionUtilities$VersionURLInfo;
exports.default = VersionUtilities$VersionURLInfo;
//# sourceMappingURL=VersionUtilities$VersionURLInfo.js.map