"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IResourceValidator = exports.createIResourceValidatorProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IResourceValidator} interface.
 * All required methods in {@link IResourceValidatorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIResourceValidatorProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.utils.validation.IResourceValidator', methods, opts);
}
exports.createIResourceValidatorProxy = createIResourceValidatorProxy;
/**
 * Class org.hl7.fhir.r5.utils.validation.IResourceValidator.
 *
 * This actually imports the java class for further use.
 * The class {@link IResourceValidatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IResourceValidator extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.utils.validation.IResourceValidator') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IResourceValidator = IResourceValidator;
exports.default = IResourceValidator;
//# sourceMappingURL=IResourceValidator.js.map