import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { Element as org_hl7_fhir_r5_elementmodel_Element } from "./../../elementmodel/Element";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../../../java/util/List";
import { Resource as org_hl7_fhir_r5_model_Resource } from "./../../model/Resource";
import { Element as org_w3c_dom_Element, ElementInterface as org_w3c_dom_ElementInterface } from "./../../../../../w3c/dom/Element";
import { InputStream as java_io_InputStream } from "./../../../../../../java/io/InputStream";
import { Manager$FhirFormat as org_hl7_fhir_r5_elementmodel_Manager$FhirFormat } from "./../../elementmodel/Manager$FhirFormat";
import { Document as org_w3c_dom_Document, DocumentInterface as org_w3c_dom_DocumentInterface } from "./../../../../../w3c/dom/Document";
import { JsonObject as org_hl7_fhir_utilities_json_model_JsonObject } from "./../../../utilities/json/model/JsonObject";
import { Boolean as java_lang_Boolean } from "./../../../../../../java/lang/Boolean";
import { Coding as org_hl7_fhir_r5_model_Coding } from "./../../model/Coding";
import { IValidationPolicyAdvisor as org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor, IValidationPolicyAdvisorInterface as org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisorInterface } from "./IValidationPolicyAdvisor";
import { IValidationProfileUsageTracker as org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker, IValidationProfileUsageTrackerInterface as org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTrackerInterface } from "./IValidationProfileUsageTracker";
import { IValidatorResourceFetcher as org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher, IValidatorResourceFetcherInterface as org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcherInterface } from "./IValidatorResourceFetcher";
import { IdStatus as org_hl7_fhir_r5_utils_validation_constants_IdStatus } from "./constants/IdStatus";
import { CheckDisplayOption as org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption } from "./constants/CheckDisplayOption";
import { BestPracticeWarningLevel as org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel } from "./constants/BestPracticeWarningLevel";
/**
 * This class just defines types, you should import {@link IResourceValidator} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IResourceValidatorClass extends JavaClass {
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: string | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: string | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @return original return type: 'void'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: string | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: string | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: string | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: string | null): Promise<org_hl7_fhir_r5_elementmodel_Element | null>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validateSync(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @return original return type: 'boolean'
     */
    isAllowExamples(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAllowExamplesSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setForPublication(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setForPublicationSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isForPublication(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isForPublicationSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAllowExamples(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAllowExamplesSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Coding'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setJurisdiction(var0: org_hl7_fhir_r5_model_Coding | null): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Coding'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setJurisdictionSync(var0: org_hl7_fhir_r5_model_Coding | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Coding'
     */
    getJurisdiction(): Promise<org_hl7_fhir_r5_model_Coding | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Coding'
     */
    getJurisdictionSync(): org_hl7_fhir_r5_model_Coding | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setPolicyAdvisor(var0: org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisorInterface> | null): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setPolicyAdvisorSync(var0: org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisorInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isCrumbTrails(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isCrumbTrailsSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setCrumbTrails(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setCrumbTrailsSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setTracker(var0: org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTrackerInterface> | null): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setTrackerSync(var0: org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTrackerInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     */
    getTracker(): Promise<org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     */
    getTrackerSync(): org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     */
    getFetcher(): Promise<org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     */
    getFetcherSync(): org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     */
    getResourceIdRule(): Promise<org_hl7_fhir_r5_utils_validation_constants_IdStatus | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     */
    getResourceIdRuleSync(): org_hl7_fhir_r5_utils_validation_constants_IdStatus | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setFetcher(var0: org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcherInterface> | null): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setFetcherSync(var0: org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcherInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     */
    getCheckDisplay(): Promise<org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     */
    getCheckDisplaySync(): org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     */
    getPolicyAdvisor(): Promise<org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     */
    getPolicyAdvisorSync(): org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     * @return original return type: 'void'
     */
    setCheckDisplay(var0: org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     * @return original return type: 'void'
     */
    setCheckDisplaySync(var0: org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     * @return original return type: 'void'
     */
    setResourceIdRule(var0: org_hl7_fhir_r5_utils_validation_constants_IdStatus | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     * @return original return type: 'void'
     */
    setResourceIdRuleSync(var0: org_hl7_fhir_r5_utils_validation_constants_IdStatus | null): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoInvariantChecks(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoInvariantChecksSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isWantInvariantInMessage(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isWantInvariantInMessageSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setWantInvariantInMessage(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setWantInvariantInMessageSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoBindingMsgSuppressed(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoBindingMsgSuppressedSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isNoTerminologyChecks(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoTerminologyChecksSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoTerminologyChecks(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoTerminologyChecksSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoExtensibleWarnings(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoExtensibleWarningsSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoExtensibleWarnings(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoExtensibleWarningsSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     */
    getBestPracticeWarningLevel(): Promise<org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     */
    getBestPracticeWarningLevelSync(): org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setBestPracticeWarningLevel(var0: org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setBestPracticeWarningLevelSync(var0: org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoInvariantChecks(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoInvariantChecksSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoBindingMsgSuppressed(var0: java_lang_Boolean | boolean): Promise<IResourceValidator | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoBindingMsgSuppressedSync(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoUnicodeBiDiControlChars(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoUnicodeBiDiControlCharsSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setValidateValueSetCodesOnTxServer(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setValidateValueSetCodesOnTxServerSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isAssumeValidRestReferences(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAssumeValidRestReferencesSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoUnicodeBiDiControlChars(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoUnicodeBiDiControlCharsSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setWantCheckSnapshotUnchanged(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setWantCheckSnapshotUnchangedSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setErrorForUnknownProfiles(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setErrorForUnknownProfilesSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isShowMessagesFromReferences(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isShowMessagesFromReferencesSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isValidateValueSetCodesOnTxServer(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isValidateValueSetCodesOnTxServerSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoCheckAggregation(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoCheckAggregationSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setShowMessagesFromReferences(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setShowMessagesFromReferencesSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isWantCheckSnapshotUnchanged(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isWantCheckSnapshotUnchangedSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAssumeValidRestReferences(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAssumeValidRestReferencesSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getBundleValidationRules(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getBundleValidationRulesSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isErrorForUnknownProfiles(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isErrorForUnknownProfilesSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isNoCheckAggregation(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNoCheckAggregationSync(): boolean;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIResourceValidatorProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IResourceValidatorInterface {
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.model.Resource'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_model_Resource | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Element'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Element | JavaInterfaceProxy<org_w3c_dom_ElementInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: string | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Element'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'void'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: string | null, var3: org_hl7_fhir_r5_elementmodel_Element | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'java.io.InputStream'
     * @param var3 original type: 'org.hl7.fhir.r5.elementmodel.Manager$FhirFormat'
     * @param var4 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: java_io_InputStream | null, var3: org_hl7_fhir_r5_elementmodel_Manager$FhirFormat | null, var4: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.w3c.dom.Document'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_w3c_dom_Document | JavaInterfaceProxy<org_w3c_dom_DocumentInterface> | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Element'
     */
    validate(var0: BasicOrJavaType | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_utilities_json_model_JsonObject | null, var3: string | null): org_hl7_fhir_r5_elementmodel_Element | null;
    /**
     * @return original return type: 'boolean'
     */
    isAllowExamples(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setForPublication(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isForPublication(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAllowExamples(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Coding'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setJurisdiction(var0: org_hl7_fhir_r5_model_Coding | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Coding'
     */
    getJurisdiction(): org_hl7_fhir_r5_model_Coding | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setPolicyAdvisor(var0: org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisorInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isCrumbTrails(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setCrumbTrails(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setTracker(var0: org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTrackerInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker'
     */
    getTracker(): org_hl7_fhir_r5_utils_validation_IValidationProfileUsageTracker | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     */
    getFetcher(): org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     */
    getResourceIdRule(): org_hl7_fhir_r5_utils_validation_constants_IdStatus | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IValidatorResourceFetcher'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setFetcher(var0: org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcher | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IValidatorResourceFetcherInterface> | null): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     */
    getCheckDisplay(): org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor'
     */
    getPolicyAdvisor(): org_hl7_fhir_r5_utils_validation_IValidationPolicyAdvisor | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.CheckDisplayOption'
     * @return original return type: 'void'
     */
    setCheckDisplay(var0: org_hl7_fhir_r5_utils_validation_constants_CheckDisplayOption | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.IdStatus'
     * @return original return type: 'void'
     */
    setResourceIdRule(var0: org_hl7_fhir_r5_utils_validation_constants_IdStatus | null): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoInvariantChecks(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isWantInvariantInMessage(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setWantInvariantInMessage(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoBindingMsgSuppressed(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isNoTerminologyChecks(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoTerminologyChecks(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoExtensibleWarnings(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoExtensibleWarnings(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     */
    getBestPracticeWarningLevel(): org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.constants.BestPracticeWarningLevel'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setBestPracticeWarningLevel(var0: org_hl7_fhir_r5_utils_validation_constants_BestPracticeWarningLevel | null): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoInvariantChecks(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     */
    setNoBindingMsgSuppressed(var0: java_lang_Boolean | boolean): IResourceValidator | null;
    /**
     * @return original return type: 'boolean'
     */
    isNoUnicodeBiDiControlChars(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setValidateValueSetCodesOnTxServer(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isAssumeValidRestReferences(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoUnicodeBiDiControlChars(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setWantCheckSnapshotUnchanged(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setErrorForUnknownProfiles(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isShowMessagesFromReferences(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isValidateValueSetCodesOnTxServer(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setNoCheckAggregation(var0: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setShowMessagesFromReferences(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isWantCheckSnapshotUnchanged(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setAssumeValidRestReferences(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getBundleValidationRules(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isErrorForUnknownProfiles(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isNoCheckAggregation(): boolean;
}
/**
 * Create a proxy for the {@link IResourceValidator} interface.
 * All required methods in {@link IResourceValidatorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIResourceValidatorProxy(methods: IResourceValidatorInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IResourceValidatorInterface>;
declare const IResourceValidator_base: typeof IResourceValidatorClass;
/**
 * Class org.hl7.fhir.r5.utils.validation.IResourceValidator.
 *
 * This actually imports the java class for further use.
 * The class {@link IResourceValidatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IResourceValidator extends IResourceValidator_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IResourceValidator;
//# sourceMappingURL=IResourceValidator.d.ts.map