"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IValidationProfileUsageTracker = exports.createIValidationProfileUsageTrackerProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IValidationProfileUsageTracker} interface.
 * All required methods in {@link IValidationProfileUsageTrackerInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIValidationProfileUsageTrackerProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker', methods, opts);
}
exports.createIValidationProfileUsageTrackerProxy = createIValidationProfileUsageTrackerProxy;
/**
 * Class org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationProfileUsageTrackerClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IValidationProfileUsageTracker extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.utils.validation.IValidationProfileUsageTracker') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IValidationProfileUsageTracker = IValidationProfileUsageTracker;
exports.default = IValidationProfileUsageTracker;
//# sourceMappingURL=IValidationProfileUsageTracker.js.map