import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { CodedContentValidationPolicy as org_hl7_fhir_r5_utils_validation_constants_CodedContentValidationPolicy } from "./constants/CodedContentValidationPolicy";
import { IResourceValidator as org_hl7_fhir_r5_utils_validation_IResourceValidator, IResourceValidatorInterface as org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface } from "./IResourceValidator";
import { ElementDefinition as org_hl7_fhir_r5_model_ElementDefinition } from "./../../model/ElementDefinition";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./../../model/StructureDefinition";
import { BindingKind as org_hl7_fhir_r5_utils_validation_constants_BindingKind } from "./constants/BindingKind";
import { ValueSet as org_hl7_fhir_r5_model_ValueSet } from "./../../model/ValueSet";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../../../java/util/List";
import { ReferenceValidationPolicy as org_hl7_fhir_r5_utils_validation_constants_ReferenceValidationPolicy } from "./constants/ReferenceValidationPolicy";
import { ContainedReferenceValidationPolicy as org_hl7_fhir_r5_utils_validation_constants_ContainedReferenceValidationPolicy } from "./constants/ContainedReferenceValidationPolicy";
import { Element$SpecialElement as org_hl7_fhir_r5_elementmodel_Element$SpecialElement } from "./../../elementmodel/Element$SpecialElement";
/**
 * This class just defines types, you should import {@link IValidationPolicyAdvisor} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IValidationPolicyAdvisorClass extends JavaClass {
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var4 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var5 original type: 'org.hl7.fhir.r5.utils.validation.constants.BindingKind'
     * @param var6 original type: 'org.hl7.fhir.r5.model.ValueSet'
     * @param var7 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CodedContentValidationPolicy'
     */
    policyForCodedContent(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: org_hl7_fhir_r5_model_ElementDefinition | null, var4: org_hl7_fhir_r5_model_StructureDefinition | null, var5: org_hl7_fhir_r5_utils_validation_constants_BindingKind | null, var6: org_hl7_fhir_r5_model_ValueSet | null, var7: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<org_hl7_fhir_r5_utils_validation_constants_CodedContentValidationPolicy | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var4 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var5 original type: 'org.hl7.fhir.r5.utils.validation.constants.BindingKind'
     * @param var6 original type: 'org.hl7.fhir.r5.model.ValueSet'
     * @param var7 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CodedContentValidationPolicy'
     */
    policyForCodedContentSync(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: org_hl7_fhir_r5_model_ElementDefinition | null, var4: org_hl7_fhir_r5_model_StructureDefinition | null, var5: org_hl7_fhir_r5_utils_validation_constants_BindingKind | null, var6: org_hl7_fhir_r5_model_ValueSet | null, var7: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_utils_validation_constants_CodedContentValidationPolicy | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ReferenceValidationPolicy'
     */
    policyForReference(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null): Promise<org_hl7_fhir_r5_utils_validation_constants_ReferenceValidationPolicy | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ReferenceValidationPolicy'
     */
    policyForReferenceSync(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null): org_hl7_fhir_r5_utils_validation_constants_ReferenceValidationPolicy | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'org.hl7.fhir.r5.elementmodel.Element$SpecialElement'
     * @param var5 original type: 'java.lang.String'
     * @param var6 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ContainedReferenceValidationPolicy'
     */
    policyForContained(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null, var4: org_hl7_fhir_r5_elementmodel_Element$SpecialElement | null, var5: string | null, var6: string | null): Promise<org_hl7_fhir_r5_utils_validation_constants_ContainedReferenceValidationPolicy | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'org.hl7.fhir.r5.elementmodel.Element$SpecialElement'
     * @param var5 original type: 'java.lang.String'
     * @param var6 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ContainedReferenceValidationPolicy'
     */
    policyForContainedSync(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null, var4: org_hl7_fhir_r5_elementmodel_Element$SpecialElement | null, var5: string | null, var6: string | null): org_hl7_fhir_r5_utils_validation_constants_ContainedReferenceValidationPolicy | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIValidationPolicyAdvisorProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IValidationPolicyAdvisorInterface {
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var4 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var5 original type: 'org.hl7.fhir.r5.utils.validation.constants.BindingKind'
     * @param var6 original type: 'org.hl7.fhir.r5.model.ValueSet'
     * @param var7 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.CodedContentValidationPolicy'
     */
    policyForCodedContent(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: org_hl7_fhir_r5_model_ElementDefinition | null, var4: org_hl7_fhir_r5_model_StructureDefinition | null, var5: org_hl7_fhir_r5_utils_validation_constants_BindingKind | null, var6: org_hl7_fhir_r5_model_ValueSet | null, var7: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): org_hl7_fhir_r5_utils_validation_constants_CodedContentValidationPolicy | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ReferenceValidationPolicy'
     */
    policyForReference(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null): org_hl7_fhir_r5_utils_validation_constants_ReferenceValidationPolicy | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.validation.IResourceValidator'
     * @param var1 original type: 'java.lang.Object'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'org.hl7.fhir.r5.elementmodel.Element$SpecialElement'
     * @param var5 original type: 'java.lang.String'
     * @param var6 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.utils.validation.constants.ContainedReferenceValidationPolicy'
     */
    policyForContained(var0: org_hl7_fhir_r5_utils_validation_IResourceValidator | JavaInterfaceProxy<org_hl7_fhir_r5_utils_validation_IResourceValidatorInterface> | null, var1: BasicOrJavaType | null, var2: string | null, var3: string | null, var4: org_hl7_fhir_r5_elementmodel_Element$SpecialElement | null, var5: string | null, var6: string | null): org_hl7_fhir_r5_utils_validation_constants_ContainedReferenceValidationPolicy | null;
}
/**
 * Create a proxy for the {@link IValidationPolicyAdvisor} interface.
 * All required methods in {@link IValidationPolicyAdvisorInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIValidationPolicyAdvisorProxy(methods: IValidationPolicyAdvisorInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IValidationPolicyAdvisorInterface>;
declare const IValidationPolicyAdvisor_base: typeof IValidationPolicyAdvisorClass;
/**
 * Class org.hl7.fhir.r5.utils.validation.IValidationPolicyAdvisor.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationPolicyAdvisorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IValidationPolicyAdvisor extends IValidationPolicyAdvisor_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IValidationPolicyAdvisor;
//# sourceMappingURL=IValidationPolicyAdvisor.d.ts.map