"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonPrimitive = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.utilities.json.model.JsonPrimitive.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonPrimitiveClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonPrimitive extends (0, java_bridge_1.importClass)('org.hl7.fhir.utilities.json.model.JsonPrimitive') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.JsonPrimitive = JsonPrimitive;
exports.default = JsonPrimitive;
//# sourceMappingURL=JsonPrimitive.js.map