import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { JsonElement as org_hl7_fhir_utilities_json_model_JsonElement } from "./JsonElement";
import { Integer as java_lang_Integer } from "./../../../../../../java/lang/Integer";
import { JsonElementType as org_hl7_fhir_utilities_json_model_JsonElementType } from "./JsonElementType";
import { Iterator as java_util_Iterator } from "./../../../../../../java/util/Iterator";
import { List as java_util_List } from "./../../../../../../java/util/List";
import { Boolean as java_lang_Boolean } from "./../../../../../../java/lang/Boolean";
import { JsonObject as org_hl7_fhir_utilities_json_model_JsonObject } from "./JsonObject";
import { JsonLocationData as org_hl7_fhir_utilities_json_model_JsonLocationData } from "./JsonLocationData";
import { JsonPrimitive as org_hl7_fhir_utilities_json_model_JsonPrimitive } from "./JsonPrimitive";
import { JsonNumber as org_hl7_fhir_utilities_json_model_JsonNumber } from "./JsonNumber";
import { JsonString as org_hl7_fhir_utilities_json_model_JsonString } from "./JsonString";
import { JsonBoolean as org_hl7_fhir_utilities_json_model_JsonBoolean } from "./JsonBoolean";
import { JsonNull as org_hl7_fhir_utilities_json_model_JsonNull } from "./JsonNull";
import { Long as java_lang_Long } from "./../../../../../../java/lang/Long";
import { Class as java_lang_Class } from "./../../../../../../java/lang/Class";
import { Spliterator as java_util_Spliterator } from "./../../../../../../java/util/Spliterator";
import { Consumer as java_util_function_Consumer, ConsumerInterface as java_util_function_ConsumerInterface } from "./../../../../../../java/util/function/Consumer";
/**
 * This class just defines types, you should import {@link JsonArray} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonArrayClass extends JavaClass {
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    add(var0: org_hl7_fhir_utilities_json_model_JsonElement | null): Promise<JsonArray | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    addSync(var0: org_hl7_fhir_utilities_json_model_JsonElement | null): JsonArray | null;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    add(var0: java_lang_Integer | number, var1: org_hl7_fhir_utilities_json_model_JsonElement | null): Promise<JsonArray | null>;
    /**
     * @param var0 original type: 'int'
     * @param var1 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    addSync(var0: java_lang_Integer | number, var1: org_hl7_fhir_utilities_json_model_JsonElement | null): JsonArray | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    add(var0: string | null): Promise<JsonArray | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    addSync(var0: string | null): JsonArray | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'void'
     */
    remove(var0: org_hl7_fhir_utilities_json_model_JsonElement | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @return original return type: 'void'
     */
    removeSync(var0: org_hl7_fhir_utilities_json_model_JsonElement | null): void;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     */
    get(var0: java_lang_Integer | number): Promise<org_hl7_fhir_utilities_json_model_JsonElement | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     */
    getSync(var0: java_lang_Integer | number): org_hl7_fhir_utilities_json_model_JsonElement | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElementType'
     */
    type(): Promise<org_hl7_fhir_utilities_json_model_JsonElementType | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElementType'
     */
    typeSync(): org_hl7_fhir_utilities_json_model_JsonElementType | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'java.lang.Integer'
     */
    size(): Promise<number | null>;
    /**
     * @return original return type: 'java.lang.Integer'
     */
    sizeSync(): number | null;
    /**
     * @return original return type: 'java.util.Iterator'
     */
    iterator(): Promise<java_util_Iterator | null>;
    /**
     * @return original return type: 'java.util.Iterator'
     */
    iteratorSync(): java_util_Iterator | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    deepCopy(): Promise<JsonArray | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    deepCopySync(): JsonArray | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     */
    deepCopy(): Promise<org_hl7_fhir_utilities_json_model_JsonElement | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     */
    deepCopySync(): org_hl7_fhir_utilities_json_model_JsonElement | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getItems(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getItemsSync(): java_util_List | null;
    /**
     * @return original return type: 'java.util.List'
     */
    asStrings(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    asStringsSync(): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    addForParser(var0: org_hl7_fhir_utilities_json_model_JsonElement | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonElement'
     * @param var1 original type: 'boolean'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    addForParserSync(var0: org_hl7_fhir_utilities_json_model_JsonElement | null, var1: java_lang_Boolean | boolean, var2: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isExtraComma(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isExtraCommaSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setExtraComma(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setExtraCommaSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'java.util.List'
     */
    asJsonObjects(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    asJsonObjectsSync(): java_util_List | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     */
    findByStringProp(var0: string | null, var1: string | null): Promise<org_hl7_fhir_utilities_json_model_JsonObject | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     */
    findByStringPropSync(var0: string | null, var1: string | null): org_hl7_fhir_utilities_json_model_JsonObject | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'boolean'
     */
    isNoComma(var0: java_lang_Integer | number): Promise<boolean>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'boolean'
     */
    isNoCommaSync(var0: java_lang_Integer | number): boolean;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'boolean'
     */
    isUnquoted(var0: java_lang_Integer | number): Promise<boolean>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'boolean'
     */
    isUnquotedSync(var0: java_lang_Integer | number): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     * @return original return type: 'void'
     */
    setStart(var0: org_hl7_fhir_utilities_json_model_JsonLocationData | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     * @return original return type: 'void'
     */
    setStartSync(var0: org_hl7_fhir_utilities_json_model_JsonLocationData | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    asString(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    asStringSync(): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     */
    getStart(): Promise<org_hl7_fhir_utilities_json_model_JsonLocationData | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     */
    getStartSync(): org_hl7_fhir_utilities_json_model_JsonLocationData | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     */
    getEnd(): Promise<org_hl7_fhir_utilities_json_model_JsonLocationData | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     */
    getEndSync(): org_hl7_fhir_utilities_json_model_JsonLocationData | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     * @return original return type: 'void'
     */
    setEnd(var0: org_hl7_fhir_utilities_json_model_JsonLocationData | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.json.model.JsonLocationData'
     * @return original return type: 'void'
     */
    setEndSync(var0: org_hl7_fhir_utilities_json_model_JsonLocationData | null): void;
    /**
     * @return original return type: 'boolean'
     */
    hasComments(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasCommentsSync(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    getComments(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getCommentsSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isJsonObject(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonObjectSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isJsonArray(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonArraySync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isJsonPrimitive(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonPrimitiveSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isJsonString(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonStringSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isJsonBoolean(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonBooleanSync(): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonPrimitive'
     */
    asJsonPrimitive(): Promise<org_hl7_fhir_utilities_json_model_JsonPrimitive | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonPrimitive'
     */
    asJsonPrimitiveSync(): org_hl7_fhir_utilities_json_model_JsonPrimitive | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonNumber'
     */
    asJsonNumber(): Promise<org_hl7_fhir_utilities_json_model_JsonNumber | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonNumber'
     */
    asJsonNumberSync(): org_hl7_fhir_utilities_json_model_JsonNumber | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonString'
     */
    asJsonString(): Promise<org_hl7_fhir_utilities_json_model_JsonString | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonString'
     */
    asJsonStringSync(): org_hl7_fhir_utilities_json_model_JsonString | null;
    /**
     * @return original return type: 'boolean'
     */
    isJsonNull(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonNullSync(): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     */
    asJsonObject(): Promise<org_hl7_fhir_utilities_json_model_JsonObject | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonObject'
     */
    asJsonObjectSync(): org_hl7_fhir_utilities_json_model_JsonObject | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonBoolean'
     */
    asJsonBoolean(): Promise<org_hl7_fhir_utilities_json_model_JsonBoolean | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonBoolean'
     */
    asJsonBooleanSync(): org_hl7_fhir_utilities_json_model_JsonBoolean | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    asJsonArray(): Promise<JsonArray | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    asJsonArraySync(): JsonArray | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonNull'
     */
    asJsonNull(): Promise<org_hl7_fhir_utilities_json_model_JsonNull | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonNull'
     */
    asJsonNullSync(): org_hl7_fhir_utilities_json_model_JsonNull | null;
    /**
     * @return original return type: 'boolean'
     */
    isJsonNumber(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonNumberSync(): boolean;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    spliterator(): Promise<java_util_Spliterator | null>;
    /**
     * @return original return type: 'java.util.Spliterator'
     */
    spliteratorSync(): java_util_Spliterator | null;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    forEach(var0: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.function.Consumer'
     * @return original return type: 'void'
     */
    forEachSync(var0: java_util_function_Consumer | JavaInterfaceProxy<java_util_function_ConsumerInterface> | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.json.model.JsonArray'
     */
    static newInstanceAsync(): Promise<JsonArray>;
    constructor();
}
declare const JsonArray_base: typeof JsonArrayClass;
/**
 * Class org.hl7.fhir.utilities.json.model.JsonArray.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonArrayClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class JsonArray extends JsonArray_base {
}
export default JsonArray;
//# sourceMappingURL=JsonArray.d.ts.map