import { JavaClass, BasicOrJavaType } from "java-bridge";
import { PEType as org_hl7_fhir_r5_profilemodel_PEType } from "./PEType";
import { Base as org_hl7_fhir_r5_model_Base } from "./../model/Base";
import { List as java_util_List } from "./../../../../../java/util/List";
import { PEDefinition as org_hl7_fhir_r5_profilemodel_PEDefinition } from "./PEDefinition";
import { Identifier as org_hl7_fhir_r5_model_Identifier } from "./../model/Identifier";
import { Address as org_hl7_fhir_r5_model_Address } from "./../model/Address";
import { Quantity as org_hl7_fhir_r5_model_Quantity } from "./../model/Quantity";
import { CodeableConcept as org_hl7_fhir_r5_model_CodeableConcept } from "./../model/CodeableConcept";
import { Reference as org_hl7_fhir_r5_model_Reference } from "./../model/Reference";
import { Date as java_util_Date } from "./../../../../../java/util/Date";
import { Resource as org_hl7_fhir_r5_model_Resource } from "./../model/Resource";
import { PEInstance$PEInstanceDataKind as org_hl7_fhir_r5_profilemodel_PEInstance$PEInstanceDataKind } from "./PEInstance$PEInstanceDataKind";
import { DataType as org_hl7_fhir_r5_model_DataType } from "./../model/DataType";
import { HumanName as org_hl7_fhir_r5_model_HumanName } from "./../model/HumanName";
import { ContactPoint as org_hl7_fhir_r5_model_ContactPoint } from "./../model/ContactPoint";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link PEInstance} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PEInstanceClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEType'
     */
    type(): Promise<org_hl7_fhir_r5_profilemodel_PEType | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEType'
     */
    typeSync(): org_hl7_fhir_r5_profilemodel_PEType | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base'
     */
    data(): Promise<org_hl7_fhir_r5_model_Base | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base'
     */
    dataSync(): org_hl7_fhir_r5_model_Base | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPath(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPathSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    child(var0: string | null): Promise<PEInstance | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    childSync(var0: string | null): PEInstance | null;
    /**
     * @return original return type: 'java.util.List'
     */
    children(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    childrenSync(): java_util_List | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    children(var0: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    childrenSync(var0: string | null): java_util_List | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base'
     */
    getBase(): Promise<org_hl7_fhir_r5_model_Base | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Base'
     */
    getBaseSync(): org_hl7_fhir_r5_model_Base | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    makeChild(var0: string | null): Promise<PEInstance | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    makeChildSync(var0: string | null): PEInstance | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPrimitiveAsString(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getPrimitiveAsStringSync(): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEDefinition'
     */
    definition(): Promise<org_hl7_fhir_r5_profilemodel_PEDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEDefinition'
     */
    definitionSync(): org_hl7_fhir_r5_profilemodel_PEDefinition | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     * @return original return type: 'boolean'
     */
    removeChild(var0: PEInstanceClass | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     * @return original return type: 'boolean'
     */
    removeChildSync(var0: PEInstanceClass | null): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Identifier'
     */
    Identifier(): Promise<org_hl7_fhir_r5_model_Identifier | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Identifier'
     */
    IdentifierSync(): org_hl7_fhir_r5_model_Identifier | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Address'
     */
    Address(): Promise<org_hl7_fhir_r5_model_Address | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Address'
     */
    AddressSync(): org_hl7_fhir_r5_model_Address | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Quantity'
     */
    asQuantity(): Promise<org_hl7_fhir_r5_model_Quantity | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Quantity'
     */
    asQuantitySync(): org_hl7_fhir_r5_model_Quantity | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    forceChild(var0: string | null): Promise<PEInstance | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance'
     */
    forceChildSync(var0: string | null): PEInstance | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.CodeableConcept'
     */
    asCodeableConcept(): Promise<org_hl7_fhir_r5_model_CodeableConcept | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.CodeableConcept'
     */
    asCodeableConceptSync(): org_hl7_fhir_r5_model_CodeableConcept | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Reference'
     */
    asReference(): Promise<org_hl7_fhir_r5_model_Reference | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Reference'
     */
    asReferenceSync(): org_hl7_fhir_r5_model_Reference | null;
    /**
     * @return original return type: 'java.util.Date'
     */
    getPrimitiveAsDate(): Promise<java_util_Date | null>;
    /**
     * @return original return type: 'java.util.Date'
     */
    getPrimitiveAsDateSync(): java_util_Date | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setPrimitiveValue(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setPrimitiveValueSync(var0: string | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Resource'
     */
    asResource(): Promise<org_hl7_fhir_r5_model_Resource | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.Resource'
     */
    asResourceSync(): org_hl7_fhir_r5_model_Resource | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance$PEInstanceDataKind'
     */
    getDataKind(): Promise<org_hl7_fhir_r5_profilemodel_PEInstance$PEInstanceDataKind | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.profilemodel.PEInstance$PEInstanceDataKind'
     */
    getDataKindSync(): org_hl7_fhir_r5_profilemodel_PEInstance$PEInstanceDataKind | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.DataType'
     */
    asDataType(): Promise<org_hl7_fhir_r5_model_DataType | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.DataType'
     */
    asDataTypeSync(): org_hl7_fhir_r5_model_DataType | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.HumanName'
     */
    asHumanName(): Promise<org_hl7_fhir_r5_model_HumanName | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.HumanName'
     */
    asHumanNameSync(): org_hl7_fhir_r5_model_HumanName | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ContactPoint'
     */
    asContactPoint(): Promise<org_hl7_fhir_r5_model_ContactPoint | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ContactPoint'
     */
    asContactPointSync(): org_hl7_fhir_r5_model_ContactPoint | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
}
declare const PEInstance_base: typeof PEInstanceClass;
/**
 * Class org.hl7.fhir.r5.profilemodel.PEInstance.
 *
 * This actually imports the java class for further use.
 * The class {@link PEInstanceClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PEInstance extends PEInstance_base {
}
export default PEInstance;
//# sourceMappingURL=PEInstance.d.ts.map