"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Address$AddressType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.Address$AddressType.
 *
 * This actually imports the java class for further use.
 * The class {@link Address$AddressTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Address$AddressType extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.Address$AddressType') {
}
exports.Address$AddressType = Address$AddressType;
exports.default = Address$AddressType;
//# sourceMappingURL=Address$AddressType.js.map