"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DataRequirement$SortDirection = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.DataRequirement$SortDirection.
 *
 * This actually imports the java class for further use.
 * The class {@link DataRequirement$SortDirectionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DataRequirement$SortDirection extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.DataRequirement$SortDirection') {
}
exports.DataRequirement$SortDirection = DataRequirement$SortDirection;
exports.default = DataRequirement$SortDirection;
//# sourceMappingURL=DataRequirement$SortDirection.js.map