"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Dosage$DosageDoseAndRateComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.Dosage$DosageDoseAndRateComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link Dosage$DosageDoseAndRateComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Dosage$DosageDoseAndRateComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.Dosage$DosageDoseAndRateComponent') {
}
exports.Dosage$DosageDoseAndRateComponent = Dosage$DosageDoseAndRateComponent;
exports.default = Dosage$DosageDoseAndRateComponent;
//# sourceMappingURL=Dosage$DosageDoseAndRateComponent.js.map