"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementDefinition$ReferenceVersionRules = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.ElementDefinition$ReferenceVersionRules.
 *
 * This actually imports the java class for further use.
 * The class {@link ElementDefinition$ReferenceVersionRulesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ElementDefinition$ReferenceVersionRules extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.ElementDefinition$ReferenceVersionRules') {
}
exports.ElementDefinition$ReferenceVersionRules = ElementDefinition$ReferenceVersionRules;
exports.default = ElementDefinition$ReferenceVersionRules;
//# sourceMappingURL=ElementDefinition$ReferenceVersionRules.js.map