"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link ElementDefinition$ElementDefinitionSlicingDiscriminatorComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent') {
}
exports.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent = ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent;
exports.default = ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent;
//# sourceMappingURL=ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent.js.map