"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ElementDefinition$ElementDefinitionBaseComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.ElementDefinition$ElementDefinitionBaseComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link ElementDefinition$ElementDefinitionBaseComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ElementDefinition$ElementDefinitionBaseComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.ElementDefinition$ElementDefinitionBaseComponent') {
}
exports.ElementDefinition$ElementDefinitionBaseComponent = ElementDefinition$ElementDefinitionBaseComponent;
exports.default = ElementDefinition$ElementDefinitionBaseComponent;
//# sourceMappingURL=ElementDefinition$ElementDefinitionBaseComponent.js.map