"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Endpoint$EndpointStatus = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.Endpoint$EndpointStatus.
 *
 * This actually imports the java class for further use.
 * The class {@link Endpoint$EndpointStatusClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Endpoint$EndpointStatus extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.Endpoint$EndpointStatus') {
}
exports.Endpoint$EndpointStatus = Endpoint$EndpointStatus;
exports.default = Endpoint$EndpointStatus;
//# sourceMappingURL=Endpoint$EndpointStatus.js.map