"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleQuantity = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.SimpleQuantity.
 *
 * This actually imports the java class for further use.
 * The class {@link SimpleQuantityClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class SimpleQuantity extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.SimpleQuantity') {
}
exports.SimpleQuantity = SimpleQuantity;
exports.default = SimpleQuantity;
//# sourceMappingURL=SimpleQuantity.js.map