"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StructureDefinition$StructureDefinitionSnapshotComponent = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.StructureDefinition$StructureDefinitionSnapshotComponent.
 *
 * This actually imports the java class for further use.
 * The class {@link StructureDefinition$StructureDefinitionSnapshotComponentClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StructureDefinition$StructureDefinitionSnapshotComponent extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.StructureDefinition$StructureDefinitionSnapshotComponent') {
}
exports.StructureDefinition$StructureDefinitionSnapshotComponent = StructureDefinition$StructureDefinitionSnapshotComponent;
exports.default = StructureDefinition$StructureDefinitionSnapshotComponent;
//# sourceMappingURL=StructureDefinition$StructureDefinitionSnapshotComponent.js.map