"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.StructureDefinition$StructureDefinitionKind = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r4.model.StructureDefinition$StructureDefinitionKind.
 *
 * This actually imports the java class for further use.
 * The class {@link StructureDefinition$StructureDefinitionKindClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class StructureDefinition$StructureDefinitionKind extends (0, java_bridge_1.importClass)('org.hl7.fhir.r4.model.StructureDefinition$StructureDefinitionKind') {
}
exports.StructureDefinition$StructureDefinitionKind = StructureDefinition$StructureDefinitionKind;
exports.default = StructureDefinition$StructureDefinitionKind;
//# sourceMappingURL=StructureDefinition$StructureDefinitionKind.js.map