"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BufferedSource = exports.createBufferedSourceProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link BufferedSource} interface.
 * All required methods in {@link BufferedSourceInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createBufferedSourceProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('okio.BufferedSource', methods, opts);
}
exports.createBufferedSourceProxy = createBufferedSourceProxy;
/**
 * Class okio.BufferedSource.
 *
 * This actually imports the java class for further use.
 * The class {@link BufferedSourceClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BufferedSource extends (0, java_bridge_1.importClass)('okio.BufferedSource') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.BufferedSource = BufferedSource;
exports.default = BufferedSource;
//# sourceMappingURL=BufferedSource.js.map