"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Buffer$UnsafeCursor = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class okio.Buffer$UnsafeCursor.
 *
 * This actually imports the java class for further use.
 * The class {@link Buffer$UnsafeCursorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Buffer$UnsafeCursor extends (0, java_bridge_1.importClass)('okio.Buffer$UnsafeCursor') {
}
exports.Buffer$UnsafeCursor = Buffer$UnsafeCursor;
exports.default = Buffer$UnsafeCursor;
//# sourceMappingURL=Buffer$UnsafeCursor.js.map