"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Segment$Companion = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class okio.Segment$Companion.
 *
 * This actually imports the java class for further use.
 * The class {@link Segment$CompanionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Segment$Companion extends (0, java_bridge_1.importClass)('okio.Segment$Companion') {
}
exports.Segment$Companion = Segment$Companion;
exports.default = Segment$Companion;
//# sourceMappingURL=Segment$Companion.js.map