"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Source = exports.createSourceProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Source} interface.
 * All required methods in {@link SourceInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createSourceProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('okio.Source', methods, opts);
}
exports.createSourceProxy = createSourceProxy;
/**
 * Class okio.Source.
 *
 * This actually imports the java class for further use.
 * The class {@link SourceClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Source extends (0, java_bridge_1.importClass)('okio.Source') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Source = Source;
exports.default = Source;
//# sourceMappingURL=Source.js.map