"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TerminologyServiceErrorClass = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.terminologies.utilities.TerminologyServiceErrorClass.
 *
 * This actually imports the java class for further use.
 * The class {@link TerminologyServiceErrorClassClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class TerminologyServiceErrorClass extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.terminologies.utilities.TerminologyServiceErrorClass') {
}
exports.TerminologyServiceErrorClass = TerminologyServiceErrorClass;
exports.default = TerminologyServiceErrorClass;
//# sourceMappingURL=TerminologyServiceErrorClass.js.map