"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BufferedOutputStream = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class java.io.BufferedOutputStream.
 *
 * This actually imports the java class for further use.
 * The class {@link BufferedOutputStreamClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BufferedOutputStream extends (0, java_bridge_1.importClass)('java.io.BufferedOutputStream') {
}
exports.BufferedOutputStream = BufferedOutputStream;
exports.default = BufferedOutputStream;
//# sourceMappingURL=BufferedOutputStream.js.map