"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DateTimeDt = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.model.primitive.DateTimeDt.
 *
 * This actually imports the java class for further use.
 * The class {@link DateTimeDtClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class DateTimeDt extends (0, java_bridge_1.importClass)('ca.uhn.fhir.model.primitive.DateTimeDt') {
}
exports.DateTimeDt = DateTimeDt;
exports.default = DateTimeDt;
//# sourceMappingURL=DateTimeDt.js.map