"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IdDt = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.model.primitive.IdDt.
 *
 * This actually imports the java class for further use.
 * The class {@link IdDtClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IdDt extends (0, java_bridge_1.importClass)('ca.uhn.fhir.model.primitive.IdDt') {
}
exports.IdDt = IdDt;
exports.default = IdDt;
//# sourceMappingURL=IdDt.js.map