"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseJsonLikeValue$ValueType = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseJsonLikeValue$ValueTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BaseJsonLikeValue$ValueType extends (0, java_bridge_1.importClass)('ca.uhn.fhir.parser.json.BaseJsonLikeValue$ValueType') {
}
exports.BaseJsonLikeValue$ValueType = BaseJsonLikeValue$ValueType;
exports.default = BaseJsonLikeValue$ValueType;
//# sourceMappingURL=BaseJsonLikeValue$ValueType.js.map