"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IParser$OutputStyle = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.formats.IParser$OutputStyle.
 *
 * This actually imports the java class for further use.
 * The class {@link IParser$OutputStyleClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IParser$OutputStyle extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.formats.IParser$OutputStyle') {
}
exports.IParser$OutputStyle = IParser$OutputStyle;
exports.default = IParser$OutputStyle;
//# sourceMappingURL=IParser$OutputStyle.js.map