"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsonParser = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.formats.JsonParser.
 *
 * This actually imports the java class for further use.
 * The class {@link JsonParserClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class JsonParser extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.formats.JsonParser') {
}
exports.JsonParser = JsonParser;
exports.default = JsonParser;
//# sourceMappingURL=JsonParser.js.map