"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Function0 = exports.createFunction0Proxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link Function0} interface.
 * All required methods in {@link Function0Interface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createFunction0Proxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('kotlin.jvm.functions.Function0', methods, opts);
}
exports.createFunction0Proxy = createFunction0Proxy;
/**
 * Class kotlin.jvm.functions.Function0.
 *
 * This actually imports the java class for further use.
 * The class {@link Function0Class} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Function0 extends (0, java_bridge_1.importClass)('kotlin.jvm.functions.Function0') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.Function0 = Function0;
exports.default = Function0;
//# sourceMappingURL=Function0.js.map