"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPhoneticEncoder = exports.createIPhoneticEncoderProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IPhoneticEncoder} interface.
 * All required methods in {@link IPhoneticEncoderInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIPhoneticEncoderProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.context.phonetic.IPhoneticEncoder', methods, opts);
}
exports.createIPhoneticEncoderProxy = createIPhoneticEncoderProxy;
/**
 * Class ca.uhn.fhir.context.phonetic.IPhoneticEncoder.
 *
 * This actually imports the java class for further use.
 * The class {@link IPhoneticEncoderClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IPhoneticEncoder extends (0, java_bridge_1.importClass)('ca.uhn.fhir.context.phonetic.IPhoneticEncoder') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IPhoneticEncoder = IPhoneticEncoder;
exports.default = IPhoneticEncoder;
//# sourceMappingURL=IPhoneticEncoder.js.map