"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FhirValidator = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.validation.FhirValidator.
 *
 * This actually imports the java class for further use.
 * The class {@link FhirValidatorClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class FhirValidator extends (0, java_bridge_1.importClass)('ca.uhn.fhir.validation.FhirValidator') {
}
exports.FhirValidator = FhirValidator;
exports.default = FhirValidator;
//# sourceMappingURL=FhirValidator.js.map