"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IValidationContext = exports.createIValidationContextProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IValidationContext} interface.
 * All required methods in {@link IValidationContextInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIValidationContextProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('ca.uhn.fhir.validation.IValidationContext', methods, opts);
}
exports.createIValidationContextProxy = createIValidationContextProxy;
/**
 * Class ca.uhn.fhir.validation.IValidationContext.
 *
 * This actually imports the java class for further use.
 * The class {@link IValidationContextClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IValidationContext extends (0, java_bridge_1.importClass)('ca.uhn.fhir.validation.IValidationContext') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IValidationContext = IValidationContext;
exports.default = IValidationContext;
//# sourceMappingURL=IValidationContext.js.map