"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResultSeverityEnum = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.validation.ResultSeverityEnum.
 *
 * This actually imports the java class for further use.
 * The class {@link ResultSeverityEnumClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ResultSeverityEnum extends (0, java_bridge_1.importClass)('ca.uhn.fhir.validation.ResultSeverityEnum') {
}
exports.ResultSeverityEnum = ResultSeverityEnum;
exports.default = ResultSeverityEnum;
//# sourceMappingURL=ResultSeverityEnum.js.map