"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValidationResult = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class ca.uhn.fhir.validation.ValidationResult.
 *
 * This actually imports the java class for further use.
 * The class {@link ValidationResultClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ValidationResult extends (0, java_bridge_1.importClass)('ca.uhn.fhir.validation.ValidationResult') {
}
exports.ValidationResult = ValidationResult;
exports.default = ValidationResult;
//# sourceMappingURL=ValidationResult.js.map