"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BaseUnit = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.fhir.ucum.BaseUnit.
 *
 * This actually imports the java class for further use.
 * The class {@link BaseUnitClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class BaseUnit extends (0, java_bridge_1.importClass)('org.fhir.ucum.BaseUnit') {
}
exports.BaseUnit = BaseUnit;
exports.default = BaseUnit;
//# sourceMappingURL=BaseUnit.js.map