"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pair = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.fhir.ucum.Pair.
 *
 * This actually imports the java class for further use.
 * The class {@link PairClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class Pair extends (0, java_bridge_1.importClass)('org.fhir.ucum.Pair') {
}
exports.Pair = Pair;
exports.default = Pair;
//# sourceMappingURL=Pair.js.map