"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBaseResource = exports.createIBaseResourceProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IBaseResource} interface.
 * All required methods in {@link IBaseResourceInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIBaseResourceProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.instance.model.api.IBaseResource', methods, opts);
}
exports.createIBaseResourceProxy = createIBaseResourceProxy;
/**
 * Class org.hl7.fhir.instance.model.api.IBaseResource.
 *
 * This actually imports the java class for further use.
 * The class {@link IBaseResourceClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IBaseResource extends (0, java_bridge_1.importClass)('org.hl7.fhir.instance.model.api.IBaseResource') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IBaseResource = IBaseResource;
exports.default = IBaseResource;
//# sourceMappingURL=IBaseResource.js.map