"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBaseExtension = exports.createIBaseExtensionProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IBaseExtension} interface.
 * All required methods in {@link IBaseExtensionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIBaseExtensionProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.instance.model.api.IBaseExtension', methods, opts);
}
exports.createIBaseExtensionProxy = createIBaseExtensionProxy;
/**
 * Class org.hl7.fhir.instance.model.api.IBaseExtension.
 *
 * This actually imports the java class for further use.
 * The class {@link IBaseExtensionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IBaseExtension extends (0, java_bridge_1.importClass)('org.hl7.fhir.instance.model.api.IBaseExtension') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IBaseExtension = IBaseExtension;
exports.default = IBaseExtension;
//# sourceMappingURL=IBaseExtension.js.map