import { JavaClass, BasicOrJavaType, InterfaceProxyOptions, JavaInterfaceProxy } from "java-bridge";
import { IBaseDatatype as org_hl7_fhir_instance_model_api_IBaseDatatype, IBaseDatatypeInterface as org_hl7_fhir_instance_model_api_IBaseDatatypeInterface } from "./IBaseDatatype";
import { List as java_util_List } from "./../../../../../../java/util/List";
/**
 * This class just defines types, you should import {@link IBaseExtension} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IBaseExtensionClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    getValue(): Promise<org_hl7_fhir_instance_model_api_IBaseDatatype | null>;
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    getValueSync(): org_hl7_fhir_instance_model_api_IBaseDatatype | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'java.lang.Object'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'java.lang.Object'
     */
    setValueSync(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getExtension(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getExtensionSync(): java_util_List | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrl(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrlSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    setUrl(var0: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    setUrlSync(var0: string | null): BasicOrJavaType | null;
    /**
     * @return original return type: 'boolean'
     */
    isEmpty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isEmptySync(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPre(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPreSync(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    hasFormatComment(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasFormatCommentSync(): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    fhirType(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    fhirTypeSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getUserData(var0: string | null): Promise<BasicOrJavaType | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getUserDataSync(var0: string | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    setUserData(var0: string | null, var1: BasicOrJavaType | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    setUserDataSync(var0: string | null, var1: BasicOrJavaType | null): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPost(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPostSync(): java_util_List | null;
}
/**
 * This interface just defines types for creating proxies,
 * you should use {@link createIBaseExtensionProxy} for actually creating the proxies.
 *
 * Optional methods in here may still be required by java.
 * This is caused by typescript not allowing to have both optional and
 * non-optional signatures for the same interface member.
 *
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export interface IBaseExtensionInterface {
    /**
     * @return original return type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     */
    getValue(): org_hl7_fhir_instance_model_api_IBaseDatatype | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.instance.model.api.IBaseDatatype'
     * @return original return type: 'java.lang.Object'
     */
    setValue(var0: org_hl7_fhir_instance_model_api_IBaseDatatype | JavaInterfaceProxy<org_hl7_fhir_instance_model_api_IBaseDatatypeInterface> | null): BasicOrJavaType | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getExtension(): java_util_List | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getUrl(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    setUrl(var0: string | null): BasicOrJavaType | null;
    /**
     * @return original return type: 'boolean'
     */
    isEmpty(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPre(): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    hasFormatComment(): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    fhirType?(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.Object'
     */
    getUserData(var0: string | null): BasicOrJavaType | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.Object'
     * @return original return type: 'void'
     */
    setUserData(var0: string | null, var1: BasicOrJavaType | null): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getFormatCommentsPost(): java_util_List | null;
}
/**
 * Create a proxy for the {@link IBaseExtension} interface.
 * All required methods in {@link IBaseExtensionInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
export declare function createIBaseExtensionProxy(methods: IBaseExtensionInterface, opts?: InterfaceProxyOptions): JavaInterfaceProxy<IBaseExtensionInterface>;
declare const IBaseExtension_base: typeof IBaseExtensionClass;
/**
 * Class org.hl7.fhir.instance.model.api.IBaseExtension.
 *
 * This actually imports the java class for further use.
 * The class {@link IBaseExtensionClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class IBaseExtension extends IBaseExtension_base {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    private constructor();
}
export default IBaseExtension;
//# sourceMappingURL=IBaseExtension.d.ts.map