"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBaseOperationOutcome = exports.createIBaseOperationOutcomeProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IBaseOperationOutcome} interface.
 * All required methods in {@link IBaseOperationOutcomeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIBaseOperationOutcomeProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.instance.model.api.IBaseOperationOutcome', methods, opts);
}
exports.createIBaseOperationOutcomeProxy = createIBaseOperationOutcomeProxy;
/**
 * Class org.hl7.fhir.instance.model.api.IBaseOperationOutcome.
 *
 * This actually imports the java class for further use.
 * The class {@link IBaseOperationOutcomeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IBaseOperationOutcome extends (0, java_bridge_1.importClass)('org.hl7.fhir.instance.model.api.IBaseOperationOutcome') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IBaseOperationOutcome = IBaseOperationOutcome;
exports.default = IBaseOperationOutcome;
//# sourceMappingURL=IBaseOperationOutcome.js.map