"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBase = exports.createIBaseProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IBase} interface.
 * All required methods in {@link IBaseInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIBaseProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.instance.model.api.IBase', methods, opts);
}
exports.createIBaseProxy = createIBaseProxy;
/**
 * Class org.hl7.fhir.instance.model.api.IBase.
 *
 * This actually imports the java class for further use.
 * The class {@link IBaseClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IBase extends (0, java_bridge_1.importClass)('org.hl7.fhir.instance.model.api.IBase') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IBase = IBase;
exports.default = IBase;
//# sourceMappingURL=IBase.js.map