"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IIdType = exports.createIIdTypeProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IIdType} interface.
 * All required methods in {@link IIdTypeInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIIdTypeProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.instance.model.api.IIdType', methods, opts);
}
exports.createIIdTypeProxy = createIIdTypeProxy;
/**
 * Class org.hl7.fhir.instance.model.api.IIdType.
 *
 * This actually imports the java class for further use.
 * The class {@link IIdTypeClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IIdType extends (0, java_bridge_1.importClass)('org.hl7.fhir.instance.model.api.IIdType') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IIdType = IIdType;
exports.default = IIdType;
//# sourceMappingURL=IIdType.js.map