import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { IWorkerContext as org_hl7_fhir_r5_context_IWorkerContext, IWorkerContextInterface as org_hl7_fhir_r5_context_IWorkerContextInterface } from "./../context/IWorkerContext";
import { ElementDefinition as org_hl7_fhir_r5_model_ElementDefinition } from "./../model/ElementDefinition";
import { List as java_util_List } from "./../../../../../java/util/List";
import { TypeDetails as org_hl7_fhir_r5_model_TypeDetails } from "./../model/TypeDetails";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./../model/StructureDefinition";
import { ProfileUtilities as org_hl7_fhir_r5_conformance_profile_ProfileUtilities } from "./../conformance/profile/ProfileUtilities";
import { Long as java_lang_Long } from "./../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link Property} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class PropertyClass extends JavaClass {
    /**
     * @return original return type: 'java.lang.String'
     */
    getName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getNameSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isPrimitive(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isPrimitiveSync(var0: string | null): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isPrimitive(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isPrimitiveSync(): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.r5.context.IWorkerContext'
     */
    getContext(): Promise<org_hl7_fhir_r5_context_IWorkerContext | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.context.IWorkerContext'
     */
    getContextSync(): org_hl7_fhir_r5_context_IWorkerContext | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    getType(var0: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    getTypeSync(var0: string | null): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getType(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getTypeSync(): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    getDefinition(): Promise<org_hl7_fhir_r5_model_ElementDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    getDefinitionSync(): org_hl7_fhir_r5_model_ElementDefinition | null;
    /**
     * @return original return type: 'boolean'
     */
    isResource(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isResourceSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isBaseList(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isBaseListSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getChildProperties(var0: string | null, var1: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getChildPropertiesSync(var0: string | null, var1: string | null): java_util_List | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.r5.model.TypeDetails'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChild(var0: string | null, var1: org_hl7_fhir_r5_model_TypeDetails | null): Promise<Property | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'org.hl7.fhir.r5.model.TypeDetails'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChildSync(var0: string | null, var1: org_hl7_fhir_r5_model_TypeDetails | null): Property | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChild(var0: string | null): Promise<Property | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChildSync(var0: string | null): Property | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChild(var0: string | null, var1: string | null): Promise<Property | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChildSync(var0: string | null, var1: string | null): Property | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isPrimitiveName(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    isPrimitiveNameSync(var0: string | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChildSimpleName(var0: string | null, var1: string | null): Promise<Property | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    getChildSimpleNameSync(var0: string | null, var1: string | null): Property | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    summary(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    summarySync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    hasType(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    hasTypeSync(var0: string | null): boolean;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getStructure(): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getStructureSync(): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @return original return type: 'boolean'
     */
    isList(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isListSync(): boolean;
    /**
     * @return original return type: 'java.lang.Object'
     */
    typeSummary(): Promise<BasicOrJavaType | null>;
    /**
     * @return original return type: 'java.lang.Object'
     */
    typeSummarySync(): BasicOrJavaType | null;
    /**
     * @return original return type: 'boolean'
     */
    isChoice(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isChoiceSync(): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    cloneToType(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<Property | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    cloneToTypeSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Property | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getXmlNamespace(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getXmlNamespaceSync(): string | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getXmlName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getXmlNameSync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    hasImpliedPrefix(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasImpliedPrefixSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    hasTypeSpecifier(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasTypeSpecifierSync(): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    getJsonKeyProperty(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getJsonKeyPropertySync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isNullable(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNullableSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isLogical(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isLogicalSync(): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    getImpliedPrefix(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getImpliedPrefixSync(): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    getUtils(): Promise<org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    getUtilsSync(): org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null;
    /**
     * @return original return type: 'boolean'
     */
    canBeEmpty(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    canBeEmptySync(): boolean;
    /**
     * @return original return type: 'java.util.List'
     */
    getTypeSpecifiers(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getTypeSpecifiersSync(): java_util_List | null;
    /**
     * @return original return type: 'java.lang.String'
     */
    getJsonName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getJsonNameSync(): string | null;
    /**
     * @return original return type: 'boolean'
     */
    isJsonKeyArray(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonKeyArraySync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isTranslatable(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isTranslatableSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    hasJsonName(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    hasJsonNameSync(): boolean;
    /**
     * @return original return type: 'boolean'
     */
    isJsonPrimitiveChoice(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isJsonPrimitiveChoiceSync(): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    getScopedPropertyName(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getScopedPropertyNameSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    IsLogicalAndHasPrimitiveValue(var0: string | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'boolean'
     */
    IsLogicalAndHasPrimitiveValueSync(var0: string | null): boolean;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<Property>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null, var3: org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null, var4: string | null): Promise<Property>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     * @return original return type: 'org.hl7.fhir.r5.elementmodel.Property'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null, var3: org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null): Promise<Property>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null);
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     * @param var4 original type: 'java.lang.String'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null, var3: org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null, var4: string | null);
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var3 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: org_hl7_fhir_r5_model_StructureDefinition | null, var3: org_hl7_fhir_r5_conformance_profile_ProfileUtilities | null);
}
declare const Property_base: typeof PropertyClass;
/**
 * Class org.hl7.fhir.r5.elementmodel.Property.
 *
 * This actually imports the java class for further use.
 * The class {@link PropertyClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class Property extends Property_base {
}
export default Property;
//# sourceMappingURL=Property.d.ts.map