"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IOFileFilter = exports.createIOFileFilterProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link IOFileFilter} interface.
 * All required methods in {@link IOFileFilterInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createIOFileFilterProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.apache.commons.io.filefilter.IOFileFilter', methods, opts);
}
exports.createIOFileFilterProxy = createIOFileFilterProxy;
/**
 * Class org.apache.commons.io.filefilter.IOFileFilter.
 *
 * This actually imports the java class for further use.
 * The class {@link IOFileFilterClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class IOFileFilter extends (0, java_bridge_1.importClass)('org.apache.commons.io.filefilter.IOFileFilter') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.IOFileFilter = IOFileFilter;
exports.default = IOFileFilter;
//# sourceMappingURL=IOFileFilter.js.map