import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { Integer as java_lang_Integer } from "./../../../../../../java/lang/Integer";
import { IWorkerContext as org_hl7_fhir_r5_context_IWorkerContext, IWorkerContextInterface as org_hl7_fhir_r5_context_IWorkerContextInterface } from "./../../context/IWorkerContext";
import { Boolean as java_lang_Boolean } from "./../../../../../../java/lang/Boolean";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../../../java/util/List";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./../../model/StructureDefinition";
import { ElementDefinition as org_hl7_fhir_r5_model_ElementDefinition } from "./../../model/ElementDefinition";
import { OutputStream as java_io_OutputStream } from "./../../../../../../java/io/OutputStream";
import { CSVWriter as org_hl7_fhir_r5_utils_formats_CSVWriter } from "./../../utils/formats/CSVWriter";
import { ProfileUtilities$ElementDefinitionComparer as org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionComparer } from "./ProfileUtilities$ElementDefinitionComparer";
import { ProfileUtilities$ElementDefinitionHolder as org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionHolder } from "./ProfileUtilities$ElementDefinitionHolder";
import { XVerExtensionManager as org_hl7_fhir_r5_utils_XVerExtensionManager } from "./../../utils/XVerExtensionManager";
import { Set as java_util_Set, SetInterface as java_util_SetInterface } from "./../../../../../../java/util/Set";
import { Enumerations$FHIRVersion as org_hl7_fhir_r5_model_Enumerations$FHIRVersion } from "./../../model/Enumerations$FHIRVersion";
import { ProfileUtilities$ElementChoiceGroup as org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementChoiceGroup } from "./ProfileUtilities$ElementChoiceGroup";
import { ElementDefinition$ElementDefinitionConstraintComponent as org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionConstraintComponent } from "./../../model/ElementDefinition$ElementDefinitionConstraintComponent";
import { ProfileKnowledgeProvider as org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider, ProfileKnowledgeProviderInterface as org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProviderInterface } from "./ProfileKnowledgeProvider";
import { ProfileUtilities$SourcedChildDefinitions as org_hl7_fhir_r5_conformance_profile_ProfileUtilities$SourcedChildDefinitions } from "./ProfileUtilities$SourcedChildDefinitions";
import { ProfileUtilities$AllowUnknownProfile as org_hl7_fhir_r5_conformance_profile_ProfileUtilities$AllowUnknownProfile } from "./ProfileUtilities$AllowUnknownProfile";
import { ValidationOptions as org_hl7_fhir_utilities_validation_ValidationOptions } from "./../../../utilities/validation/ValidationOptions";
import { ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent as org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent } from "./../../model/ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent";
import { PrimitiveType as org_hl7_fhir_r5_model_PrimitiveType } from "./../../model/PrimitiveType";
import { Enumeration as org_hl7_fhir_r5_model_Enumeration } from "./../../model/Enumeration";
import { Date as java_util_Date } from "./../../../../../../java/util/Date";
import { TranslationServices as org_hl7_fhir_utilities_TranslationServices, TranslationServicesInterface as org_hl7_fhir_utilities_TranslationServicesInterface } from "./../../../utilities/TranslationServices";
import { Long as java_lang_Long } from "./../../../../../../java/lang/Long";
import { Class as java_lang_Class } from "./../../../../../../java/lang/Class";
import { FHIRPathEngine as org_hl7_fhir_r5_utils_FHIRPathEngine } from "./../../utils/FHIRPathEngine";
/**
 * This class just defines types, you should import {@link ProfileUtilities} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProfileUtilitiesClass extends JavaClass {
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_BASE_MODEL: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_BASE_PATH: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_DERIVATION_EQUALS: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_DERIVATION_POINTER: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_IS_DERIVED: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_GENERATED_IN_SNAPSHOT: string | null;
    /**
     * Original type: 'java.lang.String'
     */
    static readonly UD_ERROR_STATUS: string | null;
    /**
     * Original type: 'int'
     */
    static readonly STATUS_OK: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly STATUS_HINT: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly STATUS_WARNING: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly STATUS_ERROR: java_lang_Integer | number;
    /**
     * Original type: 'int'
     */
    static readonly STATUS_FATAL: java_lang_Integer | number;
    /**
     * @return original return type: 'org.hl7.fhir.r5.context.IWorkerContext'
     */
    getContext(): Promise<org_hl7_fhir_r5_context_IWorkerContext | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.context.IWorkerContext'
     */
    getContextSync(): org_hl7_fhir_r5_context_IWorkerContext | null;
    /**
     * @return original return type: 'boolean'
     */
    isDebug(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isDebugSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setForPublication(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setForPublicationSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isForPublication(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isForPublicationSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setDebug(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setDebugSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'java.util.List'
     */
    getMessages(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getMessagesSync(): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    generateSnapshot(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: string | null, var3: string | null, var4: string | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.lang.String'
     * @param var4 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    generateSnapshotSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: string | null, var3: string | null, var4: string | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getProfile(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getProfileSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    updateURLs(var0: string | null, var1: string | null, var2: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<org_hl7_fhir_r5_model_ElementDefinition | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition'
     */
    updateURLsSync(var0: string | null, var1: string | null, var2: org_hl7_fhir_r5_model_ElementDefinition | null): org_hl7_fhir_r5_model_ElementDefinition | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    closeDifferential(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    closeDifferentialSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): void;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    generateCsv(var0: java_io_OutputStream | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'boolean'
     * @return original return type: 'void'
     */
    generateCsvSync(var0: java_io_OutputStream | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.formats.CSVWriter'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    addToCSV(var0: org_hl7_fhir_r5_utils_formats_CSVWriter | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.formats.CSVWriter'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    addToCSVSync(var0: org_hl7_fhir_r5_utils_formats_CSVWriter | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionComparer'
     * @param var1 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionHolder'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionComparer'
     */
    getComparer(var0: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionComparer | null, var1: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionHolder | null): Promise<org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionComparer | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionComparer'
     * @param var1 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionHolder'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementDefinitionComparer'
     */
    getComparerSync(var0: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionComparer | null, var1: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionHolder | null): org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementDefinitionComparer | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.util.List'
     * @param var4 original type: 'boolean'
     * @return original return type: 'void'
     */
    sortDifferential(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: string | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var4: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.util.List'
     * @param var4 original type: 'boolean'
     * @return original return type: 'void'
     */
    sortDifferentialSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null, var2: string | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var4: java_lang_Boolean | boolean): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    generateExamples(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    generateExamplesSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    setIds(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'void'
     */
    setIdsSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     */
    getXver(): Promise<org_hl7_fhir_r5_utils_XVerExtensionManager | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     */
    getXverSync(): org_hl7_fhir_r5_utils_XVerExtensionManager | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getLocalFileNames(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getLocalFileNamesSync(): java_util_Set | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setThrowException(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setThrowExceptionSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isThrowException(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isThrowExceptionSync(): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setDefWebRoot(var0: string | null): Promise<void>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'void'
     */
    setDefWebRootSync(var0: string | null): void;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefWebRoot(): Promise<string | null>;
    /**
     * @return original return type: 'java.lang.String'
     */
    getDefWebRootSync(): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeBaseDefinition(var0: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeBaseDefinitionSync(var0: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Enumerations$FHIRVersion'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeBaseDefinition(var0: org_hl7_fhir_r5_model_Enumerations$FHIRVersion | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Enumerations$FHIRVersion'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeBaseDefinitionSync(var0: org_hl7_fhir_r5_model_Enumerations$FHIRVersion | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setXver(var0: org_hl7_fhir_r5_utils_XVerExtensionManager | null): Promise<ProfileUtilities | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.utils.XVerExtensionManager'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setXverSync(var0: org_hl7_fhir_r5_utils_XVerExtensionManager | null): ProfileUtilities | null;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionConstraintComponent'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementChoiceGroup'
     */
    processConstraint(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionConstraintComponent | null): Promise<org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementChoiceGroup | null>;
    /**
     * @param var0 original type: 'java.util.List'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionConstraintComponent'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$ElementChoiceGroup'
     */
    processConstraintSync(var0: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var1: org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionConstraintComponent | null): org_hl7_fhir_r5_conformance_profile_ProfileUtilities$ElementChoiceGroup | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.lang.String'
     */
    getRowColor(var0: org_hl7_fhir_r5_model_ElementDefinition | null, var1: java_lang_Boolean | boolean): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var1 original type: 'boolean'
     * @return original return type: 'java.lang.String'
     */
    getRowColorSync(var0: org_hl7_fhir_r5_model_ElementDefinition | null, var1: java_lang_Boolean | boolean): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     */
    getPkp(): Promise<org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     */
    getPkpSync(): org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | null;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'void'
     */
    setLocalFileNames(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'void'
     */
    setLocalFileNamesSync(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isSimpleExtension(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isSimpleExtensionSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'boolean'
     */
    static isResourceBoundary(var0: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'boolean'
     */
    static isResourceBoundarySync(var0: org_hl7_fhir_r5_model_ElementDefinition | null): boolean;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static sdNs(var0: string | null, var1: string | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'java.lang.String'
     */
    static sdNsSync(var0: string | null, var1: string | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions'
     */
    getChildMap(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<org_hl7_fhir_r5_conformance_profile_ProfileUtilities$SourcedChildDefinitions | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions'
     */
    getChildMapSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): org_hl7_fhir_r5_conformance_profile_ProfileUtilities$SourcedChildDefinitions | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: java_lang_Boolean | boolean, var3: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @param var2 original type: 'boolean'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null, var2: java_lang_Boolean | boolean, var3: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     * @param var4 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean, var4: java_lang_Boolean | boolean): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'boolean'
     * @param var4 original type: 'boolean'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: string | null, var2: string | null, var3: java_lang_Boolean | boolean, var4: java_lang_Boolean | boolean): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'java.util.List'
     */
    getChildList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'java.util.List'
     */
    getChildListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): java_util_List | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'java.util.List'
     */
    getSliceList(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<java_util_List | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'java.util.List'
     */
    getSliceListSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: org_hl7_fhir_r5_model_ElementDefinition | null): java_util_List | null;
    /**
     * @return original return type: 'boolean'
     */
    isAutoFixSliceNames(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isAutoFixSliceNamesSync(): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setAutoFixSliceNames(var0: java_lang_Boolean | boolean): Promise<ProfileUtilities | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setAutoFixSliceNamesSync(var0: java_lang_Boolean | boolean): ProfileUtilities | null;
    /**
     * @return original return type: 'java.util.Set'
     */
    getMasterSourceFileNames(): Promise<java_util_Set | null>;
    /**
     * @return original return type: 'java.util.Set'
     */
    getMasterSourceFileNamesSync(): java_util_Set | null;
    /**
     * @return original return type: 'boolean'
     */
    isNewSlicingProcessing(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isNewSlicingProcessingSync(): boolean;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'void'
     */
    setMasterSourceFileNames(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'java.util.Set'
     * @return original return type: 'void'
     */
    setMasterSourceFileNamesSync(var0: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isExtensionDefinition(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isExtensionDefinitionSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$AllowUnknownProfile'
     * @return original return type: 'void'
     */
    setAllowUnknownProfile(var0: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$AllowUnknownProfile | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$AllowUnknownProfile'
     * @return original return type: 'void'
     */
    setAllowUnknownProfileSync(var0: org_hl7_fhir_r5_conformance_profile_ProfileUtilities$AllowUnknownProfile | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeExtensionForVersionedURL(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: string | null): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.lang.String'
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    static makeExtensionForVersionedURLSync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: string | null): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.validation.ValidationOptions'
     */
    getTerminologyServiceOptions(): Promise<org_hl7_fhir_utilities_validation_ValidationOptions | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.validation.ValidationOptions'
     */
    getTerminologyServiceOptionsSync(): org_hl7_fhir_utilities_validation_ValidationOptions | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'void'
     */
    updateFromObligationProfiles(var0: org_hl7_fhir_r5_model_ElementDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition'
     * @return original return type: 'void'
     */
    updateFromObligationProfilesSync(var0: org_hl7_fhir_r5_model_ElementDefinition | null): void;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    generateSchematrons(var0: java_io_OutputStream | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'java.io.OutputStream'
     * @param var1 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    generateSchematronsSync(var0: java_io_OutputStream | null, var1: org_hl7_fhir_r5_model_StructureDefinition | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    populateLogicalSnapshot(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    populateLogicalSnapshotSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): void;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent'
     */
    static interpretR2Discriminator(var0: string | null, var1: java_lang_Boolean | boolean): Promise<org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent'
     */
    static interpretR2DiscriminatorSync(var0: string | null, var1: java_lang_Boolean | boolean): org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent | null;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setNewSlicingProcessing(var0: java_lang_Boolean | boolean): Promise<ProfileUtilities | null>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    setNewSlicingProcessingSync(var0: java_lang_Boolean | boolean): ProfileUtilities | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'java.lang.String'
     */
    static describeExtensionContext(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'java.lang.String'
     */
    static describeExtensionContextSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.validation.ValidationOptions'
     * @return original return type: 'void'
     */
    setTerminologyServiceOptions(var0: org_hl7_fhir_utilities_validation_ValidationOptions | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.validation.ValidationOptions'
     * @return original return type: 'void'
     */
    setTerminologyServiceOptionsSync(var0: org_hl7_fhir_utilities_validation_ValidationOptions | null): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent'
     * @return original return type: 'java.lang.String'
     */
    static buildR2Discriminator(var0: org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent'
     * @return original return type: 'java.lang.String'
     */
    static buildR2DiscriminatorSync(var0: org_hl7_fhir_r5_model_ElementDefinition$ElementDefinitionSlicingDiscriminatorComponent | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    cleanUpDifferential(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'void'
     */
    cleanUpDifferentialSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): void;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$AllowUnknownProfile'
     */
    getAllowUnknownProfile(): Promise<org_hl7_fhir_r5_conformance_profile_ProfileUtilities$AllowUnknownProfile | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$AllowUnknownProfile'
     */
    getAllowUnknownProfileSync(): org_hl7_fhir_r5_conformance_profile_ProfileUtilities$AllowUnknownProfile | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.util.List'
     * @param var4 original type: 'java.util.Set'
     * @param var5 original type: 'java.util.Set'
     * @param var6 original type: 'boolean'
     * @return original return type: 'java.lang.String'
     */
    static processRelativeUrls(var0: string | null, var1: string | null, var2: string | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var4: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var5: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var6: java_lang_Boolean | boolean): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.String'
     * @param var3 original type: 'java.util.List'
     * @param var4 original type: 'java.util.Set'
     * @param var5 original type: 'java.util.Set'
     * @param var6 original type: 'boolean'
     * @return original return type: 'java.lang.String'
     */
    static processRelativeUrlsSync(var0: string | null, var1: string | null, var2: string | null, var3: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var4: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var5: java_util_Set | JavaInterfaceProxy<java_util_SetInterface> | null, var6: java_lang_Boolean | boolean): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isModifierExtension(var0: org_hl7_fhir_r5_model_StructureDefinition | null): Promise<boolean>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @return original return type: 'boolean'
     */
    static isModifierExtensionSync(var0: org_hl7_fhir_r5_model_StructureDefinition | null): boolean;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setWantFixDifferentialFirstElementType(var0: java_lang_Boolean | boolean): Promise<void>;
    /**
     * @param var0 original type: 'boolean'
     * @return original return type: 'void'
     */
    setWantFixDifferentialFirstElementTypeSync(var0: java_lang_Boolean | boolean): void;
    /**
     * @return original return type: 'boolean'
     */
    isWantFixDifferentialFirstElementType(): Promise<boolean>;
    /**
     * @return original return type: 'boolean'
     */
    isWantFixDifferentialFirstElementTypeSync(): boolean;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.PrimitiveType'
     * @return original return type: 'java.lang.String'
     */
    gt(var0: org_hl7_fhir_r5_model_PrimitiveType | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.PrimitiveType'
     * @return original return type: 'java.lang.String'
     */
    gtSync(var0: org_hl7_fhir_r5_model_PrimitiveType | null): string | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Enumeration'
     * @return original return type: 'java.lang.String'
     */
    egt(var0: org_hl7_fhir_r5_model_Enumeration | null): Promise<string | null>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.Enumeration'
     * @return original return type: 'java.lang.String'
     */
    egtSync(var0: org_hl7_fhir_r5_model_Enumeration | null): string | null;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.String'
     */
    translate(var0: string | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.lang.String'
     * @param var1 original type: 'java.lang.String'
     * @param var2 original type: 'java.lang.Object[]'
     * @return original return type: 'java.lang.String'
     */
    translateSync(var0: string | null, var1: string | null, var2: (BasicOrJavaType | null)[] | null): string | null;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    toStr(var0: java_lang_Integer | number): Promise<string | null>;
    /**
     * @param var0 original type: 'int'
     * @return original return type: 'java.lang.String'
     */
    toStrSync(var0: java_lang_Integer | number): string | null;
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'java.lang.String'
     */
    toStr(var0: java_util_Date | null): Promise<string | null>;
    /**
     * @param var0 original type: 'java.util.Date'
     * @return original return type: 'java.lang.String'
     */
    toStrSync(var0: java_util_Date | null): string | null;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.TranslationServices'
     */
    getTranslator(): Promise<org_hl7_fhir_utilities_TranslationServices | null>;
    /**
     * @return original return type: 'org.hl7.fhir.utilities.TranslationServices'
     */
    getTranslatorSync(): org_hl7_fhir_utilities_TranslationServices | null;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TranslationServices'
     * @return original return type: 'void'
     */
    setTranslator(var0: org_hl7_fhir_utilities_TranslationServices | JavaInterfaceProxy<org_hl7_fhir_utilities_TranslationServicesInterface> | null): Promise<void>;
    /**
     * @param var0 original type: 'org.hl7.fhir.utilities.TranslationServices'
     * @return original return type: 'void'
     */
    setTranslatorSync(var0: org_hl7_fhir_utilities_TranslationServices | JavaInterfaceProxy<org_hl7_fhir_utilities_TranslationServicesInterface> | null): void;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | JavaInterfaceProxy<org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProviderInterface> | null): Promise<ProfileUtilities>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     * @param var3 original type: 'org.hl7.fhir.r5.utils.FHIRPathEngine'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | JavaInterfaceProxy<org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProviderInterface> | null, var3: org_hl7_fhir_r5_utils_FHIRPathEngine | null): Promise<ProfileUtilities>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | JavaInterfaceProxy<org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProviderInterface> | null);
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.context.IWorkerContext'
     * @param var1 original type: 'java.util.List'
     * @param var2 original type: 'org.hl7.fhir.r5.conformance.profile.ProfileKnowledgeProvider'
     * @param var3 original type: 'org.hl7.fhir.r5.utils.FHIRPathEngine'
     */
    constructor(var0: org_hl7_fhir_r5_context_IWorkerContext | JavaInterfaceProxy<org_hl7_fhir_r5_context_IWorkerContextInterface> | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null, var2: org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProvider | JavaInterfaceProxy<org_hl7_fhir_r5_conformance_profile_ProfileKnowledgeProviderInterface> | null, var3: org_hl7_fhir_r5_utils_FHIRPathEngine | null);
}
declare const ProfileUtilities_base: typeof ProfileUtilitiesClass;
/**
 * Class org.hl7.fhir.r5.conformance.profile.ProfileUtilities.
 *
 * This actually imports the java class for further use.
 * The class {@link ProfileUtilitiesClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProfileUtilities extends ProfileUtilities_base {
}
export default ProfileUtilities;
//# sourceMappingURL=ProfileUtilities.d.ts.map