"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfileUtilities$SourcedChildDefinitions = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Class org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions.
 *
 * This actually imports the java class for further use.
 * The class {@link ProfileUtilities$SourcedChildDefinitionsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ProfileUtilities$SourcedChildDefinitions extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions') {
}
exports.ProfileUtilities$SourcedChildDefinitions = ProfileUtilities$SourcedChildDefinitions;
exports.default = ProfileUtilities$SourcedChildDefinitions;
//# sourceMappingURL=ProfileUtilities$SourcedChildDefinitions.js.map