import { JavaClass, BasicOrJavaType, JavaInterfaceProxy } from "java-bridge";
import { StructureDefinition as org_hl7_fhir_r5_model_StructureDefinition } from "./../../model/StructureDefinition";
import { List as java_util_List, ListInterface as java_util_ListInterface } from "./../../../../../../java/util/List";
import { Long as java_lang_Long } from "./../../../../../../java/lang/Long";
import { Integer as java_lang_Integer } from "./../../../../../../java/lang/Integer";
import { Class as java_lang_Class } from "./../../../../../../java/lang/Class";
/**
 * This class just defines types, you should import {@link ProfileUtilities$SourcedChildDefinitions} instead of this.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProfileUtilities$SourcedChildDefinitionsClass extends JavaClass {
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getSource(): Promise<org_hl7_fhir_r5_model_StructureDefinition | null>;
    /**
     * @return original return type: 'org.hl7.fhir.r5.model.StructureDefinition'
     */
    getSourceSync(): org_hl7_fhir_r5_model_StructureDefinition | null;
    /**
     * @return original return type: 'java.util.List'
     */
    getList(): Promise<java_util_List | null>;
    /**
     * @return original return type: 'java.util.List'
     */
    getListSync(): java_util_List | null;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @param var1 original type: 'int'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number, var1: java_lang_Integer | number): void;
    /**
     * @return original return type: 'void'
     */
    wait(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    waitSync(): void;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    wait(var0: java_lang_Long | bigint | number): Promise<void>;
    /**
     * @param var0 original type: 'long'
     * @return original return type: 'void'
     */
    waitSync(var0: java_lang_Long | bigint | number): void;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equals(var0: BasicOrJavaType | null): Promise<boolean>;
    /**
     * @param var0 original type: 'java.lang.Object'
     * @return original return type: 'boolean'
     */
    equalsSync(var0: BasicOrJavaType | null): boolean;
    /**
     * @return original return type: 'java.lang.String'
     */
    toString(): Promise<string>;
    /**
     * @return original return type: 'java.lang.String'
     */
    toStringSync(): string;
    /**
     * @return original return type: 'int'
     */
    hashCode(): Promise<number>;
    /**
     * @return original return type: 'int'
     */
    hashCodeSync(): number;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClass(): Promise<java_lang_Class>;
    /**
     * @return original return type: 'java.lang.Class'
     */
    getClassSync(): java_lang_Class;
    /**
     * @return original return type: 'void'
     */
    notify(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifySync(): void;
    /**
     * @return original return type: 'void'
     */
    notifyAll(): Promise<void>;
    /**
     * @return original return type: 'void'
     */
    notifyAllSync(): void;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.util.List'
     * @return original return type: 'org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions'
     */
    static newInstanceAsync(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null): Promise<ProfileUtilities$SourcedChildDefinitions>;
    /**
     * @param var0 original type: 'org.hl7.fhir.r5.model.StructureDefinition'
     * @param var1 original type: 'java.util.List'
     */
    constructor(var0: org_hl7_fhir_r5_model_StructureDefinition | null, var1: java_util_List | JavaInterfaceProxy<java_util_ListInterface> | null);
}
declare const ProfileUtilities$SourcedChildDefinitions_base: typeof ProfileUtilities$SourcedChildDefinitionsClass;
/**
 * Class org.hl7.fhir.r5.conformance.profile.ProfileUtilities$SourcedChildDefinitions.
 *
 * This actually imports the java class for further use.
 * The class {@link ProfileUtilities$SourcedChildDefinitionsClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
export declare class ProfileUtilities$SourcedChildDefinitions extends ProfileUtilities$SourcedChildDefinitions_base {
}
export default ProfileUtilities$SourcedChildDefinitions;
//# sourceMappingURL=ProfileUtilities$SourcedChildDefinitions.d.ts.map