"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITerminologyClient = exports.createITerminologyClientProxy = void 0;
const java_bridge_1 = require("java-bridge");
/**
 * Create a proxy for the {@link ITerminologyClient} interface.
 * All required methods in {@link ITerminologyClientInterface} must be implemented.
 *
 * @param methods the methods to implement
 * @param opts the proxy options
 * @return the proxy
 */
function createITerminologyClientProxy(methods, opts) {
    return (0, java_bridge_1.newProxy)('org.hl7.fhir.r5.terminologies.client.ITerminologyClient', methods, opts);
}
exports.createITerminologyClientProxy = createITerminologyClientProxy;
/**
 * Class org.hl7.fhir.r5.terminologies.client.ITerminologyClient.
 *
 * This actually imports the java class for further use.
 * The class {@link ITerminologyClientClass} only defines types, this is the class you should actually import.
 * Please note that this statement imports the underlying java class at runtime, which may take a while.
 * This was generated by java-bridge.
 * You should probably not edit this.
 */
class ITerminologyClient extends (0, java_bridge_1.importClass)('org.hl7.fhir.r5.terminologies.client.ITerminologyClient') {
    /**
     * Private constructor to prevent instantiation
     * as this is either an abstract class or an interface
     */
    constructor() {
        super();
    }
}
exports.ITerminologyClient = ITerminologyClient;
exports.default = ITerminologyClient;
//# sourceMappingURL=ITerminologyClient.js.map